### ISSUE TITLE
bug please help me this is my project (ubuntu)

### ISSUE THREAD

**Issue by fahernkhan** [astronomer/astronomer-cosmos#1007]
I've tried everything possible but nothing happens and the same thing doesn't happen in the table bigquery want to transform, thanks

![image](https://github.com/astronomer/astronomer-cosmos/assets/128980804/f4e2e0df-410e-41bd-aa87-7b1a9cd1ef87)

![image](https://github.com/astronomer/astronomer-cosmos/assets/128980804/dc0292cf-f87a-4bc0-ab0f-2d14e2d639ea)

![image](https://github.com/astronomer/astronomer-cosmos/assets/128980804/e5aa5d09-259c-4bce-b571-0e6cb6bc5bce)

![image](https://github.com/astronomer/astronomer-cosmos/assets/128980804/c5e519df-41df-4791-8211-03862578ffec)

**Comment by fahernkhan** [comment]
can anyone help me?

**Comment by fahernkhan** [comment]
I want to do an operation using dbt but strangely it can't be run and it doesn't show anything there, can't debug

and there is another addition, why can't I connect my account and project to https://cloud.astronomer.io/ to connect my project with WORKSPACE gosh I've been waiting a long time to log in and connect:v

**Comment by pankajastro** [comment]
You can use `astro-cli` to connect and [deploy](https://www.astronomer.io/docs/astro/cli/astro-deploy) on https://cloud.astronomer.io/  

Here is an example https://github.com/astronomer/cosmos-demo you might like to try

**Comment by tatiana** [comment]
@fahernkhan are you facing issues running dbt in Airflow, or in using Cosmos? By the logs and information you shared, it seems unrelated to Cosmos - so you should probably try to get support in #airflow-dbt in the Airflow Slack: https://apache-airflow-slack.herokuapp.com/

**Comment by fahernkhan** [comment]
okay I have found the bug so when I want to run the dbt command in the astro dev bash terminal, and nothing happens because there is an error namely 'permission initialized' there so we cannot run dbt using the dbt comment and it is not visible therefore The bug lacks instructions and can't be explained, so I'm sorry, so it's visible if there's a 'permission denied' error there.

Thanks
