### ISSUE TITLE
Support deep linking in the DBT docs plugin

### ISSUE THREAD

**Issue by ajsquared** [astronomer/astronomer-cosmos#1029]
### Description

Since the [DBT docs plugin](https://astronomer.github.io/astronomer-cosmos/configuration/hosting-docs.html) uses an iframe, it doesn't support deep linking.

For example, when browsing the docs with `dbt docs serve`, you can get links like `https://<hostname>/view#!/model/model.foo.bar`. This does not happen in this plugin.

### Use case/motivation

It's useful to be able to share links to a particular model in the docs. Without support for deep linking this isn't possible.

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by tatiana** [comment]
It seems it would be technically possible to have links to deep links in iframes: https://mrvirk.com/passing-url-parameters-to-iframe-using-javascript.html, but I wonder if this would be a good approach - since Cosmos doesn't know the actual docs that it will be exposing.

@dwreeves  @bbovenzi do you have any ideas?

**Comment by dwreeves** [comment]
@tatiana Yes! @ajsquared's issue should be seen as a sub-task of #1012.

**Comment by dwreeves** [comment]
Passing the fragment identifier from the parent to the iframe was a simple 3-line change (not sure if it's the best way to do it, but it seems fine):

<img width="761" alt="image" src="https://github.com/astronomer/astronomer-cosmos/assets/31971762/103ce485-3428-4abc-8083-6278dfedc6d5">

The reverse-- passing the fragment identifier from the iframe to the parent may be a little trickier. I'll look into it. I'm not a Javascript / front-end person so we'll see 🤔

**Comment by dwreeves** [comment]
That was fun! I figured it out. 😄 The linking will be bi-directional. PR coming shortly.

**Comment by tatiana** [comment]
Awesome work, @dwreeves , thanks a lot for looking into this and fixing so quickly!
