### ISSUE TITLE
Add support for dbt-teradata 

### ISSUE THREAD

**Issue by sc250072** [astronomer/astronomer-cosmos#1053]
### Description

Establish a new profile configuration tailored for Teradata. This is essential as Teradata employs the dbt adapter named  [dbt-teradata](https://github.com/Teradata/dbt-teradata)  and utilizes the Airflow Provider known as [Teradata Provider](https://airflow.apache.org/docs/apache-airflow-providers-teradata/stable/index.html).

### Use case/motivation

This is essential as Teradata employs the dbt adapter named  [dbt-teradata](https://github.com/Teradata/dbt-teradata)  and utilizes the Airflow Provider known as [Teradata Provider](https://airflow.apache.org/docs/apache-airflow-providers-teradata/stable/index.html).

### Are you willing to submit a PR?

- [X] Yes, I am willing to submit a PR!

**Comment by satish-chinthanippu** [comment]
Currently, Team from Teradata  is contributing to [Airflow](https://github.com/Teradata/airflow), [dbt](https://github.com/Teradata/dbt-teradata), [Airbyte ](https://github.com/Teradata/airbyte)and [Mulesoft](https://github.com/Teradata/mule-teradata-connector). So, we wanted to contribute for this request as well.

**Comment by pankajastro** [comment]
> Currently, Team from Teradata is contributing to [Airflow](https://github.com/Teradata/airflow), [dbt](https://github.com/Teradata/dbt-teradata), [Airbyte ](https://github.com/Teradata/airbyte)and [Mulesoft](https://github.com/Teradata/mule-teradata-connector). So, we wanted to contribute for this request as well.

That's great to hear! Please feel free to submit a PR.

**Comment by satish-chinthanippu** [comment]
> > Currently, Team from Teradata is contributing to [Airflow](https://github.com/Teradata/airflow), [dbt](https://github.com/Teradata/dbt-teradata), [Airbyte ](https://github.com/Teradata/airbyte)and [Mulesoft](https://github.com/Teradata/mule-teradata-connector). So, we wanted to contribute for this request as well.
> 
> That's great to hear! Please feel free to submit a PR.

 I have developed a new profile mapping class for Teradata, which can be viewed at the following link: [link]. Unit tests have been successfully executed. However, an error occurs when attempting to install the package via the whl installer.

> cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/usr/local/bin/dbt', 'ls', '--output', 'json', '--project-dir', '/tmp/tmppe3rpgg5', '--profiles-dir', '/tmp/tmpe6bag4ak', '--profile', 'generated_profile', '--target', 'dev'] due to the error:
12:37:10  Running with dbt=1.7.11
12:37:11  Encountered an error:
Runtime Error
  Credentials in profile "generated_profile", target "dev" invalid: 1025 is not valid under any of the given schemas

**Comment by sc250072** [comment]
> > Currently, Team from Teradata is contributing to [Airflow](https://github.com/Teradata/airflow), [dbt](https://github.com/Teradata/dbt-teradata), [Airbyte ](https://github.com/Teradata/airbyte)and [Mulesoft](https://github.com/Teradata/mule-teradata-connector). So, we wanted to contribute for this request as well.
> 
> That's great to hear! Please feel free to submit a PR.

Here the PR - https://github.com/astronomer/astronomer-cosmos/pull/1077

**Comment by sc250072** [comment]
> > > Currently, Team from Teradata is contributing to [Airflow](https://github.com/Teradata/airflow), [dbt](https://github.com/Teradata/dbt-teradata), [Airbyte ](https://github.com/Teradata/airbyte)and [Mulesoft](https://github.com/Teradata/mule-teradata-connector). So, we wanted to contribute for this request as well.
> > 
> > 
> > That's great to hear! Please feel free to submit a PR.
> 
> I have developed a new profile mapping class for Teradata, which can be viewed at the following [link](https://github.com/astronomer/astronomer-cosmos/compare/main...satish-chinthanippu:astronomer-cosmos:teradata-profile). Unit tests have been successfully executed. However, an error occurs when attempting to install the package via the whl installer. Could someone help with creating integration tests to validate the functionality?
> 
> > cosmos.dbt.graph.CosmosLoadDbtException: Unable to run ['/usr/local/bin/dbt', 'ls', '--output', 'json', '--project-dir', '/tmp/tmppe3rpgg5', '--profiles-dir', '/tmp/tmpe6bag4ak', '--profile', 'generated_profile', '--target', 'dev'] due to the error:
> > 12:37:10  Running with dbt=1.7.11
> > 12:37:11  Encountered an error:
> > Runtime Error
> > Credentials in profile "generated_profile", target "dev" invalid: 1025 is not valid under any of the given schemas

Issue got resolved and Able to run dbt teradata projects from with Airflow with new Teradata cosmos profile mapping configuraton.
