### ISSUE TITLE
[Bug] Test task doesn't accept `full_refresh` kwarg

### ISSUE THREAD

**Issue by CamposContentful** [astronomer/astronomer-cosmos#1062]
### Astronomer Cosmos Version

main (development)

### dbt-core version

1.8.2

### Versions of dbt adapters

dbt-redshift = "^1.8.1"

### LoadMode

DBT_LS_MANIFEST

### ExecutionMode

AWS_EKS

### InvocationMode

None

### airflow version

MWAA 2.7.2

### Operating System

Fedora

### Deployment

Amazon (AWS) MWAA

### What happened?

Hello everyone,
when passing the `full_refresh` parameter in `operator_args` for a `DbtTaskGroup` task. 
I get the following error:

```
airflow.exceptions.AirflowException: Invalid arguments were passed to DbtTestAwsEksOperator (task_id: test). Invalid arguments were:
**kwargs: {'full_refresh': True}
```

The task is defined as:

```
    example_calculation = DbtTaskGroup(
        group_id="example_calculation_models",
        project_config=ProjectConfig(
            manifest_path=f"{os.path.dirname(os.path.realpath(__file__))}/manifest.json",
            project_name="example_calculation",
        ),
        profile_config=ProfileConfig(
            profile_name="default_profile", target_name="airflow", profiles_yml_filepath="./dbt_profiles/profiles.yml"
        ),
        render_config=RenderConfig(
            select=["tag:example_calculation"],
            load_method=LoadMode.DBT_MANIFEST,
            node_converters={
                DbtResourceType("source"): convert_source,  # known dbt node type to Cosmos (part of DbtResourceType)
            },
            test_behavior=TestBehavior.AFTER_ALL,
        ),
        execution_config=ExecutionConfig(execution_mode=ExecutionMode.AWS_EKS, dbt_project_path="/usr/app/dbt/"),
        operator_args={
            "in_cluster": False,
            "image_pull_policy": "Always",
            "get_logs": True,
            "is_delete_operator_pod": True,
            "on_finish_action": "delete_pod",
            "full_refresh": True,
        },
    )
```
My understanding is that the `full_refresh` argument should be ignored by `dbt test`.
I couldn't find any similar issues in the repo, do you an idea if I'm just setting the argument wrong or is something else.

Thanks!

### How to reproduce

For `execution_mode=ExecutionMode.AWS_EKS` set up a dbt project with test and `full_refresh` option in `operator_args`.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Contact Details

jaime.campos@contentful.com

**Comment by tatiana** [comment]
Hi @CamposContentful , thank you for reporting and submitting a fix for this!
Based on the dbt (latest == 1.8) docs, https://docs.getdbt.com/reference/resource-configs/full_refresh, my understanding is also that full-refresh is only a parameter for `dbt run` and `dbt seed`.
