### ISSUE TITLE
[Feature] add task owner to dbt operator

### ISSUE THREAD

**Issue by wornjs** [astronomer/astronomer-cosmos#1065]
### Description

add owner information to DbtxxxOperator 

### Use case/motivation

Each model is created by multiple da.
When a failure occurs, I want to check the owner on the UI without checking the source.

### Are you willing to submit a PR?

- [X] Yes, I am willing to submit a PR!

**Comment by tatiana** [comment]
@wornjs, this looks like a cool feature!

How do you currently represent in dbt a model owner? Do you use the following..?
https://docs.getdbt.com/reference/resource-configs/meta#designate-a-model-owner

It does not look like a big task to map this into the Airflow argument `owner`.

Do you know if dbt also supports setting the `owner` information at a pipeline level? Ideally we'd handle both cases.
