### ISSUE TITLE
Databricks connection, can't use schema

### ISSUE THREAD

**Issue by MikeWallis42** [astronomer/astronomer-cosmos#107]
The databricks connection schema gets set in the db variable here
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/providers/dbt/core/utils/profiles_generator.py#L195
and then ultimately is missed over here because it's expecting it in the schema variable
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/providers/dbt/core/utils/profiles_generator.py#L164

The end result is 
`[2023-01-30, 14:12:14 GMT] {profiles_generator.py:223} ERROR - Please specify a target schema using the schema parameter.`

For the moment I've worked around it by using the schema override option.

**Comment by MikeWallis42** [comment]
@pohek321 apologies for the mention but I've done some dev work on this locally, would it be possible to gain access to push it up so I can share please?

**Comment by pohek321** [comment]
@MikeWallis42 would love to review the PR for you! We do [PR's via forking](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) so you should have access to contribute that way!
