### ISSUE TITLE
[Feature] Allow storing dbt ls cache into Object Store

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#1072]
### Description

Following up on #1014 , we'd like to allow users to store the dbt ls cache into a remote object store, as an alternative to store it in Airflow Variables. This task relates to #927.

### Use case/motivation

Even though the dbt ls is being compressed without significantly affecting the Airflow Metadata database, some users prefer not to have cache information mixed up with their Airflow variables.

### Related issues

* #1014 
* #927 

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by pankajkoti** [comment]
Aiming to create a PR for this tonight. We discussed the approach and clarified doubts in our call today
