### ISSUE TITLE
Add other tasks as dependencies of specific dbt tasks (and not as dependencies of the whole `DbtTaskGroup`)

### ISSUE THREAD

**Issue by gmyrianthous** [astronomer/astronomer-cosmos#112]
At the moment, we can add additional tasks/operators as downstream or upstream dependencies to the `DbtTaskGroup`. 
This means that (e.g. for downstream tasks), all tasks belonging to `DbtTaskGroup` must finish before they get executed. 

Is it possible to add such tasks (e.g. a `PythonOperator`) as a downstream dependency to a specific task within the `DbtTaskGroup` rather than adding it as a dependency to the whole `DbtTaskGroup`?

**Comment by pohek321** [comment]
@gmyrianthous unfortunately, it's not available as a feature today. However, you can set cross-DAG dependencies from individual tasks generated by the `DbtTaskGroup` via [Airflow Datasets](https://docs.astronomer.io/learn/airflow-datasets). Not sure if this would be a viable work around for you?

**Comment by pohek321** [comment]
Haven't heard back for a few weeks. Closing issue as stale.

**Comment by gmyrianthous** [comment]
Hi, I am keen in understanding if that would be helpful to the community and something that would fit in to the direction of the package itself. If so, I am happy to initiate a discussion to share some more technical details as to potential implementation approaches to achieve this. 

From my point of view, this is an extremely useful functionality since many teams need additional Airflow Operators to run in between dbt tasks
