### ISSUE TITLE
[Design]: Callback support

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-cosmos#1121]
Description co-authored by @tatiana @pankajastro 

Cosmos has supported the callback feature in test tasks for a while, as described in: https://astronomer.github.io/astronomer-cosmos/configuration/testing-behavior.html

However, the community has quite often asked us to have a more generic approach, making this feature also available in other situations.

The goal with this epic is to make the callback feature more generic.

Callback-related improvements:
- https://github.com/astronomer/astronomer-cosmos/issues/801
- https://github.com/astronomer/astronomer-cosmos/issues/851
- https://github.com/astronomer/astronomer-cosmos/issues/867
- https://github.com/astronomer/astronomer-cosmos/issues/914
- https://github.com/astronomer/astronomer-cosmos/issues/976

**Comment by phanikumv** [comment]
- Read the associated issues, understand the needs
- Agree on an approach to handle callbacks in Cosmos that meets the needs described in all these issues
- I do not believe we can commit to complete this issue in the current sprint, but any work will help completing it sooner than later

**Comment by pankajkoti** [comment]
Initial thoughts:
Current callback supported on Cosmos model tests, are executed after the operator `build_and_run` command in the `execute` method in only the `local` & `kubernetes` execution modes. It involves extracting the test names & tests results that are then set in the context which is forwarded to the callback function defined by the user in the render config. 

I am currently checking how Airflow implements and supports callback for its operators. Essentially we will also have to extend, override & hook in callback types support similar to how Airflow does for its operators. Also, check if something that is already available with the Airflow's BaseOperator can be readily used, meaning if the BaseOperator in Airflow already supports how to handle the callback types & offers a few customisations, it would be relatively easy to use that since our AbstractDbtBaseOperator (base class for our Cosmos operators) already extends the `BaseOperator`. We however need to check for the set of different operators that Cosmos offers, what is it that we want to set in the context that maybe of interest & use of the callback functions users would define.

Airflow supports 6 types of callbacks: https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html#callback-types and we can try to support as much as possible iteratively.

**Comment by pankajkoti** [comment]
When reviewing the linked issues in the description, a recurring request is the ability to access artifacts from the `target` directory for analysis, regardless of whether the task execution succeeds or fails (with particular importance placed on failure scenarios). Utilizing callbacks appears to be the most logical approach to achieve this. Callbacks can execute post-model/task execution, enabling custom handling of artifacts.

Currently, a notable limitation for users is the transient nature of the temporary directories created by Cosmos. During execution, Cosmos creates a temporary project directory, where dbt commands are run. However, artifacts such as `run_results.json`, compiled SQL files, and other outputs remain in the `target` directory within this temporary directory. Since this temporary directory path is neither exposed nor persisted, users cannot retrieve these files.

That said, Cosmos already provides a mechanism to attach a callback function during dbt runs in local execution mode. This is [exposed here](https://github.com/astronomer/astronomer-cosmos/blob/1abb37145fcc3b756c513a60f04a659491d84761/cosmos/operators/local.py#L143) and is [executed here](https://github.com/astronomer/astronomer-cosmos/blob/1abb37145fcc3b756c513a60f04a659491d84761/cosmos/operators/local.py#L505) after the dbt command finishes running and which has identification to the temporary project directory to operate on.

Furthermore, the `DbtDocsCloudLocalOperator` leverages this callback functionality already by providing a [predefined callback](https://github.com/astronomer/astronomer-cosmos/blob/1abb37145fcc3b756c513a60f04a659491d84761/cosmos/operators/local.py#L830) that uploads a [selection of files](https://github.com/astronomer/astronomer-cosmos/blob/1abb37145fcc3b756c513a60f04a659491d84761/cosmos/operators/local.py#L793) from the `target` directory to cloud storage (e.g., S3, GCS) based on the implementation of the overriding class.

However, we may be lacking sufficient examples and documentation to guide users on how to fully leverage this callback functionality. Addressing this gap could significantly enhance user experience.

Proposed Enhancements:

1. **Helper Functions for Artifact Management**
Introduce helper functions in Cosmos to facilitate artifact management. These functions would allow users to specify a list of files (from the temporary directory’s target folder) to upload to a remote store. For Airflow 2.8+, we could utilize Airflow’s Object Store integration for this purpose, with a fallback implementation for older versions that uses provider-specific hooks (e.g., S3, GCS, Azure). This abstraction would simplify artifact handling for users.
2. **Documentation and Example DAGs**
Provide detailed example DAGs and supporting documentation demonstrating the usage of the proposed helper functions. This would help users understand how to upload target directory files to remote stores and customize callbacks for their specific requirements.
3. **Enhancing Callback Metadata**
Iteratively gather user feedback to determine if additional metadata (beyond the temporary project directory) should be exposed to the callback function. For example, metadata such as the dbt command executed, environment variables, or other contextual information might prove valuable for advanced use cases.
4. **Validation and Expansion of Airflow Callback Support**
Test and confirm that standard [Airflow callback types](https://airflow.apache.org/docs/apache-airflow/stable/administration-and-deployment/logging-monitoring/callbacks.html#callback-types) (e.g., on_success_callback, on_failure_callback) work seamlessly with Cosmos operators, as they do with native Airflow operators. Document these capabilities in our documentation. For broader use cases beyond artifact retrieval, ensure that these callbacks function correctly. If certain callback types are found to be incompatible, prioritize adding support starting with local execution mode, then iteratively extend support to other execution modes.
5. **Regex Support for Output Parsing**
For specific user requests, such as [Issue #914](https://github.com/astronomer/astronomer-cosmos/issues/914), consider providing detailed examples of how to use regular expressions to extract information from dbt command outputs. This could include sample patterns, example use cases, and best practices for parsing logs or other outputs effectively.

By addressing these proposals, we can not only resolve many of the pain points highlighted by users but also provide a more intuitive and flexible way to manage dbt artifacts, ultimately improving the utility and user experience of Cosmos.

-----------------------------------------------------------------
I have planned travel for the next two weeks, but once I return and we receive feedback on these proposals, I’ll be ready to start implementing them. Hopefully, we will stay on track with the milestone dates for Cosmos 1.8.0 🤞🏽
