### ISSUE TITLE
[Bug] Unable to create task group from folder when using DBT_MANIFEST

### ISSUE THREAD

**Issue by micahVictoria** [astronomer/astronomer-cosmos#1141]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.5.1

### dbt-core version

1.8.4

### Versions of dbt adapters

dbt_redshift==1.8.1

### LoadMode

DBT_LS_MANIFEST

### ExecutionMode

LOCAL

### InvocationMode

None

### airflow version

2.9.1

### Operating System

Amazon Linux 2023

### Deployment

Amazon (AWS) MWAA

### Deployment details

I've also tested this in the docker-compose [MWAA local runner](https://github.com/aws/aws-mwaa-local-runner)

### What happened?

When using DBT_MANIFEST as the load_method, cosmos does not generate tasks for models in a path but DBT_LS will.

dbt will allow you to run this as: `dbt ls -s marts.some_folder_with_models` or `dbt ls -s ./models/marts/some_folder_with_models`

## This doesn't work:
```
    project_config=ProjectConfig(
        dbt_project_path=AIRFLOW_HOME / "dags/dbt/dbt-analytics",
        manifest_path=AIRFLOW_HOME / "dags/dbt/dbt-analytics/target/manifest.json",
    ),
    render_config=RenderConfig(
        select=["+marts.some_folder_with_models"],
        load_method=LoadMode.DBT_MANIFEST,
        dbt_executable_path=AIRFLOW_HOME / "dbt_venv/bin/dbt",
    ),
```

![image](https://github.com/user-attachments/assets/3d0e54a7-7c4e-4d31-867e-8dd8c7807186)

## This works:
```
    project_config=ProjectConfig(
        dbt_project_path=AIRFLOW_HOME / "dags/dbt/dbt-analytics",
    ),
    render_config=RenderConfig(
        select=["+marts.some_folder_with_models"],
        load_method=LoadMode.DBT_LS,
        dbt_executable_path=AIRFLOW_HOME / "dbt_venv/bin/dbt",
    ),
```

### How to reproduce

1. in your render config select a folder with models
2. change load_method from DBT_LS to DBT_MANIFEST
3. In the GUI, reload and watch the tasks in the task group disappear

### Anything else :)?

IMO the two methods should return the same DAG, so DBT_MANIFEST should be able to recognize all models and upstream/downstream dependencies in a folder.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Contact Details

mvictoria@healthfirst.org

**Comment by mvictoria** [comment]
@pankajastro - sorry for the profile switch, I've tested with 1.6.0a4 and it still appears to be an issue, here is the example dag using jaffle shop in the ./dev folder

```python
"""
An example DAG that uses Cosmos to render a dbt project into Airflow using a dbt manifest file.
"""

import os
from datetime import datetime
from pathlib import Path

from airflow.decorators import dag
from airflow.operators.empty import EmptyOperator

from cosmos import DbtTaskGroup, ExecutionConfig, LoadMode, ProfileConfig, ProjectConfig, RenderConfig
from cosmos.profiles import DbtProfileConfigVars, PostgresUserPasswordProfileMapping

DEFAULT_DBT_ROOT_PATH = Path(__file__).parent / "dbt"
DBT_ROOT_PATH = Path(os.getenv("DBT_ROOT_PATH", DEFAULT_DBT_ROOT_PATH))

execution_config = ExecutionConfig(dbt_project_path=DBT_ROOT_PATH / "jaffle_shop")

profile_config = ProfileConfig(
    profile_name="default",
    target_name="dev",
    profile_mapping=PostgresUserPasswordProfileMapping(
        conn_id="example_conn",
        profile_args={"schema": "public"},
        dbt_config_vars=DbtProfileConfigVars(send_anonymous_usage_stats=True),
    ),
)

@dag(
    schedule_interval="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    default_args={"retries": 2},
)
def cosmos_manifest_example() -> None:

    pre_dbt = EmptyOperator(task_id="pre_dbt")

    # [START local_example]
    manifest_example = DbtTaskGroup(
        group_id="manifest_example",
        project_config=ProjectConfig(
            manifest_path=DBT_ROOT_PATH / "jaffle_shop" / "target" / "manifest.json",
            project_name="jaffle_shop",
        ),
        profile_config=profile_config,
        render_config=RenderConfig(load_method=LoadMode.DBT_MANIFEST, select=["+path:models/staging"]),
        execution_config=execution_config,
        operator_args={"install_deps": True},
    )
    # [END local_example]

    ls_example = DbtTaskGroup(
        group_id="ls_example",
        project_config=ProjectConfig(
            manifest_path=DBT_ROOT_PATH / "jaffle_shop" / "target" / "manifest.json",
            project_name="jaffle_shop",
        ),
        profile_config=profile_config,
        render_config=RenderConfig(load_method=LoadMode.DBT_LS, select=["+path:models/staging"]),
        execution_config=execution_config,
        operator_args={"install_deps": True},
    )

    post_dbt = EmptyOperator(task_id="post_dbt")

    (pre_dbt >> ls_example >> manifest_example >> post_dbt)

cosmos_manifest_example()
```

you can see I'm still getting an empty task group with DBT_MANIFEST method
![image](https://github.com/user-attachments/assets/d95db0fd-f94d-46a0-8c04-be80cacf9ff1)

**Comment by pankajastro** [comment]
It seems there might be an issue when using a relative path. Could you please update the select argument to be `select=["path:models/staging"]`?

**Comment by mvictoria** [comment]
@pankajastro - `select=["path:models/staging"]` does render correctly with both DBT_LS and DBT_MANIFEST, but selecting upstream or downstream with ``select=["+path:models/staging"]`` or ``select=["path:models/staging+"]`` does not work

**Comment by pankajastro** [comment]
would you like to submit a PR? I’d be happy to review and merge it.

**Comment by mvictoria** [comment]
@pankajastro - I'm getting familiar with the code base, I'll take a stab at it.

**Comment by tatiana** [comment]
Thanks, @micahVictoria , for identifying and proposing a fix for this.

To some extent, this is a duplicate / generalisation of: a previously logged issue #823
