### ISSUE TITLE
Airflow is unable to find dbt_project.yml

### ISSUE THREAD

**Issue by gladwincogoport** [astronomer/astronomer-cosmos#1145]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.5.1

### dbt-core version

1.8.4

### Versions of dbt adapters

dbt-postgres                             1.8.2

### LoadMode

AUTOMATIC

### ExecutionMode

DOCKER

### InvocationMode

None

### airflow version

apache-airflow    2.9.3

### Operating System

MacOS 14.1.2

### Deployment

Astronomer

### What happened?

My airflow cant find my dbt_project.yml file.

Following is my folder structure 

.
├── Dockerfile
├── README.md
├── airflow_settings.yaml
├── dags
│   ├── __pycache__
│   │   ├── dbt_dag.cpython-311.pyc
│   │   └── exampledag.cpython-311.pyc
│   ├── dbt
│   │   └── datapulse_transform
│   │       ├── README.md
│   │       ├── analyses
│   │       ├── dbt_project.yml
│   │       ├── logs
│   │       │   └── dbt.log
│   │       ├── macros
│   │       ├── models
│   │       │   ├── example
│   │       │   │   ├── my_first_dbt_model.sql
│   │       │   │   ├── my_second_dbt_model.sql
│   │       │   │   └── schema.yml
│   │       │   ├── marts
│   │       │   │   └── mart1.sql
│   │       │   └── staging
│   │       │       ├── stg2.sql
│   │       │       └── stg1.sql
│   │       ├── seeds
│   │       ├── snapshots
│   │       ├── target
│   │       │   ├── compiled
│   │       │   │   └── datapulse_transform
│   │       │   │       └── models
│   │       │   │           ├── example
│   │       │   │           │   ├── my_first_dbt_model.sql
│   │       │   │           │   └── my_second_dbt_model.sql
│   │       │   │           ├── marts
│   │       │   │           │   └── mart1.sql
│   │       │   │           └── staging
│   │       │   │               ├── stg1.sql
│   │       │   │               └── stg2.sql
│   │       │   ├── graph.gpickle
│   │       │   ├── graph_summary.json
│   │       │   ├── manifest.json
│   │       │   ├── partial_parse.msgpack
│   │       │   ├── run
│   │       │   │   └── datapulse_transform
│   │       │   │       └── models
│   │       │   │           ├── example
│   │       │   │           │   ├── my_first_dbt_model.sql
│   │       │   │           │   └── my_second_dbt_model.sql
│   │       │   │           ├── marts
│   │       │   │           │   └── mart1.sql
│   │       │   │           └── staging
│   │       │   │               ├── stg1.sql
│   │       │   │               └── stg2.sql
│   │       │   ├── run_results.json
│   │       │   └── semantic_manifest.json
│   │       └── tests
│   ├── dbt_dag.py
│   └── exampledag.py
├── include
├── logs
│   └── dbt.log
├── packages.txt
├── plugins
├── requirements.txt
└── tests
    └── dags
        └── test_dag_example.py

### Relevant log output

```shell
Broken DAG: [/usr/local/airflow/dags/dbt_dag.py]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/cosmos/converter.py", line 214, in _init_
    project_config.validate_project()
  File "/usr/local/lib/python3.11/site-packages/cosmos/config.py", line 207, in validate_project
    raise CosmosValueError(f"Could not find {name} at {path}")
cosmos.exceptions.CosmosValueError: Could not find dbt_project.yml at /Users/gladwingracias_air/Gladwin/cogo-transform/datapulse_dag/dags/datapulse_transform/dbt_project.yml
```

### How to reproduce

dbt_postgres_dag = DbtDag(
    project_config=ProjectConfig(
        "/Users/gladwingracias_air/Gladwin/cogo-transform/datapulse_dag/dags/datapulse_transform"),

    # operator_args={"install_deps": True},
    profile_config=profile_config,
    execution_config=ExecutionConfig(
        dbt_executable_path=f"{os.environ['AIRFLOW_HOME']}/dbt_venv/bin/dbt",),
    schedule_interval="@daily",
    start_date=datetime(2024, 8, 8),  # yyyy-mm-dd
    catchup=False,
    dag_id="dbt_datapulse_dag"
)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by gladwincogoport** [comment]
That fixed the project config path but now the code is unable to find the dbt executable 
cosmos.config.CosmosConfigException: Unable to find the dbt executable, attempted: <dbt> and </usr/local/airflow/dbt_venv/bin/dbt>.

**Comment by gladwincogoport** [comment]
@Dosu 
would I need to create separate dbt projects for different schedules ? 

Lets say that I need to run models for the marketing vertical at an interval of 1 hour but I need to run the models for the finance vertical every 6 hours. 
How can I do this ?

**Comment by matthieuauger** [comment]
Hello, I experienced a similar issue today with Airflow 3 on Astronomer. It took me a few hours to get something working so I'm sharing it here just in case.

When Airflow is parsing the DAG, it can't find the dbt_project.yml, even if when I log in my docker container and cat the exact path given in the error, I see the file content.

The only thing that worked for me was to move the dbt project inside the include/ folder of Astro.

**Comment by dangvietkhanh1511** [comment]
When run DBT . Airflow do this action:
Cloning project to writable temp directory /tmp/tmpq3dk0fl8 from dags/dbt/data_pipeline. It cloned my dbt project (data_pipeline) to a temporary dicrectory call /tmp/tmpq3dk0fl8. 
But when it run dbt project, it encounter error :
No such file or directory: '/tmp/tmpq3dk0fl8/dbt_project.yml'. I assure that dbt/data_pipeline have a file dbt_project.yml but the clone said that it don't have dbt_project.yml
How I can fix that ?
