### ISSUE TITLE
[Bug] Tried to set relationships between tasks in more than one DAG

### ISSUE THREAD

**Issue by davidmorosini** [astronomer/astronomer-cosmos#1218]
### Astronomer Cosmos Version

Other Astronomer Cosmos version (please specify below)

### If "Other Astronomer Cosmos version" selected, which one?

1.6.0

### dbt-core version

1.7.16

### Versions of dbt adapters

dbt-databricks==1.7.16

### LoadMode

DBT_LS_MANIFEST

### ExecutionMode

VIRTUALENV

### InvocationMode

SUBPROCESS

### airflow version

2.8.2

### Operating System

Debian GNU/Linux 12 (bookworm) (Local using docker) 

### Deployment

Other

### What happened?

Hello everyone,

We are trying to update the Cosmos version to `1.6.0` and have encountered a problem. We would like to request your help in understanding what might be happening.

Before describing the issue, please consider the code snippet below. The object `partial_dbt_env` is an instance of `<class 'airflow.models.xcom_arg.PlainXComArg'>`, similar to the example: `{{ task_instance.xcom_pull(task_ids='TASK_ID', dag_id='DAG_NAME', key='return_value') }}`.

```python
from cosmos import DbtTaskGroup, ProjectConfig

project_config = ProjectConfig(
    dbt_project_path=<DBT PROJECT PATH>,
    manifest_path=<MANIFEST PATH>,
    env_vars=partial_dbt_env
)

transform_task_group = DbtTaskGroup(
    group_id=<GROUP ID>,
    project_config=project_config,
    operator_args=<OPERATOR ARGS>,
    profile_config=<PROFILE CONFIG>,
    execution_config=<EXECUTION CONFIG>,
    render_config=<RENDER CONFIG>
)
```

When attempting to update from version `1.5.1` to version `1.6.0` using the code above, we encountered a significant issue. The exception raised is:

```python
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: DAG_NAME>, <DAG: DAG_NAME>}.
```

After investigating, we noticed that the way some assignments are made in the `cosmos/converter.py` code has changed. For example:

- In version `1.5.1` ([see here](https://github.com/astronomer/astronomer-cosmos/blob/astronomer-cosmos-v1.5.1/cosmos/converter.py#L227)), the objects `env_vars` and `dbt_vars` were **assigned by reference**.
- In version `1.6.0` ([see here](https://github.com/astronomer/astronomer-cosmos/blob/astronomer-cosmos-v1.6.0/cosmos/converter.py#L232)), these same objects are **assigned by copy** (using deepcopy).

This change means that Cosmos uses both the original objects and the copies created internally. Since these objects carry a reference to the DAG they belong to, the duplication results in two distinct objects, each referencing a DAG, which is identified by the Airflow code when performing a set of all objects with the DAG identification. Previously, with reference passing, the result was the same object. Now, with the copy, the set operation performed by Airflow considers them as distinct objects, leading to the exception.

**Note:** If the `env_vars` attribute of the `ProjectConfig` object is removed, the issue is immediately resolved. However, this leads to other problems, are need the value from partial_dbt_env because it is the result of a task, and thus it is a templated value.
**Note:** Up to version `1.5.1`, the code works without issues; this problem occurs only in version `1.6.0`.

We would like to understand the reason for this change in how these variable assignments were made (so that we can adopt the best practices established by you) and whether there is a way to work around this issue in version `1.6.0`.

Thank you in advance for your attention and assistance.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/airflow/dags/core_operators/dbt_run.py", line 109, in dbt_run
    transform_task_group = DbtTaskGroup(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/airflow/task_group.py", line 28, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/converter.py", line 295, in __init__
    build_airflow_graph(
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/airflow/graph.py", line 303, in build_airflow_graph
    task_or_group = conversion_function(  # type: ignore
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/airflow/graph.py", line 251, in generate_task_or_group
    task_or_group = create_airflow_task(task_meta, dag, task_group=task_group)
  File "/home/airflow/.local/lib/python3.10/site-packages/cosmos/core/airflow.py", line 33, in get_airflow_task
    airflow_task = Operator(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 445, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1159, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom_arg.py", line 129, in apply_upstream_relationship
    op.set_upstream(operator)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: DAG_NAME>, <DAG: DAG_NAME>}
```

### How to reproduce

Assemble the provided code by filling in the values according to the runtime we use. The key point to reproducing this error is using the XCom return from a Python operator as the dictionary for partial_dbt_env.

```python
from airflow.decorators import task
from cosmos import DbtTaskGroup, ProjectConfig


@task(task_id="build_partial_dbt_env_vars_operator")
def build_partial_dbt_env() -> Dict[str, str | bool]:
    # some code
    # This return is for demonstration purposes only
    return {
        "ENV_VAR_NAME": "value",
        "ENV_VAR_NAME_2": False
    }
  

partial_dbt_env = build_partial_dbt_env()

project_config = ProjectConfig(
    dbt_project_path=<DBT PROJECT PATH>,
    manifest_path=<MANIFEST PATH>,
    env_vars=partial_dbt_env
)

transform_task_group = DbtTaskGroup(
    group_id=<GROUP ID>,
    project_config=project_config,
    operator_args=<OPERATOR ARGS>,
    profile_config=<PROFILE CONFIG>,
    execution_config=<EXECUTION CONFIG>,
    render_config=<RENDER CONFIG>
)

partial_dbt_env >> transform_task_group
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by davidmorosini** [comment]
Hello @tatiana  I hope you're doing well. I noticed that the issue has been closed. Would you have any guidance on this matter? Thank you in advance!

**Comment by tatiana** [comment]
@davidmorosini, I'm sorry that this issue was closed. I contacted the DosuBot team, requesting that they disable this feature of closing issues.

I'm sorry we didn't reply to you beforehand. I'm adding this issue temptingly to our next sprint so that we can give you the deserved attention.

**Comment by davidmorosini** [comment]
Hello, thank you very much for your response, don't worry about the bot. I asked more to get some guidance on the scenario. We are trying to work around the issue here so we can migrate to the latest versions of Cosmos, however, this feature of retrieving values at runtime is quite important for our case. Thank you again for your reply, and I’m available if needed.

**Comment by davidmorosini** [comment]
Thank you very much, @tatiana and @pankajastro, for your support! As soon as the release is available, we will begin the migration testing. Thank you again! =)

**Comment by tatiana** [comment]
@davidmorosini Cosmos 1.8.0 was released!

**Comment by davidmorosini** [comment]
Great news, @tatiana! I will schedule the tests here and post in this thread confirming that everything worked out, so that if others encounter the same issue and happen to see this thread, they will have the feedback as well. =)
