### ISSUE TITLE
Add support for Google Cloud Composer / KubernetesPodOperator

### ISSUE THREAD

**Issue by jpcassil** [astronomer/astronomer-cosmos#128]
It would be helpful to be able to run cosmos in composer. 

There doesn't seem to be a way to do that now, because creating a virtualenv in composer is complex and/or impossible, and even if one gets created, installing the basic package conflicts with the packages that come with composer: https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images

![image](https://user-images.githubusercontent.com/94997997/217144671-fdc3fd8b-fbf6-4bea-8617-f5c4287a048f.png)

results from adding the dbt.bigquery package:
```
+ python3 -m pip check
google-cloud-bigquery 3.5.0 has requirement protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.0.
google-cloud-aiplatform 1.16.1 has requirement google-cloud-bigquery<3.0.0dev,>=1.15.0, but you have google-cloud-bigquery 3.5.0.
dbt-bigquery 1.4.0 has requirement dbt-core~=1.4.0, but you have dbt-core 1.3.1.
The command '/bin/sh -c bash installer.sh $COMPOSER_PYTHON_VERSION  fail' returned a non-zero code: 1
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

To separate environments, `KubernetesPodOperator` seems to be the most natural fit.  It could take a really simple python image.  I'm not sure how feasible this is, but currently the virtualenv creation in managed airflow seems like a no-go.

**Comment by juldrixx** [comment]
I also think that this feature is necessary. I tried to make a PR to open the discussion. The PR is not perfect at all but atleast we can discuss around it.

**Comment by jlaneve** [comment]
PR is merged, so closing this!
