### ISSUE TITLE
[Feature] dbt source rendering: Use `.` instead of `_` between schema & table

### ISSUE THREAD

**Issue by corsettigyg** [astronomer/astronomer-cosmos#1308]
### Description

Currently in cosmos, sources are rendered as emptyOperators with a task_id of `{schema}_{table}_source` 

![Image](https://github.com/user-attachments/assets/1d68fd21-4cb4-4711-8192-85fada8e6258)

The main issue with this naming convention is that the usual convention of naming tables with the schema uses dot (.) instead of underscore (_), and by using underscore in the naming of our tasks, it is not possible to properly identify where the schema name ends and where the table name begins. 

### Use case/motivation

By having a logical separation of the schema and the table, it is easy to extend cosmos and add extra features to the sources. At my company we are adding sensors before the sources, but the process becomes way harder because of something as simple as using the `_` instead of `. `in the name of the task.

### Are you willing to submit a PR?

- [ ] Yes, I am willing to submit a PR!

**Comment by corsettigyg** [comment]
@tatiana totally

**Comment by pankajastro** [comment]
Hi @corsettigyg, I looked into this a bit more. Cosmos only append  `_source` in dbt node name to construct the task id https://github.com/astronomer/astronomer-cosmos/blob/0951f27e522c094998fa4b4f237d1a37d82be037/cosmos/airflow/graph.py#L178. dbt also prefers to use underscore over the dot for the naming model so changing `_source` to `.source` or `__source` I feel would inconsistent. https://docs.getdbt.com/best-practices/how-we-style/1-how-we-style-our-dbt-models#:~:text=Use%20underscores%20for%20naming%20dbt%20models%3B%20avoid%20dots.&text=Most%20data%20platforms%20use%20dots,certain%20parts%20of%20dbt%20Cloud.

**Comment by pankajastro** [comment]
I'm closing this for now, but don't feel free to reopen it if you have any additional input.
