### ISSUE TITLE
[Bug] Fix K8s test on main brach (currently failing)

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#1319]
### Astronomer Cosmos Version

N/A

### dbt-core version

N/A

### Versions of dbt adapters

Cosmos K8s integration tests are failing in our main branch.

This is visible in new PRs, since the issue started happening after the last merge to main:
https://github.com/astronomer/astronomer-cosmos/actions/runs/11796817624/job/32867560902

### LoadMode

AUTOMATIC

### ExecutionMode

AWS_EKS

### InvocationMode

None

### airflow version

N/A

### Operating System

N/A

### Deployment

Official Apache Airflow Helm Chart

### What happened?

K8s tests stopped working in the CI

### Relevant log output

```shell

```

### How to reproduce

Create a branch from main and see the k8s tests failing in the CI

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pankajkoti** [comment]
We merged PR #1320 that checks on the status of the postgres pod -- previously, postgres pod failed & errored as observed in https://github.com/astronomer/astronomer-cosmos/actions/runs/11796817624/job/32867560902 which led to late failure in the K8s tests. It would be nice to observe for a while & if all is well, we can close the issue

**Comment by pankajkoti** [comment]
After discussing with @tatiana we agreed that we could close this ticket & re-open it if we observe any more failures.
