### ISSUE TITLE
[Bug] GoogleCloudProfile dataset argument is not replaced by neither model or yml config, but instead used as a prefix

### ISSUE THREAD

**Issue by vanAkim** [astronomer/astronomer-cosmos#1334]
### Astronomer Cosmos Version

1.6.0

### dbt-core version

1.8.8

### Versions of dbt adapters

dbt-adapters 1.7.0
dbt-bigquery 1.8.3

### LoadMode

AUTOMATIC

### ExecutionMode

VIRTUALENV

### InvocationMode

None

### airflow version

2.5.3

### Operating System

Ubuntu & Docker under WSL2 of windows 11

### Deployment

Docker-Compose

### What happened?

As I'm using `GoogleCloudOauthProfileMapping` and passing the required arguments for `profile_args`, a project, `my_gcp_project`, and a dataset, `my_gcp_dataset`, are set.

By running the current set-up to build the simple `my_first_dbt_model.sql` of the `jaffle_shop` project, the table is correctly created in the correct location, `my_gcp_project.my_gcp_dataset.my_first_dbt_model`.

Now, if I try to overwrite these parameters for this specific model,

- within `{{ config(database='my_other_gcp_project', schema='my_other_gcp_dataset') }}` model config, the new location will become `my_other_gcp_project.my_gcp_dataset_my_other_gcp_dataset.my_first_dbt_model`
- within the yml config for the model, as below, also do the same location, `my_other_gcp_project.my_gcp_dataset_my_other_gcp_dataset.my_first_dbt_model`
  ```yml
  models:
    - name: my_first_dbt_model
      config:
        database: "my_other_gcp_project"
        schema: "my_other_gcp_dataset"
  ```

The word combination database/project and schema/dataset are interchangeable and working as is.

So the database/project is fully overwritten in the appropriate hierarchy (https://docs.getdbt.com/reference/model-configs#configuring-models) but schema/dataset are concatenated.
However, the concatenation occurs only with the Cosmos argument and the dbt upper hierarchical config. For example, if I try both options described above, only the model `config()` will be concatenated with Cosmos value.

### Relevant log output

```shell

```

### How to reproduce

1. Use a GCP profile mapping function, in my case `GoogleCloudOauthProfileMapping`
2. Set a dataset value
3. Set a schema/dataset value for a specific model, either `config()` or yml config.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Contact Details

akim.van-eersel@dailymotion.com

**Comment by pankajastro** [comment]
Hey @vanAkim, Thank you for finding this issue and providing a detailed analysis. Could you please add a test here: https://github.com/astronomer/astronomer-cosmos/blob/main/tests/profiles/bigquery/test_bq_oauth.py for this case and propose the solution? We are planning to do the next release in mid-December.

**Comment by vanAkim** [comment]
After looking at the Cosmos source code and not understanding how this behavior is happening, I've found that it is a native feature of dbt (ref https://docs.getdbt.com/docs/build/custom-schemas#understanding-custom-schemas).
Thus, it has nothing to do with Cosmos, and this issue can be closed I presume.
