### ISSUE TITLE
Enable SQLite adapters tests

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-cosmos#1341]
We are running the SQLite adapters tests for dbt-core 1.4, but these tests have recently started failing. The SQLite adapters have since added support for dbt-core 1.5, so I attempted an upgrade, but that also failed and requires further investigation. There are existing issues in the repository related to upgrading the SQLite adapters to various dbt-core versions, some of which have been open for over a year: 
- https://github.com/codeforkjeff/dbt-sqlite/issues

Additionally, there is an open issue calling for a maintainer for the project: https://github.com/codeforkjeff/dbt-sqlite/issues/48

It's also worth noting that dbt-core 1.4 and 1.5 have reached their End of Life (EOL), as outlined here: https://docs.getdbt.com/docs/dbt-versions/core#latest-releases.

The goal of this ticket is to restore the SQLite adapter tests.

**Comment by tatiana** [comment]
The idea with the sqlite adaptor tests was to have a cheap alternative to the Postgres ones. Perhaps we can look into adopting a not so cheap alternative, BQ, or another one - WDYT?

**Comment by pankajastro** [comment]
BQ option looks good to me, and I believe we already have the credentials set up in CI for this
