### ISSUE TITLE
Improve callback support

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#1349]
This is a follow up to #1121 

The idea is to close all callback issue tasks:
* https://github.com/astronomer/astronomer-cosmos/issues/801
* https://github.com/astronomer/astronomer-cosmos/issues/851
* https://github.com/astronomer/astronomer-cosmos/issues/867
* https://github.com/astronomer/astronomer-cosmos/issues/976

We created a subtask for each of the proposed ideas:
https://github.com/astronomer/astronomer-cosmos/issues/1121#issuecomment-2494598568

**Comment by pankajkoti** [comment]
I am removing https://github.com/astronomer/astronomer-cosmos/issues/914 from this task's description since it is been tackled separately by @pankajastro in PR #1400 & it has the Cosmos 1.8.0 milestone tagged to it. 

With that I am closing this issue as the rest of the issues are already covered
