### ISSUE TITLE
dbt executable file not found in virtual environment of airflow

### ISSUE THREAD

**Issue by bhawesh490** [astronomer/astronomer-cosmos#1388]
Hi 
I am using airflow 2.10.1 version 
This is my startup script of airflow in aws 
#!/bin/bash

if [[ "${MWAA_AIRFLOW_COMPONENT}" != "worker" ]]
then
    exit 0
fi

echo "------------------------------"
echo "Installing virtual Python env"
echo "------------------------------"

pip3 install --upgrade pip

echo "Current Python version:"
python3 --version
echo "..."

sudo pip3 install --user virtualenv
sudo mkdir python3-virtualenv
cd python3-virtualenv
sudo python3 -m venv dbt-env
sudo chmod -R 777 *

echo "------------------------------"
echo "Activating venv in"
$DBT_ENV_PATH
echo "------------------------------"

source dbt-env/bin/activate
pip3 list

echo "------------------------------"
echo "Installing libraries..."
echo "------------------------------"

# do not use sudo, as it will install outside the venv
pip3 install dbt-core==1.8.9 dbt-redshift==1.8.1 dbt-glue==1.8.6

echo "------------------------------"
echo "Venv libraries..."
echo "------------------------------"

pip3 list
dbt --version

echo "------------------------------"
echo "Deactivating venv..."
echo "------------------------------"

deactivate

I have a requirements.txt file 
in this file i am installing cosmos using 
astronomer-cosmos

Now the issue is the ![Image](https://github.com/user-attachments/assets/38ccab92-6907-4e71-a62f-8bcd89c396e1)
Attaching my dag script also 
import os
from datetime import datetime
from cosmos import DbtDag, ProjectConfig, ProfileConfig, ExecutionConfig,RenderConfig
from cosmos.constants import ExecutionMode,LoadMode

profile_config = ProfileConfig(
    profile_name="dbt_glue_demo",
    target_name="dev",
    profiles_yml_filepath=f"{os.environ['AIRFLOW_HOME']}/dags/dbt/dbt_glue_demo/profiles/iceberg/profiles.yml",
)

dbt_glue_dag = DbtDag(
    project_config=ProjectConfig(f"{os.environ['AIRFLOW_HOME']}/dags/dbt/dbt_glue_demo"),
    operator_args={
        "install_deps": True
        },
    profile_config=profile_config,
    render_config=RenderConfig(
            load_method=LoadMode.DBT_LS,
            dbt_executable_path=f"/usr/local/airflow/python3-virtualenv/dbt-env/bin/dbt",
        ),
    execution_config=ExecutionConfig(
        dbt_executable_path=f"/usr/local/airflow/python3-virtualenv/dbt-env/bin/dbt"
                ),
    schedule_interval="@daily",
    start_date=datetime(2023, 9, 10),
    catchup=False,
    dag_id="dbt_glue_cosmos_dag",
)

Dont know why its not able to find the executable?

**Comment by bhawesh490** [comment]
The executable path does exists /usr/local/airflow/python3-virtualenv/dbt-env/bin/dbt
becuase when i am not using cosmos and using conventional bash operator it does work and produces dags.

Example:

test_silver_iceberg = BashOperator(
        task_id='test_silver_iceberg',
        bash_command=f"""
        source {os.environ['AIRFLOW_HOME']}/python3-virtualenv/dbt-env/bin/activate && \
        cp -R /usr/local/airflow/dags/dbt /tmp && \
        echo 'listing project files:' &&\
        ls -R /tmp/dbt/dbt_glue_demo && \
        echo "printing profiles.yml" && \
        cat /tmp/dbt/dbt_glue_demo/profiles/iceberg/profiles.yml && \
        cd /tmp/dbt/dbt_glue_demo && \
        /usr/local/airflow/python3-virtualenv/dbt-env/bin/dbt test -m silver_iceberg --project-dir /tmp/dbt/dbt_glue_demo --profiles-dir /tmp/dbt/dbt_glue_demo/profiles/iceberg/ && \
        rm -rf /tmp/dbt
        """
    )

Only Issue is coming when using cosmos instead of bash operators

**Comment by tatiana** [comment]
Hi @bhawesh490,

I'm unfamiliar with MWAA, but hopefully, some of the following suggestions will get you unblocked.

Did you follow the tutorial to run Cosmos in MWAA?
https://astronomer.github.io/astronomer-cosmos/getting_started/mwaa.html

This used to work in the past, and I would like to know if you reproduced those steps if things work for you.

Regarding the exception you're facing, this is the part of the code that raises it:
https://github.com/astronomer/astronomer-cosmos/blob/fdf70250d1c5adc558c26af7d59c5756d6660cb5/cosmos/config.py#L101-L120

If you try to run this method from within an Airflow task, does it work? It may help with troubleshooting.

Another possible way to help troubleshooting could be to run `which dbt` after you run:
```
echo "------------------------------"
echo "Venv libraries..."
echo "------------------------------"

pip3 list
dbt --version
```

**Comment by bhawesh490** [comment]
Thanks for guiding me on this
