### ISSUE TITLE
DBT Configuration

### ISSUE THREAD

**Issue by AkashSonu14** [astronomer/astronomer-cosmos#1418]
Hi,
I want to know something about dbt like, I am orcherstrating dbt workflows in MWAA and when I written a sample code the task group has been created based on the dependencies in the dbt project. my condition is how we can manage the workflows through our custom arguments like running model one after another or running model when a particular previous model fails. can you give me some document links or some source codes .

**Comment by AkashSonu14** [comment]
transformed_data = DbtTaskGroup(
        group_id="transform"
        project_config=ProjectConfig(DBT_PROJECT_PATH),
        profile_config=profile_config,
        default_args={"retries": 2},     
        operator_args={
            "dbt_cmd_flags": ["--models", "City_data"],
            "fail_fast": True,
            "warn_error": True,
        }
is this correct

**Comment by pankajastro** [comment]
Hey @AkashSonu14,  You could set operator args using `operator_args` param. Please see the docs: https://astronomer.github.io/astronomer-cosmos/configuration/operator-args.html

**Comment by pankajkoti** [comment]
Hi @AkashSonu14, could you please update the title of this issue to something more descriptive? A title like “DBT Configuration” provides little context for the community to understand the issue at a glance. You can refer to the open issues here: https://github.com/astronomer/astronomer-cosmos/issues to see examples of how the community reports issues with clear titles and descriptions. Thank you!
