### ISSUE TITLE
astronomer-cosmos to send openlineage events to s3 bucket or cloudwatch logs

### ISSUE THREAD

**Issue by bhawesh490** [astronomer/astronomer-cosmos#1423]
Hi
Team i am using astronomer-cosmos to create dags for my client projects.
This is running in aws managed airflow environment.
We want to send the open lineage events to the s3 bucket and later on we can consume those events from s3 and push it to aws datazone .
Can you provide some sample snippets to accomplish this?

**Comment by pankajastro** [comment]
Cosmos support openlineage See docs: https://astronomer.github.io/astronomer-cosmos/configuration/lineage.html

To send event at remote location you have to setup transport configuration accordingly See docs: https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/guides/user.html

I tried to find docs to setup transport for s3 and found something here https://openlineage.io/docs/client/java/configuration/#s3 but this for java client.

But I feel there should be way to upload lineage to cloud.

@tatiana / @pankajkoti do you know if uploading lineage to cloud work natively in Cosmos or not?

**Comment by tatiana** [comment]
Thanks for following up on this, @pankajastro ! Yes, all you wrote is accurate.

I improve our OpenLineage docs to highlight limitations regarding which dbt adaptors are supported: #1431

@bhawesh490 since you created #1430, is it correct to assume we can close this ticket?

**Comment by bhawesh490** [comment]
Thanks team
Yes you can close this issue
