### ISSUE TITLE
Cosmos

### ISSUE THREAD

**Issue by AkashSonu14** [astronomer/astronomer-cosmos#1426]
give task arguments for the sequence running of dbt models when cases of fail and pass in the airflow dag using cosmos.
another thing is custom task dependencies in the airflow

**Comment by pankajkoti** [comment]
Hi @AkashSonu14, could you please update the title of this issue to something more descriptive? A title like “Cosmos” provides little context for the community to understand the issue at a glance. You can refer to the open issues here: https://github.com/astronomer/astronomer-cosmos/issues to see examples of how the community reports issues with clear titles and descriptions. Thank you!

Also, it's difficult to follow from the description what is being asked for. Could you please update the description too to help understand the community what is being sought :)
