### ISSUE TITLE
Link DatabricksWorkflowTaskgroup timeout to databricks jobs timeout

### ISSUE THREAD

**Issue by dimberman** [astronomer/astronomer-cosmos#145]
Description:
To prevent infinitely hanging jobs, it would be useful to have the ability to program timeouts for Airflow tasks that are submitted to Databricks. Currently, Databricks jobs do not have timeouts by default which means that a databricks job could run forever even if the Airflow task times out. By linking Airflow task timeouts to Databricks timeouts, we can ensure that long-running tasks do not block other jobs and resources on the platform.

Proposed solution:

Add a configuration option to DatabricksWorkflowTaskGroup to specify a timeout value. When the Databricks Job is submitted, Airflow should include the timeout value as part of the request to Databricks. This will allow Databricks to enforce the timeout and kill the task if it runs for too long.

Potential challenges:

* Ensuring that the timeout value is propagated correctly from Airflow to Databricks.
* Handling cases where the task takes longer to run than the specified timeout (e.g. due to slow network or data access).
Determining an appropriate default timeout value that works for most workflows.

**Comment by dimberman** [comment]
@pankajkoti and I discussed this ticket and Pankaj is going to do a spike on 

1) tying the airflow timeout to the databricks job timeout when submitting
2) sending a "kill" message to databricks if the task takes longer than the timeout

and report findings here cc: @tatiana

**Comment by pankajkoti** [comment]
**Approach 1: Tying the airflow timeout to the Databricks job timeout when submitting**
The approach would use the execution_timeout param available with the BaseOperator and pass it to the Databricks task which accepts `timeout_seconds` as a param in the payload.

_Pros:_
1. Ensures that the Databricks job will eventually and definitely terminate after the set timeout has elapsed and that the job won't run forever as the timeout is set with the Databricks task specification when triggered.

_Cons:_
1. There might be a slight delay between Airflow task and Databricks task timeout. The Airflow task will be shown as failed first as it launches first and within which we trigger the Databricks task. Ideally, this would be a relatively small number of time units.


**Approach 2: Sending a "kill" message to Databricks if the task takes longer than the timeout**
There is no callback on timeout, but Airflow raises an [AirflowTaskTimeout exception](https://airflow.apache.org/docs/apache-airflow/2.2.0/concepts/tasks.html#timeouts) which means for each task we will need to catch the exception and then trigger a client API call to cancel the job run.

_Pros:_
Can't think of any compared to the first approach

_Cons:_
1. There would still be a delay as we're triggering cancel after getting the exception
2. The [cancel API](https://docs.databricks.com/api-explorer/workspace/jobs/cancelrun) works asynchronously and the docs don't mention if it is a hard termination or graceful termination of the job. Ideally, the job should be cancelled irrespective and immediately but the docs don't give a hint about it
3. The Databricks API might not be available when we trigger the cancellation but it was available while creating the job. So, we might need to handle retries and make sure that the job does not remain running forever, thus adding some more implementation challenges.
4. The [cancel API](https://docs.databricks.com/api-explorer/workspace/jobs/cancelrun) only accepts runId as a payload param. Thus we would not be able to reflect the cancellation reason as Timed Out whereas, with the first approach, the job gives a status `Timed Out` upon timeout seconds elapsing

**Comment by pankajkoti** [comment]
Also, `DatabricksWorkflowTaskGroup` which corresponds to the Databricks job (that encompassed notebook tasks), extends Airflow's `TaskGroup` which does not have a parameter called `execution_timeout`. Thus, **Airflow cannot apply and represent timeouts** for a `TaskGroup`. 

In Airflow, however, `tasks` have `execution_timeout` that becomes available with the `BaseOperator` which is extended by the `DatabricksNotebookOperator`. 

I believe we should support timeout param for the Notebook operator tasks and not at the Workflow level Taskgroup.

WDYT @dimberman @tatiana  ?

**Comment by dimberman** [comment]
@pankajkoti thank you for researching this. I think this sounds like a good idea. People will have different timeouts for different notebooks (as they might do drastically different things). We don't have to make this a part of this ticket, but do you think we should have a "default" timeout at the workflow level?

**Comment by pankajkoti** [comment]
@dimberman Do you mean a default timeout declared at the workflow level which gets passed to each of the notebook tasks? Or a default timeout for the workflow (together for all of its tasks) itself?
