### ISSUE TITLE
Implement dbt snapshot nodes

### ISSUE THREAD

**Issue by MikeWallis42** [astronomer/astronomer-cosmos#150]
The classes exist for it but they're not implemented in the rendering part of the project.

**Comment by pohek321** [comment]
@MikeWallis42 are you envisioning that we make a DbtSnapshotOperator that unlocks [this functionality](https://docs.getdbt.com/docs/build/snapshots) to our end users?

**Comment by MikeWallis42** [comment]
@pohek321 yes I'm suggesting that a DbtSnapshotOperator be created and then added as part of the rendering process so that the cosmos rendering process offers support for a broader range of dbt models.
