### ISSUE TITLE
Allow manual trigger arguments to be passed to dbt nodes

### ISSUE THREAD

**Issue by MikeWallis42** [astronomer/astronomer-cosmos#151]
Things like dbt's full-refresh are likely to be run in exceptional circumstances and should not need a deployment to trigger.
In the style of a user story:

> As a Cosmos user I'd like to be able to override some dbt command line flags for specific or all nodes via Airflow params so that I don't have to re-deploy my DAG to production for a one-off DAG run.

**Comment by pohek321** [comment]
@MikeWallis42 not sure how this would work since our global args and command-specific args are parameters on the operators. Can you clarify what the vision is here?

**Comment by MikeWallis42** [comment]
@pohek321 it's possible to pass in JSON configuration to an Airflow DAG when manually triggering it.
I'm wondering whether we could allow users to pass something in like.
```json
{
  "run": [
    {
      "model_name": "orders",
      "args": [
        "--full-refresh"
      ]
    }
  ]
}
```
Within the operator then we can get these from the DAG run context and merge them with the others.

```python3
run_args = context["dag_run"].conf.get("run")
```

We should stipulate what can and can't be added which might inform the JSON structure. I'm just trying to limit the amount of DAG authoring we might have to do because quite a lot of us don't have production access so would have to dev and release to be able to do and ad-hoc process like a full refresh.

**Comment by joppevos** [comment]
Passing configuration through the DAG configuration is super useful and I would love to see that. 
We started a discussion [here](https://apache-airflow.slack.com/archives/C059CC42E9W/p1698025508718199) on Slack

I will try to make a PR that allows templating of the operator_args, so that we can do something like the following example:
```python
operator_args={"full-refresh": True if "{{ dag_run.conf.get('full_refresh') }}" == 'True' else False},
```
