### ISSUE TITLE
Add clarification in docs of how to reference connections

### ISSUE THREAD

**Issue by patawan** [astronomer/astronomer-cosmos#158]
[This docs page](https://astronomer.github.io/astronomer-cosmos/dbt/usage.html#connections-profiles) mentions how a `profiles.yml` file is not required like in a typical `dbt` installation. The page mentions that the Airflow `conn_id` gets translated into a `profiles.yml` file under the hood. Love that, makes my life much easier!
I'm now trying to figure out how that `conn_id` or subsequently generated `profiles.yml` then get referenced in a `dbt` model. Do you just reference the `conn_id` string itself?:

```sql
with source as (

    select * from {{ ref('conn_id') }}

)
```

I'm more than happy to open up a PR to add this to the examples - just need some guidance first 😄

**Comment by patawan** [comment]
After doing some more reading, I think I've gotten myself closer but still need a bit of clarity. 
So passing in a `conn_id` to a `DbtTaskGroup` or `DbtDag` means the tasks within are going to utilize that specified connection. 
Can I then create a `sources.yml` that lists databases available within the connection created by `conn_id`?

For example:
If `conn_id` points to a snowflake account, would the following `sources.yml` be able to use that `conn_id`:
```yaml
version: 2

sources:
  - name: pub
    database: raw  
    schema: pub
    tables:
      - name: orders
      - name: customers
```

And then in my `models` can call 
```sql
select
  ...

from {{ source('pub', 'orders') }}
```

I'm getting my environment set up so I will also test this out myself.

**Comment by pohek321** [comment]
@patawan sorry for the lack of response to your question! So, for clarity are you trying to reference specific information about a connection parameter? For example, are you trying to reference the database, host, or user set on the Airflow connection in dbt?

**Comment by patawan** [comment]
@pohek321 yes at the time I thought I needed to reference the `profiles.yml` generated by cosmos somewhere in my `dbt` models. Didn't realize the `DbtTaskGroup` automagically passes the `profile snowflake_profile`  flag in the `dbt run` command. Admittedly I also didn't have a good grasp of how `dbt` actually functioned :sweat_smile:.


Got everything sorted out and feeling much better about it now. This [precedence section](https://astronomer.github.io/astronomer-cosmos/dbt/connections.html#precedence-order-of-connection-parameters) also helped a ton. Thanks for getting back to me!
