### ISSUE TITLE
Fix and enable type check in the CI

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#173]
This a follow-up from https://github.com/astronomer/astronomer-cosmos/issues/161 (PR https://github.com/astronomer/astronomer-cosmos/pull/167) when we identified there are lots of Type issues. The check is commented on in the CI YAML file. We just need to uncomment and address the issues.

**Comment by pohek321** [comment]
Marking as closed since databricks was separated into its own Repo
