### ISSUE TITLE
Select parameter is not working for tags

### ISSUE THREAD

**Issue by leonardonh** [astronomer/astronomer-cosmos#175]
Hi. I'm trying to use the "select" parameter (https://astronomer.github.io/astronomer-cosmos/dbt/configuration.html) to only run models with specific tags, but the entire project continues to be executed. Any advise on that?

-model.sql
`{{ config(tags='test') }}`

-dag.py
```
with DAG(
    dag_id="dbt_test",
    start_date=datetime(2022, 11, 27),
    doc_md=__doc__,
    catchup=False,
    default_args={"owner":"test"}
) as dag:

    # run only tag:test
    dbt_run = DbtTaskGroup(
        dbt_project_name="dbt_test",
        conn_id="redshift",
        dbt_args={
            "schema": "test",
            "dbt_executable_path": "/usr/local/airflow/dbt_venv/bin/dbt",
        },
        **select={'tags':['test']}**
    )
```

**Comment by jlaneve** [comment]
Hey @leonardonh, good catch - this was just a docs issue. I've updated the docs, check them out and let me know if you have any issues!

https://astronomer.github.io/astronomer-cosmos/dbt/configuration.html#selecting-and-excluding
