### ISSUE TITLE
community connectors support (athena)

### ISSUE THREAD

**Issue by ext-herbert-santos** [astronomer/astronomer-cosmos#201]
Today the Dbt Dag forced to pass the conn id, obliged to use a bank connector, I would like to use cosmos with athena that has with the community connector.

**Comment by felipesanmartin** [comment]
I think [PR-390](https://github.com/astronomer/astronomer-cosmos/pull/390) resolve this issue.

**Comment by benjamin-awd** [comment]
I've raised a PR for this here -- https://github.com/astronomer/astronomer-cosmos/pull/578
