### ISSUE TITLE
Add support for dbt-duckdb adapter

### ISSUE THREAD

**Issue by marclamberti** [astronomer/astronomer-cosmos#202]
We should add all of the dbt supported platforms (and then move to the community ones). This will require two things:

- [ ]  default profile that maps to an Airflow connection

- [ ]  new extra in setup.cfg

See Duckdb setup in [dbt docs](https://docs.getdbt.com/reference/warehouse-setups/duckdb-setup).

**Comment by dwreeves** [comment]
Reopened in light of: https://apache-airflow.slack.com/archives/C059CC42E9W/p1718538236076319

**Comment by thenaturalist** [comment]
DuckDB is rising ever more in popularity and use and is clearly establishing itself as a favorable compute option for data workloads. 

Is this still not considered? 
@tatiana @pankajkoti @pankajastro
