### ISSUE TITLE
Bug:`ModuleNotFoundError: No module named 'filelock'`

### ISSUE THREAD

**Issue by jbandoro** [astronomer/astronomer-cosmos#212]
We're seeing `ModuleNotFoundError: No module named 'filelock'` errors with the v0.5.1 release using `astronomer-cosmos[dbt-bigquery]` that I think is related to the following PR being merged: https://github.com/astronomer/astronomer-cosmos/pull/195.

I didn't see `filelock` as a dependency in the pyproject file, and it isn't installed with `dbt-bigquery`.

I believe the tests passed because it is installing `astronomer-cosmos[dbt-all]` which has `dbt-snowflake` as a dependency which I believe has a dependency for `filelock`.

Fix would be to have `filelock` as a dependency [here](https://github.com/astronomer/astronomer-cosmos/blob/fd8c60afc78115b70f1852f1a0264759196aff1e/pyproject.toml#LL37C10-L37C10).

**Comment by jlaneve** [comment]
Great catch! Would you be willing to open a PR to add that as a dependency?
