### ISSUE TITLE
DbtSnapshotOperator not present in operators.py in astronomer-cosmos 0.5.2 (PYPI)

### ISSUE THREAD

**Issue by shaunlf08** [astronomer/astronomer-cosmos#232]
The astronomer-cosmos[dbt.all] package does not include the DbtSnapshotOperator in the operators.py file (which is available in github). I have noticed that the merge for this operator only happened on the 10/04/2023, so I understand why the package may not be updated. Is there a rough timeline for when the package gets updated on PYPI?

EDIT: It was available in github 12/04/2023 - but operators.py doesn't seem to exist now?

**Comment by jlaneve** [comment]
Hey @shaunlf08, this should be fixed with version >= 0.6.0! You were right - it just hadn't been released yet.
