### ISSUE TITLE
Add rendered query to Airflow's "Rendered Template" - Feature Request

### ISSUE THREAD

**Issue by eldan-dario** [astronomer/astronomer-cosmos#265]
When running a model (.sql file) via astronomer-cosmos, the Airflow log shows the general dbt logs, but it would be great to also see the rendered/compiled query in the "Rendered Template" (as exists when using Airflow's SnowflakeOperator for example).

This feature will help debug/understand the query that was executed by Airflow.

**Missing query in "Rendered Template":**

![Screenshot 2023-05-09 at 10 50 14](https://user-images.githubusercontent.com/119860732/237031325-044a5290-7df7-4c43-8846-0347011afa52.png)

**Expected to look like this:**

![Screenshot 2023-05-09 at 10 58 26](https://user-images.githubusercontent.com/119860732/237032900-4ff6fb9e-ef7e-40ca-a33e-ecbc6567cdbf.png)

**Comment by jlaneve** [comment]
> Why did it applied only on local operator?

@rightx2 unfortunately there's no easy way to do this with KPO/Docker modes. If you have ideas on how to do it, I'd be very open to PRs or suggestions!
