### ISSUE TITLE
--target=dev in all environments

### ISSUE THREAD

**Issue by eldan-dario** [astronomer/astronomer-cosmos#266]
When running task (within DbtTaskGroup), when checking the logs both in dev and prod, the target doesn't seem to change (it stays target='dev'). 

![Screenshot 2023-05-09 at 11 38 53](https://user-images.githubusercontent.com/119860732/237043136-1c1cdbe6-0062-4a01-a697-fa83e9dbf510.png)

I believe it's to do with astronomer-cosmos generating a snowflake profile (aka "snowflake_profile") based on the Airflow connection, but is there a possibility to set this as a dbt_arg?

**Comment by jlaneve** [comment]
Hey @eldan-dario - you're correct that astronomer-cosmos takes care of translating Airflow connections to profiles for you. This means the profiles should stay the same across environments, but the values in the profile should change depending on the Airflow connection. To ensure this is a bug, can you confirm:
- you're using different Airflow connections for dev and prod (where, for example, the schema is different)
- the dbt models _are_ being run against the same connections (e.g. the schema remains the same)

If you _are_ providing different Airflow connections but the target values remain the same, then this is a bug and I can look into it!

**Comment by dschultz5197** [comment]
I would advocate for target being an option that can actually be used. We're using macros which reference the target name to help determine the database to be written to, or the sources to read from. While we can use different Airflow connections to change the database depending upon the environment, this will only apply to the single database set as the default in the connection, and will not apply to all of the databases referenced in our dbt project.

For reference, we're using target.name in a similar manner to the examples in the following dbt documentation: https://docs.getdbt.com/reference/dbt-jinja-functions/target#examples

**Comment by jlaneve** [comment]
@dschultz5197 I agree here - do you think the solution is as simple as passing a `target_name`? Then Cosmos could ensure the profile name gets translated properly.

**Comment by eldan-dario** [comment]
Hey @jlaneve, following your requests on confirming:
**1. _Using different Airflow connections for dev and prod (where, for example, the schema is different)_**

- Prod connection:

![conn prod test](https://github.com/astronomer/astronomer-cosmos/assets/119860732/f58a7799-6325-46f6-a739-3d7dc68a4cc2)

- Prod connection dbt dag run  (logs `--target='dev'`):

![dag prod dbt](https://github.com/astronomer/astronomer-cosmos/assets/119860732/c75cb800-175c-4809-a895-55a93d2b8625)


- Dev connection:

![conn dev test](https://github.com/astronomer/astronomer-cosmos/assets/119860732/ae1dc388-6f5a-4eb6-8b8d-49b81c92e88b)


- Dev connection dbt dag run  (logs `--target='dev'`):

![dag dev dbt](https://github.com/astronomer/astronomer-cosmos/assets/119860732/dbeb8f11-8e15-4b84-a8f9-9ab624a59590)




**2. _The dbt models are being run against the same connections (e.g. the schema remains the same)._**
 Do you mean running the same connections as in the previous section ("test_snowflake_prod_con" and "test_snowflake_dev_con") but with the same schema? 
 Because if so it has the same issue - both runs show --target=dev

Prod:
![dag prod same schema](https://github.com/astronomer/astronomer-cosmos/assets/119860732/7c1c400e-18bd-4406-bf68-84a2fe5e75a9)

Dev:
![dag dev same schema](https://github.com/astronomer/astronomer-cosmos/assets/119860732/8219979f-3be5-4668-a132-f0dc0d820eb6)

---
I guess the issue here is that the "snowflake_profile" generated from astronomer-cosmos based on the Airflow connection always sets the `target='dev'`. Although we have the flexibility from the Airflow connection and also the option of overriding the "db_name" in the dbt_args, it still can be confusing that in the log we see that `target='dev'`.

---
In addition, I noticed in the code (cosmos/providers/dbt/core/profiles/snowflake.py) that "dev" is hard coded, so this may be the reason that always the `target='dev'` in the airflow logs.

![cosmos_snowflake_profile](https://github.com/astronomer/astronomer-cosmos/assets/119860732/72444440-6912-494d-ab4f-609ed5ef65c7)
