### ISSUE TITLE
Key-based auth for Snowflake

### ISSUE THREAD

**Issue by jschenz-chwy** [astronomer/astronomer-cosmos#267]
Hello all.  I have been looking at `astronomer-cosmos` recently, but am a bit stuck on the auth piece of it.  We are using key-based auth, and I see that it is not supported.  Hoping for a bit of guidance as I start digging into this to see if I can add that option.  It looks like there a few things to consider:

- There is a collection of profiles, from each of the files under `cosmos.providers.dbt.core.profiles`.  
- These profiles are all specified as using password-based auth.
- There is currently no way to update the profile structure based on the Airflow connection. 

My initial concept is to replace the current process of creating the `profiles.yaml` file with one that would interrogate the available connections and generate the corresponding format for the profile.  To do that I would need to do a few things:
1. Get a list of supported connections
2. For each connection, create a connection object and interrogate that to understand what type of auth is being applied.
3. Modify the yaml in `profiles.yaml` for that connection so that it uses the correct auth type.

Curious if others are already working on some solution for key-based auth already.  If so, I am happy to help out.  If not, I would love to get some feedback on my thought process for this.

Thanks!

**Comment by jlaneve** [comment]
Hey @jschenz-chwy, the profiles have been cleaned up and now should be very easy to contribute to. Check out [the docs](https://astronomer.github.io/astronomer-cosmos/dbt/connections-profiles.html#connections-and-profiles) and please let me know if you have any questions! If you don't plan on contributing this, also let us know and we can try to open a PR.

**Comment by HybridNeos** [comment]
Commenting for visibility. This feature would be much appreciated as some organizations only allow private key authentication.

**Comment by ivanstillfront** [comment]
We are also using key-based auth. I see https://github.com/dbt-labs/dbt-snowflake/pull/671 needs a rebase? Anything else that I can help with?

**Comment by jschenz-chwy** [comment]
@ivanstillfront I just merged main into my branch on the dbt-snowflake PR.  Still waiting on a reviewer though.

**Comment by patawan** [comment]
Is there any way to get some traction on the PR open in dbt-snowflake? Seems like it's just been chilling for a while

**Comment by jschenz-chwy** [comment]
Just merged `main` into my branch again.  Not sure how to get attention over there.  No doubt everyone is focused on other things, but it would be nice to get some feedback at least.

**Comment by patawan** [comment]
Thanks for getting that merged @jschenz-chwy! I opened a PR here #378  for the cosmos functionality. I need to add some docs but please let me know what all needs cleaned up.
