### ISSUE TITLE
All models are rendered in the sql compiled (although only one model needs to be rendered due to the select tag in  DbtTaskGroup)

### ISSUE THREAD

**Issue by eldan-dario** [astronomer/astronomer-cosmos#272]
Great work with adding the sql compiled rendered template in this PR (https://github.com/astronomer/astronomer-cosmos/pull/268) !

I found a small issue with it when running this:
``    some_tg = DbtTaskGroup(
        group_id="some_tg",
        dbt_project_name="some_project",
        dbt_root_path="/usr/local/airflow/dbt",
        conn_id=dbt_snowflake_conn_id,
        select={
            "configs": ["tags:some_tag"],
                },
        dbt_args={
            "dbt_executable_path": "/usr/local/airflow/dbt_venv/bin/dbt",
            "db_name": DB_NAME,
            "schema": SCHEMA_NAME,
        },
    )``

All models are rendered in the sql compiled (also models without the tag selected - which is selected properly when rendering the DbtTaskGroup)
Here are the set up details:
requirements.txt -> astronomer-cosmos[dbt-snowflake]==0.6.6 (must be in general directory for cosmos.providers.dbt.task_group to work)
dbt-requirements.txt -> astronomer-cosmos[dbt-snowflake]==0.6.6 (for the dbt_venv)
w

**Comment by jlaneve** [comment]
Hey @eldan-dario, I'm unfortunately unable to replicate this. It sounds like dbt is compiling all your SQL when just running one model, which is odd. Are you able to create a reproducible example? If you can put a simple project where this happens in a public repo, I can dig into it and figure out how to fix it.

**Comment by jlaneve** [comment]
> Hey @jlaneve , you're right. While I started creating a replicate of this issue, I found the reason for the rendering of all models under `compiled_sql` in the rendered templates tab - if user runs `dbt compile` and a target/compiled dir is created, it seems that all models are rendered under `compiled_sql`. Once I removed this directory it solved the issue and rendered the correct compiled .sql.

Ah interesting, so you had already run `dbt compile`? I can definitely add logic to make sure this case gets handled automatically in the future!

**Comment by eldan-dario** [comment]
> > Hey @jlaneve , you're right. While I started creating a replicate of this issue, I found the reason for the rendering of all models under `compiled_sql` in the rendered templates tab - if user runs `dbt compile` and a target/compiled dir is created, it seems that all models are rendered under `compiled_sql`. Once I removed this directory it solved the issue and rendered the correct compiled .sql.
> 
> Ah interesting, so you had already run `dbt compile`? I can definitely add logic to make sure this case gets handled automatically in the future!

Yes, but this was run on local development for testing compilation before deploying project to prod.
But, because this directory is ignored (.gitignore), then I didn't put much notice to it in the general solution. Just trying to reproduce this issue in a mock up project helped me identify the issue of the existence  of this directory and it's affect on the `compiled_sql` feature.

**Comment by S1KC** [comment]
Hi @eldan-dario! I think I just stumbled upon this same issue testing out cosmos with a sample 3-model dbt project. I was performing dbt compile in the Dockerfile, but removed it and still have the same issue. Details/screenshots here:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1685412115967119
