### ISSUE TITLE
Deprecate ``dbt_executable_path`` argument

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#288]
With the implementation of the ``virtualenv`` execution mode (#222 and #279),  we can deprecate the argument ``dbt_executable_path``. It could be fully removed as part of the 1.0.0 release.

**Comment by jlaneve** [comment]
Yeah I think we need to leave this. What about the case where a user installs dbt at a custom location that's _not_ in the user's `PATH`?
