### ISSUE TITLE
Revisit filtering models

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astronomer-cosmos#299]
More context in https://github.com/astronomer/astronomer-cosmos/pull/298. Right now, the interface for filtering your models is quite confusing. We should revisit this and see if there's a better way to do it.

**Comment by tatiana** [comment]
@jlaneve considering the 1.0.0 milestone, do you think we still need to work more on filters?
It feels we already accomplished a great amount with https://github.com/astronomer/astronomer-cosmos/pull/360.

**Comment by jlaneve** [comment]
I think #360 solves this bc we now have the same interface as dbt!
