### ISSUE TITLE
Enable MyPy checks

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#301]
Uncomment:
https://github.com/astronomer/astronomer-cosmos/blob/main/.pre-commit-config.yaml#L61-L66

And fix MyPy issues.

As of now, it found 235 errors in 29 files (checked 58 source files).

**Comment by viktoriussuwandi** [comment]
Hi [tatiana](https://github.com/tatiana),  I will try to help, just wanna ask one thing. Do you mean just by uncomment `MyPy section` on the [link ](https://github.com/astronomer/astronomer-cosmos/blob/main/.pre-commit-config.yaml#L61-L66) will solve the issue ?

![Screenshot 2023-06-03 002211](https://github.com/astronomer/astronomer-cosmos/assets/68414300/1859a584-0711-464e-8d0d-fa25031637e5)

**Comment by jlaneve** [comment]
@viktoriussuwandi once we uncomment that, the check will fail. A PR to fix this should:
- uncomment that pre-commit check (exactly as you described)
- identify and fix each of the issues found by mypy (you should be able to run the checks with `pre-commit run --all-files`)
