### ISSUE TITLE
Review documentation and have a consistent way of writing dbt

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#306]
Different parts of the documentation and docstrings of the Cosmos project reference `dbt` using different approaches: DTB, dbt, **dbt** or ``dbt`` are some examples. The goal of this ticket is to normalise everything to a single representation (keeping it fully lowercase).

**Comment by viktoriussuwandi** [comment]
Hi [tatiana](https://github.com/tatiana), do you want to change all words `(DBT, Dbt)` to just fully lowercase `dbt` on the entire files ? for example on 2 files below. I will try to help.

1. file [https://github.com/astronomer/astronomer-cosmos/blob/main/docs/dbt/docs.rst](https://github.com/astronomer/astronomer-cosmos/blob/main/docs/dbt/docs.rst)
![Screenshot 2023-06-03 011010](https://github.com/astronomer/astronomer-cosmos/assets/68414300/27b016b2-c77a-4666-8c81-96f5c64a1fae)

2. file [https://github.com/astronomer/astronomer-cosmos/blob/main/docs/dbt/index.rst](https://github.com/astronomer/astronomer-cosmos/blob/main/docs/dbt/index.rst)
![Screenshot 2023-06-03 011237](https://github.com/astronomer/astronomer-cosmos/assets/68414300/0d71897c-8112-4b7f-a59d-5fd7842a0863)

**Comment by jlaneve** [comment]
@viktoriussuwandi I think this applies everywhere _except_ the actual code (docs, docstrings, comments, etc). So places where we either define or reference things like `DbtTaskGroup` should be left as-is, but anywhere we reference `dbt` as a standalone word should likely be updated.

**Comment by Spince** [comment]
I have a fix ready locally. Trying to push my branch to open a pr but don't have permissions. Messaged @jlaneve on airflow's slack hoping to figure it out.
