### ISSUE TITLE
readme.md and Quickstart lack required information for getting started

### ISSUE THREAD

**Issue by Spince** [astronomer/astronomer-cosmos#315]
Trying to get started testing this package out but had to google and search slack to finally find [this](https://docs.astronomer.io/learn/airflow-dbt) that tells me where the dbt project should be, how to setup a venv, etc..

Seems like the repo docs could easily incorporate a few additional details to cover everything that's needed when starting from scratch.

**Comment by jlaneve** [comment]
yeah this is a really good point - we're working towards a 1.0 release in the next few months, and have a docs refresh planned as part of it

**Comment by Spince** [comment]
Would be happy to help as a reviewer or contributor to that effort!

**Comment by tatiana** [comment]
@Spince that's a great point, we'd love to have your contribution to our docs - please, when you have a chance, feel free to create PRs on this.
