### ISSUE TITLE
Clone DBT Project

### ISSUE THREAD

**Issue by KarthikRajashekaran** [astronomer/astronomer-cosmos#318]
We don’t have DBT Project inside the Airflow Dag , Both Airflow Repo and DBT Repo are separate 

There should a feature where it can clone the DBT Project into the Airflow Directory and Run the DBT Commands 

Currently in my work with Airflow running EKS , I have written Custom DBTBashOperator which extends BashOperator , where I clone the DBT Project first and then run the DBT Commands

**Comment by dweaver33** [comment]
We have this same issue.  Would be nice to be able to provide the location of the dbt repo on disk as well.  The use case being that we already clone the repo via submodule in the Airflow repo.

**Comment by dweaver33** [comment]
I would say this is still relevant.  As I understand it, you still have to have the dbt project within your Astro repo to use Cosmos.  This is one of the things preventing us from moving to Cosmos.  

@KarthikRajashekaran, your thoughts?

**Comment by KarthikRajashekaran** [comment]
I am currently not using cosmos coz of lack of a feature to clone DBT project in Airflow directory

**Comment by dweaver33** [comment]
As far as I know, this is still an issue.  In order to use Cosmos, it requires that our dbt project lives in the same project as Astro, which is not optimal.
