### ISSUE TITLE
DbtBaseOperator missing Self.Execute()

### ISSUE THREAD

**Issue by JoePollo** [astronomer/astronomer-cosmos#323]
The DbtBaseOperator no longer has the Self.Execute() method as of 0.6.8 (maybe earlier?). This then raises the NotImplemented error based on it's parent class [BaseOperator](https://github.com/apache/airflow/blob/main/airflow/models/baseoperator.py#L1212).

**Comment by jlaneve** [comment]
Hi @JoePollo - what were you using the base operator for? It was never intended to be used directly.

**Comment by JoePollo** [comment]
@jlaneve we were originally using it to pass CLI commands as the task group wasn't allowing for config tag selection. We were hoping to use it in lieu of a task group running a Python model while [182](https://github.com/astronomer/astronomer-cosmos/issues/182) is worked on. What is anticipated to be used to be able to pass a CLI command without bundling other logic?

**Comment by tatiana** [comment]
@JoePollo the python model support was released as part of Cosmos [1.0.0](https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.0.0) (26 July) and more recently we've also released [1.2.0](https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.0), which adds the ability for customising how Cosmos converts dbt nodes into Airflow:
https://astronomer.github.io/astronomer-cosmos/configuration/render-config.html#customizing-how-nodes-are-rendered-experimental

Therefore, I'm closing this issue. Please feel free to create new tickets if you have any other issues or feature requests.
