### ISSUE TITLE
Make store_compiled_sql Optional 

### ISSUE THREAD

**Issue by npezman** [astronomer/astronomer-cosmos#328]
Using: astronomer-cosmos==0.7.1
Problem: Sometimes, if the number of models is big and we have too many lines of code on each one, we experience Airflow UI crashes after the task fails in these. 
I wanted to propose to make the rendering optional, keeping the templated field anyway.

**Comment by jlaneve** [comment]
Yes, I like this idea! Maybe we should make it globally disabled with an Airflow config or environment variable? What do you think?
