### ISSUE TITLE
Add support for dbt-sqlserver

### ISSUE THREAD

**Issue by P1et1e** [astronomer/astronomer-cosmos#335]
We should add all of the dbt supported platforms (and then move to the community ones). This will require two things:

 - default profile that maps to an Airflow connection 
 - new extra in setup.cfg

See MSSQL Server setup in [dbt docs](https://docs.getdbt.com/docs/core/connect-data-platform/mssql-setup).

**Comment by tatiana** [comment]
There has been interest from the community on this ticket, via the #dbt-airflow channel:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1697727028206819

**Comment by simonprydden** [comment]
Hello, I was just looking into how we run dbt on mwaa, and add SQL server support would be required for us.
