### ISSUE TITLE
Using normal dbt profiles instead of airflow connections

### ISSUE THREAD

**Issue by P1et1e** [astronomer/astronomer-cosmos#336]
Add a way to add normal dbt profiles to support a broader variety of different source and target systems.

Is there a workaround to use dbt-sqlserver with the current version of astronomer-cosmos ?

**Comment by jlaneve** [comment]
Hey @P1et1e, thanks for opening this issue! We have another issue to track this: https://github.com/astronomer/astronomer-cosmos/issues/269

Out of curiosity, how are you running Airflow and how would you get the dbt profile into Airflow? Do you have a profile.yml file that you'd load into the same filesystem as Airflow, or would you want to supply the values via `profile_args` from your Airflow DAG code?

**Comment by magdagultekin** [comment]
Hi @jlaneve, I also would love to be able to use the `profiles.yml` file :) I could go both ways - use the `profile_args` in the DAG code or use the yml file that I store in my `dbt` directory.
