### ISSUE TITLE
on_failure_callback to alert during test failure

### ISSUE THREAD

**Issue by ajithshetty** [astronomer/astronomer-cosmos#341]
There is a feature to send call back during WARN.
https://astronomer.github.io/astronomer-cosmos/dbt/configuration.html#warn-notification
Which sends the list of tests which are in WARN state.

In case, if the test fails, the task itself will fail.

With on_failure_callback, Requirement is to see the tests which are failed.

**Comment by jlaneve** [comment]
I wonder if we could modify the subprocess hook to throw a Python exception we define (with all the metadata we need) - and then a user could use it as described in: https://stackoverflow.com/questions/51822029/get-exception-details-on-airflow-on-failure-callback-context

**Comment by CorsettiS** [comment]
@jlaneve it is possible for sure, however I do not know how easy to implement it would be. Ideally we would pass it to the task level, but then a DbtDag method would overwrite it with airflow default, breaking the consistency. maybe changing the name from **on_failure_callback** to **on_test_failure_callback** and working on it as a virgin project ? and obviously do the same for warn (**on_warn_callback** to **on_test_warn_callback**) for consistency. That way we keep the airflow default method clean and it is easier to work from there.

**Comment by ajithshetty** [comment]
I'm not fully sure if it goes against the core principles, but do you think having "soft fail" makes sense for DBT tests which fails but the task still succeeds.

**Comment by CorsettiS** [comment]
@ajithshetty sorry, I did not totally understand the point you made.  astronomer-cosmos consider the tests as a task itself, therefore if it fails, it makes sense the task should fail. A soft fail would be the same as a warning from my perspective, no?
