### ISSUE TITLE
GCP BigQuery service account json not supported in v0.7

### ISSUE THREAD

**Issue by jbandoro** [astronomer/astronomer-cosmos#350]
We ran into this problem upgrading from v0.6.X -> v0.7.X using the default `google_cloud_platform` [airflow connection ](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#configuring-the-connection) that uses a keyfile json and not the keyfile path that is currently [supported](https://github.com/astronomer/astronomer-cosmos/blob/1ebee498b8ccc3a295b6c737a81d336ddcca6626/cosmos/profiles/bigquery/service_account_file.py#L9) in astronomer cosmos.

All of the profile var mapping of the json service account can be found in an older tag before the refactor of profiles in 0.7 here: https://github.com/astronomer/astronomer-cosmos/blob/astronomer-cosmos-v0.6.8/cosmos/providers/dbt/core/profiles/bigquery.py as a place to start from.

When I have time I'd be happy to take a stab at this, but opening up this issue in case others also run into this during an upgrade.

**Comment by JoeSham** [comment]
Hi, I was just going to open a similar issue :) We were not using the older version, but I guess we have the same problem: we store our Service Account JSON file as a secret in Google Secret Manager, so when we retrieve it, it is not a path to a file, but the actual file/JSON. I started testing with Cosmos 0.7.3 and so far did not manage getting it to somehow digest the SA keyfile as a json...

**Comment by JoeSham** [comment]
@tatiana Hi, I see you did the refactor probably, could you plz check this? Is there really no way to read SA keyfile_dict currently, or is there some other way? Thank you

**Comment by tatiana** [comment]
@JoeSham @jbandoro I believe this may have been an issue introduced by the PR where we refactored profiles: https://github.com/astronomer/astronomer-cosmos/pull/271

To confirm if I understood the issue, Cosmos works as expected if you create a [Google Cloud Platform](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html) connection specifying the `key_path` property but not if you specify `keyfile_dict` - is that the case?

**Comment by JoeSham** [comment]
@tatiana Hi, yes, correct. The [GoogleCloudServiceAccountFileProfileMapping](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/bigquery/service_account_file.py) seems to only accept key_path as a path to SA keyfile, but there is no keyfile_dict or similar option. I also tested passing the SA keyfile_dict into the key_path param, in which case it passed in the ProfileMapping but then failed later on the fact that the keyfile (as given) does not exists

**Comment by tatiana** [comment]
@JoeSham, the fix should be straightforward. The issue is that this:
https://github.com/astronomer/astronomer-cosmos/blob/astronomer-cosmos-v0.6.8/cosmos/providers/dbt/core/profiles/bigquery.py 

Was oversimplified as part of https://github.com/astronomer/astronomer-cosmos/pull/271:
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/bigquery/service_account_file.py

We can add test cases to make sure we don't miss this feature in the future: https://github.com/astronomer/astronomer-cosmos/blob/main/tests/profiles/bigquery/test_bq_service_account_file.py

Would either of you have the capacity to work on the fix? Otherwise, we can take it

**Comment by jlaneve** [comment]
@JoeSham looked at the commits that are linked here, I think we should create a new profile mapping for the keyfile_dict/json. What do you think about that?

**Comment by JoeSham** [comment]
@jlaneve yea you are right, it was just a quick first draft. I now made another quick 2nd draft, the way you recommended. Without tests so far. Not sure if I will have more time for it in the upcoming days though...

**Comment by jlaneve** [comment]
> @jlaneve yea you are right, it was just a quick first draft. I now made another [quick 2nd draft](https://github.com/astronomer/astronomer-cosmos/compare/main...JoeSham:joe/bq_keyfile_dict?diff=unified), the way you recommended. Without tests so far. Not sure if I will have more time for it in the upcoming days though...

That's fine! If you want to open a draft PR with what you have, I'm more than happy to jump in and add tests 🙂

**Comment by JoeSham** [comment]
Ok great @jlaneve :) [PR](https://github.com/astronomer/astronomer-cosmos/pull/352) opened

**Comment by tatiana** [comment]
That's a great start, @JoeSham ! Thank you very much. Please, do let us know once you'd like reviews - or if you need any support, e.g for writing the tests

**Comment by JoeSham** [comment]
Hey @tatiana @jlaneve, so could you please maybe take a look + possibly add tests etc.? (note: I am leaving for holidays next week so won't be able to work on this after today for a while)

**Comment by tatiana** [comment]
Hi @JoeSham , that's totally fine, thank you very much for start working on this.
Would you like to add us as contributors of your fork/branch, so we can follow up on the same PR, or do you prefer that we open a new PR from a different repo?
Enjoy your holidays!

**Comment by JoeSham** [comment]
Thx @tatiana! Add you and @jlaneve as contributors

**Comment by JoeSham** [comment]
Hey @tatiana @jlaneve 👋 May I ask what is the current status, please?

**Comment by tatiana** [comment]
@JoeSham, I apologize for the delay; I worked on other tasks in the past few days.
Unfortunately, the invitation to contribute to your repo has expired.

I wrote the tests:
https://github.com/astronomer/astronomer-cosmos/tree/joe/bq_keyfile_dict

Please, feel free to `cherry-pick` https://github.com/astronomer/astronomer-cosmos/commit/615a256bbb3e702c373022f670d41ec914d512d7

**Comment by JoeSham** [comment]
Hey @tatiana thx, I invited you and @jlaneve  as contributors again
