### ISSUE TITLE
dbt test_behavior="after_all" fails since it couldnt find profile_args

### ISSUE THREAD

**Issue by ajithshetty** [astronomer/astronomer-cosmos#356]
When I run the dbt with test_behavior="after_all":

```
import os
from datetime import datetime
from pathlib import Path

from cosmos.dag import DbtDag

DEFAULT_DBT_ROOT_PATH = Path(__file__).parent / "dbt"
DBT_ROOT_PATH = Path(os.getenv("DBT_ROOT_PATH", DEFAULT_DBT_ROOT_PATH))
PROJECT_NAME = "jaffle_shop"
CONNECTION_ID = "airflow_db"

example_virtualenv = DbtDag(
    # dbt/cosmos-specific parameters
    dbt_root_path=DBT_ROOT_PATH,
    dbt_project_name=PROJECT_NAME,
    conn_id=CONNECTION_ID,
    dbt_args={"schema": "public"},
    execution_mode="virtualenv",
    operator_args={
        "project_dir": DBT_ROOT_PATH / PROJECT_NAME,
        "py_system_site_packages": False,
        "py_requirements": ["dbt-postgres==1.6.0b1"],
        "schema": "public",
    },
    schedule_interval="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id="example_virtualenv_test_after_all",
    test_behavior="after_all",
)
```
It gives an error:

```
[2023-07-01, 16:51:40 UTC] {local.py:183} INFO - Cloning project to writable temp directory /tmp/tmpyd3ceg6d from /usr/local/airflow/dags/dbt/jaffle_shop
[2023-07-01, 16:51:40 UTC] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-07-01, 16:51:40 UTC] {base.py:73} INFO - Using connection ID 'airflow_db' for task execution.
[2023-07-01, 16:51:40 UTC] {base.py:55} INFO - Not using mapping PostgresUserPasswordProfileMapping because schema is not set
[2023-07-01, 16:51:40 UTC] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/virtualenv.py", line 100, in execute
    output = super().execute(context)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 391, in execute
    result = self.build_and_run_cmd(context=context)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 246, in build_and_run_cmd
    return self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/usr/local/airflow/astronomer_cosmos/cosmos/operators/local.py", line 204, in run_command
    profile_mapping = get_profile_mapping(
  File "/usr/local/airflow/astronomer_cosmos/cosmos/profiles/__init__.py", line 61, in get_profile_mapping
    raise ValueError(f"Could not find a profile mapping for connection {conn_id}.")
ValueError: Could not find a profile mapping for connection airflow_db.
```
When I run the dbt with test_behavior="after_each":
```
example_virtualenv = DbtDag(
    # dbt/cosmos-specific parameters
    dbt_root_path=DBT_ROOT_PATH,
    dbt_project_name=PROJECT_NAME,
    conn_id=CONNECTION_ID,
    dbt_args={"schema": "public"},
    execution_mode="virtualenv",
    operator_args={
        "project_dir": DBT_ROOT_PATH / PROJECT_NAME,
        "py_system_site_packages": False,
        "py_requirements": ["dbt-postgres==1.6.0b1"],
    },
    schedule_interval="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id="example_virtualenv_test_after_each",
    test_behavior="after_each",
)
```

I get the success logs:
```
[2023-07-01, 16:44:57 UTC] {local.py:183} INFO - Cloning project to writable temp directory /tmp/tmp2nt61p9v from /usr/local/airflow/dags/dbt/jaffle_shop
[2023-07-01, 16:44:57 UTC] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-07-01, 16:44:57 UTC] {base.py:73} INFO - Using connection ID 'airflow_db' for task execution.
[2023-07-01, 16:44:57 UTC] {local.py:228} INFO - Trying to run the command:
 ['/usr/local/bin/dbt', 'test', '--models', 'customers']
From /tmp/tmp2nt61p9v/dbt_project
[2023-07-01, 16:44:57 UTC] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/cosmos-venvvjfh2hxx --python=python3

```

**Are you willing to submit PR?**
- [x] Yes I am willing to submit a PR!

**Code of Conduct**
- [x] I agree to follow this project's [Code of Conduct](https://github.com/astronomer/astronomer-cosmos/blob/main/CODE_OF_CONDUCT.md)

**Comment by ajithshetty** [comment]
Reason:

The argument passed to render test_task when the test_behaviour="after_all"
arguments={**task_args, **operator_args}
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/render.py#L250
Which results in:
`operator_class='cosmos.operators.virtualenv.DbtTestVirtualenvOperator', arguments={'schema': 'public', 'conn_id': 'airflow_db', 'project_dir': PosixPath('/usr/local/airflow/dags/dbt/jaffle_shop'), 'py_system_site_packages': False, 'py_requirements': ['dbt-postgres==1.6.0b1']})])'
`

The argument passed to render test_task when the test_behaviour="after_each"
arguments=test_args

https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/render.py#L217

`operator_class='cosmos.operators.virtualenv.DbtTestVirtualenvOperator', arguments={'schema': 'public', 'conn_id': 'airflow_db', 'project_dir': PosixPath('/usr/local/airflow/dags/dbt/jaffle_shop'), 'py_system_site_packages': False, 'py_requirements': ['dbt-postgres==1.6.0b1'], 'models': 'stg_payments', 'profile_args': {'schema': 'public'}, 'profile_name': None, 'target_name': None, 'on_warning_callback': None, 'outlets': [Dataset(uri='DBT://AIRFLOW_DB/JAFFLE_SHOP/STG_PAYMENTS', extra=None)]})]), Task(id='raw_customers_seed', upstream_entity_ids=[]`

The profile validation will fail 
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/base.py#L34
Where it is searching for profile_args: dict[str, Any]


Resolution:
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/render.py#L250
Update to: arguments={**test_args, **operator_args}


If this makes sense I am willing to make the contribution.

**Comment by CorsettiS** [comment]
```
 import os
from datetime import datetime
from pathlib import Path

from cosmos.dag import DbtDag

DEFAULT_DBT_ROOT_PATH = Path(__file__).parent / "dbt"
DBT_ROOT_PATH = Path(os.getenv("DBT_ROOT_PATH", DEFAULT_DBT_ROOT_PATH))
PROJECT_NAME = "jaffle_shop"
CONNECTION_ID = "airflow_db"

example_virtualenv = DbtDag(
    # dbt/cosmos-specific parameters
    dbt_root_path=DBT_ROOT_PATH,
    dbt_project_name=PROJECT_NAME,
    conn_id=CONNECTION_ID,
    **dbt_args**={"schema": "public"},
    execution_mode="virtualenv",
    operator_args={
        "project_dir": DBT_ROOT_PATH / PROJECT_NAME,
        "py_system_site_packages": False,
        "py_requirements": ["dbt-postgres==1.6.0b1"],
        "schema": "public",
    },
    schedule_interval="@daily",
    start_date=datetime(2023, 1, 1),
    catchup=False,
    dag_id="example_virtualenv_test_after_all",
    test_behavior="after_all",
)
```

instead of **dbt_args**, did you try using **profile_args** ? If yes, does the error remain?

**Comment by ajithshetty** [comment]
Thank you for your response @CorsettiS 
Yes I tried using **profile_args={"schema": "public"}** and its gives the same error.

**Comment by ajithshetty** [comment]
@CorsettiS did you get a time to look into this?
If its a real issue and not a configuration mismatch, the solution what I provided above wouldnt work. As it would only pick the last test in the loop and execute.

**Comment by CorsettiS** [comment]
@ajithshetty I am just a contributor of the project, and not a member of the main team. I lack the capacity to help you on this issue. I can tell you tho that now that cosmos has reached v1.0.0, most likely this error will be gone or at least you will obtain a different error in the worst case scenario. The project underwent a huge architecture change

**Comment by ajithshetty** [comment]
Thank you @CorsettiS for your response.
I have checked in the latest cosmos version and this issue has been resolved.

**Comment by ajithshetty** [comment]
When the test_behaviour=after_all, the task will combine all the tests into a consolidated single task with multiple test cases.

Its good to be closed.
