### ISSUE TITLE
Rendered SQL does not show temp table logic

### ISSUE THREAD

**Issue by saikotcharlakota** [astronomer/astronomer-cosmos#364]
For incremental models, the Airflow rendered template only contains delete and insert statements using temporary table. It does not include the SQL for generating the temporary table.

However, for table materialization, I can see full SQL.

![Screenshot 2023-07-11 at 11 22 47 AM](https://github.com/astronomer/astronomer-cosmos/assets/96261216/25baa277-d896-4714-9910-9a4979435ebc)

**Comment by jlaneve** [comment]
I think this is related to [this comment](https://github.com/astronomer/astronomer-cosmos/pull/268#issuecomment-1617530267), which is a bug in the library.
