### ISSUE TITLE
Cosmos does not parse BigQuery connections correctly

### ISSUE THREAD

**Issue by MonideepDe** [astronomer/astronomer-cosmos#365]
Hi there!

I might be mistaken, but it looks like there is an issue with cosmos version `0.7.4` around parsing of BiqQuery connection information.

Looking at the code [here](https://github.com/astronomer/astronomer-cosmos/blob/c919e2043b07d7e06e8a8663ffcbf84f18a34b2e/cosmos/profiles/bigquery/service_account_file.py#L25), the mapping of parameters from airflow connection to seems to expect `dataset` as a top level parameter in connection json.

```
airflow_param_mapping = {
        "project": "extra.project",
        "dataset": "dataset",
        "keyfile": "extra.key_path",
    }
```

However, based on the documentation of `apache-airflow-providers-google` [here](https://airflow.apache.org/docs/apache-airflow-providers-google/stable/connections/gcp.html#configuring-the-connection), `dataset` can not appear  as a top level parameter in connection json.

To verify this further, if I try to set dataset as a top level parameter in connection json, I get error as shown below:

```bash
$ airflow connections add 'my_cosmos_connection' --conn-json '{
	"conn_type": "google-cloud-platform",
	"dataset": "my_dataset",
	"extra": {
		"project": "my_gcp_project", 
		"num_retries": "5",
		"key_path": "/path/to/key.json"
	}
}'
...
...
...
TypeError: __init__() got an unexpected keyword argument 'dataset'
```

Hence, if I am not missing something, I think the mapping of dataset parameter should be with `extra.dataset` and this should be modified at the line which I linked above. I could make this work, after making the suggested change locally.

If this sounds good, I can try and submit a PR.

**Comment by jlaneve** [comment]
@MonideepDe yes - good catch, that's right! Do you want to open a PR?

**Comment by MonideepDe** [comment]
Thanks @jlaneve. I would submit a PR soon!
