### ISSUE TITLE
Rendered SQL is not available for failed runs.

### ISSUE THREAD

**Issue by saikotcharlakota** [astronomer/astronomer-cosmos#369]
Airflow Rendered template is empty if the task if failed. I wish to see the rendered query/test that was executed resulting in the failure.

IMO, this is because `store_compiled_sql` is called after the error/exception check [local.py](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/operators/local.py#L237) file. 

`exception_handling` methods simply raises AirflowException in case of error resulting rendered template as empty.

**Comment by saikotcharlakota** [comment]
Hello,
I tested this issue and it still exists. 

DBT: 1.5.1
Cosmos: 1.2.0
Airflow: 2.5.1

**Comment by agreenburg** [comment]
@tatiana I think this would be a very helpful thing to address and I would be happy to provide a submission.

**Comment by tatiana** [comment]
Just read this issue, thanks for looping me in @agreenburg , and thanks for reporting it @saikotcharlakota !

It is a relevant improvement to Cosmos, and we'd appreciate if you'd like to contribute to fix this, @agreenburg !
