### ISSUE TITLE
Import path to DbtTaskGroup in quickstart no longer accurate

### ISSUE THREAD

**Issue by Andrew-Wichmann** [astronomer/astronomer-cosmos#376]
It appears the `DbtTaskGroup` class was moved to the `cosmos.airflow` module but the quickstart still says `from cosmos.providers.dbt.task_group import DbtTaskGroup`.

**Comment by samsoneul** [comment]
this is no longer working 
from cosmos.airflow.dbt.core.operators import (
    DbtDepsOperator,
    DbtRunOperationOperator,
    
)

**Comment by samsoneul** [comment]
from cosmos.providers.dbt.core.operators import (
    DbtDepsOperator,
    DbtRunOperationOperator,
    
)
this is no longer working
