### ISSUE TITLE
Ensure datasets are emitted from the right task

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astronomer-cosmos#393]
If models are run with no tests, we should emit the dataset from the model.

If models are run with tests, we should emit the dataset from the test. This way, if a model breaches the tests, we don't run things downstream.
This should be an optional configuration.

**Comment by tatiana** [comment]
@javihernovoa are you using [openlineage-dbt](https://pypi.org/project/openlineage-dbt/)? I think it may be worth reopening the ticket you created. I have a feeling it may be also related to https://github.com/astronomer/astronomer-cosmos/issues/305

**Comment by javihernovoa** [comment]
@tatiana , not using `openlineage-dbt`. #305 does seem related!

Do you want me to reopen #473 and link it to #305?
