### ISSUE TITLE
Question: Best way to run models in different schedule

### ISSUE THREAD

**Issue by xinbinhuang** [astronomer/astronomer-cosmos#396]
Hi team,

Thanks for the amazing work! I'm interested in trying it out. My current set up is having one 1 DBT project with models that run in different schedule. Does `cosmos` and the `DbtTaskGroup` support running models in different schedules within the same DBT project? If not, what would be your recommendation in achieving that?

**Comment by jlaneve** [comment]
Hi @xinbinhuang, yes! What you could do is split your dbt project into multiple Airflow DAGs based on a tag. Like so:

```python
from cosmos import DbtDag, ProjectConfig, RenderConfig

project_config = ProjectConfig("path/to/project")

daily = DbtDag(
    project_config=project_config,
    render_config=RenderConfig(
        select=["tag:daily"],
    ),
    schedule_interval="@daily",
)

hourly = DbtDag(
    project_config=project_config,
    render_config=RenderConfig(
        select=["tag:hourly"],
    ),
    schedule_interval="@hourly",
)
```

Let me know if you have any further questions and I can re-open this issue, but I'm going to close it for now!
