### ISSUE TITLE
How the DbtKubernetesBaseOperator is sharing the conn_id info to the K8S pod ?

### ISSUE THREAD

**Issue by raphaelauv** [astronomer/astronomer-cosmos#400]
I do not see how the DbtKubernetesBaseOperator share the conn_id ( airflow connection) informations to the K8S pod that is running dbt 

could you please explain it to me , thank you

**Comment by jlaneve** [comment]
Hi @raphaelauv, for Docker and Kubernetes we don’t do any profile mapping. The assumption is that you have your credentials on the image already. 

I’ll make sure to update the docs to call this out explicitly!
