### ISSUE TITLE
example_cosmos_python_models.py in dev sandbox is crashing

### ISSUE THREAD

**Issue by CorsettiS** [astronomer/astronomer-cosmos#405]
the dag that calls a python model is failing during the tests with the following error

```
Broken DAG: [/usr/local/airflow/dags/example_cosmos_python_models.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `databricks_default` isn't defined
```

This makes sense considering that dbt needs an adapter for running python models, which obviously would not be provided in the dev sandbox. Maybe it would be better to split the integration tasks into two kinds ? 
1. All dags except the one in example_cosmos_python_models.py 
2. the DAG in example_cosmos_python_models.py

**Comment by tatiana** [comment]
Hey @CorsettiS , which command led to this error?

As part of the commit 10585442c72b5699fc8bca8a1c50a346d2b567e3, which introduced `example_cosmos_python_models.py`, we split running integration tests:
https://github.com/astronomer/astronomer-cosmos/blob/main/pyproject.toml#L160-L174

By running the previously existing command, the new DAG, which is dependent upon Databricks, is not run:
```
hatch run tests.py3.10-2.6:test-integration
```

To run only the Databricks DAG, developers should run:
```
hatch run tests.py3.10-2.6:test-integration-expensive
```

**Comment by CorsettiS** [comment]
> Hey @CorsettiS , which command led to this error?
> 
> As part of the commit [1058544](https://github.com/astronomer/astronomer-cosmos/commit/10585442c72b5699fc8bca8a1c50a346d2b567e3), which introduced `example_cosmos_python_models.py`, we split running integration tests: https://github.com/astronomer/astronomer-cosmos/blob/main/pyproject.toml#L160-L174
> 
> By running the previously existing command, the new DAG, which is dependent upon Databricks, is not run:
> 
> ```
> hatch run tests.py3.10-2.6:test-integration
> ```
> 
> To run only the Databricks DAG, developers should run:
> 
> ```
> hatch run tests.py3.10-2.6:test-integration-expensive
> ```

no command, it is a error that appears in the airflow UI once the dev sandbox is up. It is just strange to have a DAG error in the dev env, but seems that it is more cosmetic than functional, therefore I am closing this issue
