### ISSUE TITLE
error when using `cache_selected_only` set to True

### ISSUE THREAD

**Issue by bawehkacrut** [astronomer/astronomer-cosmos#413]
When i set argument `cache_selected_only` to True, there is an error when running the actual dbt command. dbt command will be like this `dbt run --select<model name> --cache-selected-only`. based on documentation on dbt https://docs.getdbt.com/reference/global-configs/cache, the command should be `dbt --cache-selected-only run --select <model name>`

**Comment by tatiana** [comment]
This issue was also raised by @jensenity in the slack channel: https://apache-airflow.slack.com/archives/C059CC42E9W/p1686028084902759

**Comment by tatiana** [comment]
@bawehkacrut this is solved as part of the 1.1 release:
https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.1.0

Thanks for sharing this bug!
