### ISSUE TITLE
Add authentication method for Snowflake (Key Pair Authentication)

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#42]
See dbt official docs [here](https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup#key-pair-authentication) on how to do this. We'll need to add it to the default profiles and map it to the snowflake connection in Airflow

**Comment by pohek321** [comment]
Marking as blocked because we should really do [this](https://github.com/astronomer/astronomer-cosmos/issues/41) before adding any more auth methods
