### ISSUE TITLE
Support OAuth authentication for Big Query

### ISSUE THREAD

**Issue by MonideepDe** [astronomer/astronomer-cosmos#420]
Hi there!

Currently, cosmos only supports two authentication mechanisms:

1. service account key file and 
2. service account key json

DBT supports `oauth via gcloud` authentication. See documentation [here](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#oauth-via-gcloud).

As part of this issue, I request the support for `oauth via gcloud` authentication method.

I will open a PR for the same and if everything looks good, we can hopefully merge it into `main` and make it a part of the next release.

Thanks!

**Comment by harels** [comment]
Thanks @MonideepDe! looking forward to your PR!
