### ISSUE TITLE
Add authentication method for Redshift (IAM Authentication)

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#44]
See dbt official docs on how to do this [here](https://docs.getdbt.com/reference/warehouse-setups/redshift-setup) as well as the Airflow OSS docs [here](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/redshift.html). We'll have to create a default profile for this auth method and map the fields from the Airflow connection into it.

**Comment by pohek321** [comment]
Marking as blocked because we should really do [this](https://github.com/astronomer/astronomer-cosmos/issues/41) before adding any more auth methods
