### ISSUE TITLE
dbt/selectors doesn't work for config tags

### ISSUE THREAD

**Issue by javihernovoa** [astronomer/astronomer-cosmos#440]
The filtering done on select for config.tags checks if a config from the select is a subset of the node's config but this will always fail as it will try to check if a key: string is a subset of a key: list.

So for example, using `select="config.tags:has_child"` on a node with its config tags equal to `['has_child']`, the process would look something like this:
```
config = { 'tags': 'has_child' }
supported_node_config = { 'tags': ['has_child'] }
config.items() <= supported_node_config.items()
```
Which would always result to `False`.

I considered modifying the `load_from_statement` function to parse the config tags into a list but that would only work if the tags match exactly and would fail in a different scenario like:
```
config = { 'tags': ['has_child'] }
supported_node_config = { 'tags': ['has_child', 'nightly'] }
config.items() <= supported_node_config.items()
```
Which would return `False`.

My suggestion is to check for the config tags and then do the current check for all other configs. I'll add a PR in a bit.

**Comment by ntc-Felix** [comment]
If you are using DbtTaskGroup

Instead of :
config = { 'tags': 'has_child' }

use:
operator_args = {
    "select":["tags:has_child"]
}
