### ISSUE TITLE
docker compose fails for folder dev/logs and dev/plugins

### ISSUE THREAD

**Issue by ajithshetty** [astronomer/astronomer-cosmos#442]
As per https://astronomer.github.io/astronomer-cosmos/contributing.html#local-sandbox
I am trying to get the local sandox running using docker.

It fails for 
```

 ⠋ Container dev_airflow-init_1  Recreate                                                                                                                                                           0.1s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /projects/cosmos/astronomer-cosmos/dev/logs
 ⠙ Container e13d5b4cdf60_dev_airflow-init_1  Recreate                                                                                                                                              0.1s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /projects/cosmos/astronomer-cosmos/dev/plugins
```

After explicitly creating these 2 folders, I could get the container running.

**Comment by CorsettiS** [comment]
@ajithshetty I tried to replicate the error on my local setup but things worked fine by following the steps
1) git clone https://github.com/astronomer/astronomer-cosmos.git
2) cd astronomer-cosmos
3) docker compose -f dev/docker-compose.yaml up -d --build
if the error persists after following the instructions, you can create a PR introducing two empty dirs to the project
