### ISSUE TITLE
dbt >= 1.6 breaks cosmos

### ISSUE THREAD

**Issue by harels** [astronomer/astronomer-cosmos#444]
Kubernetes Airflow provider and dbt Core released new versions and these are breaking our build. We should look into this and address it.

**Comment by tatiana** [comment]
@harels does this issue relate to this PR: https://github.com/astronomer/astronomer-cosmos/pull/426 ?

**Comment by tatiana** [comment]
This was released as part of 1.2:
* https://pypi.org/project/astronomer-cosmos/1.2.0/
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.0
