### ISSUE TITLE
Add support for GKEStartPodOperator

### ISSUE THREAD

**Issue by davidvanrooij** [astronomer/astronomer-cosmos#455]
It would be great to add support for creating pods through GKEStartPodOperator to provide better integration with [Google Kubernetes Engine (GKE)](https://cloud.google.com/kubernetes-engine/).

GKEStartPodOperator extends KubernetesPodOperator to provide authorization using Google Cloud credentials. There is no need to manage the kube_config file, as it will be generated automatically. All Kubernetes parameters (except config_file) are also valid for the GKEStartPodOperator. 

The chief benefit of using GKEStartPodOperator is to easily create pods in a different cluster than the airflow instance which is less trivial with KubernetesPodOperator. 

Happy to have a stab at creating a PR.

**Comment by jlaneve** [comment]
I think the right approach may be to do this with https://github.com/astronomer/astronomer-cosmos/issues/427. There's probably a few other operators we'd want to support, so generalizing this makes more sense IMO. Curious to get your thoughts though!

**Comment by davidvanrooij** [comment]
I like the approach of adding the ability to have a custom subclass since that is more generalizable. I had briefly attempted this by monkey-patching the package to drop in a different subclass but that very quickly became unmaintainable. 

I'll keep an eye out on https://github.com/astronomer/astronomer-cosmos/issues/427 in the meantime. Let me know if I can assist in any way.

**Comment by jlaneve** [comment]
Agree, monkey patching isn't sustainable in the long-term and I'd rather just support this directly in Cosmos 🙂

Opening this issue is super helpful! And if you have any other thoughts/ideas on #427 definitely feel free to drop a comment on that issue

**Comment by tatiana** [comment]
@davidvanrooij #427 is available as part of Cosmos 1.2 - if you have a chance, please give it a try and let us know how it goes.

An alternative approach to run Cosmos in GCP is to wait for the PR #611 to be released and use `ExecutionMode.VIRTUALENV` (https://astronomer.github.io/astronomer-cosmos/getting_started/execution-modes.html#virtualenv).

**Comment by davidvanrooij** [comment]
@tatiana Awesome, thanks for the update. I'll give that approach a try and get back to you.

**Comment by tatiana** [comment]
@davidvanrooij, over the last few months, we have received contributions to add support for several execution modes.

These are examples of the AWS EKS and AWS ECS execution modes, both contributed by the community:
https://github.com/astronomer/astronomer-cosmos/pull/944
https://github.com/astronomer/astronomer-cosmos/pull/1507

We'd be happy to accept a contribution to have a GKE execution mode. Would you be interested in contributing?

**Comment by tatiana** [comment]
This ticket has been open for almost three years. Unfortunately, no one prioritised and implemented it. We'll be closing it, for now, and if someone has interest and is willing to contribute this feature - we'd gladly accept the contribution.

**Comment by burbanom** [comment]
Hello, I would be interested in contributing this extension. I have already a version of the operator that I have tested and is working.
