### ISSUE TITLE
Add tests after snapshots

### ISSUE THREAD

**Issue by dhazan-raptive** [astronomer/astronomer-cosmos#474]
Currently using v1.0.x and noticed that while my models create task groups that contain the running and testing of the model, my snapshots are just a task that run the snapshot (no tests).

I'd like to see a feature added where snapshots are treated similar to models in the Airflow dag and get a task group with a run and test command.

**Comment by tatiana** [comment]
Thanks for adding this, @dhazan-raptive ! This is a good first issue if anyone from the community wants to pick up, otherwise we may be able to squeeze in our next sprint at Astronomer!
