### ISSUE TITLE
Don't crash parsing when there's an unrecognized node type

### ISSUE THREAD

**Issue by jlaneve** [astronomer/astronomer-cosmos#477]
Right now, when you add a node type that's not explicitly supported by Cosmos, the parsing fails. While we can work to maintain the list of supported nodes, this list keeps growing and comes from many different sources. For example, the `Snowflake-Labs/dbt_constraints` package adds a new node type, `operation`. We can't keep track of all of these things in source code, so we shouldn't fail when there's an unexpected node type.

This is also related to the [generator functions issue](https://github.com/astronomer/astronomer-cosmos/issues/427) - if a user wants to do something with node types that aren't explicitly supported, they'd be able to use the generating functions.

**Comment by tatiana** [comment]
This PR should address the problem: https://github.com/astronomer/astronomer-cosmos/pull/503 (will try to remove it from draft this week)
