### ISSUE TITLE
Dynamic dbt configuration with airflow jinja template fields for SparkThriftProfileMapping host value

### ISSUE THREAD

**Issue by shishircc** [astronomer/astronomer-cosmos#478]
In my DAG, I am setting up an emrjobflow and retrieving the dns of cluster before calling the dbttaskgroup. 

To the DbtTaskGroup, I want to pass this dynamic runtime value as host and for the Thrift configuration 

However that is not possible because the profile class does not accept XCom jinja templating.

Is it possible to pass a dynamic configuration to dbt task group using XCom jinja templating ? Or are there any workarounds ?

**Comment by w0ut0** [comment]
We also would like to dynamically configure output from previous tasks (or, for example, Airflow run id) to the dbt cli as dbt_vars. This does not seems possible when initialising DbtTaskGroup.
