### ISSUE TITLE
Wrong profile mapping for SnowflakePrivateKeyPemProfileMapping

### ISSUE THREAD

**Issue by nacpacheco** [astronomer/astronomer-cosmos#479]
SnowflakePrivateKeyPemProfileMapping is adding `private_key_content` to the DBT profile when in fact dbt is expecting the setting to be named `private_key`

dbt docs:
![image](https://github.com/astronomer/astronomer-cosmos/assets/18040744/57cd90e8-4fd1-4604-85da-78768ca2d032)

log from cosmos:
![image](https://github.com/astronomer/astronomer-cosmos/assets/18040744/d2f26c48-15e5-4153-9f52-85d666639cd6)

This makes dbt still try to find a password

**Comment by jlaneve** [comment]
Hey @nacpacheco, thanks for opening this! Any interest in opening a PR to fix the issue? Should be a fairly straightforward change 🙂
