### ISSUE TITLE
Spark Thirft Profile Does not Pick up Connection from Secrets Manager

### ISSUE THREAD

**Issue by shishircc** [astronomer/astronomer-cosmos#480]
I have a connection defined in aws secrets manager with value like 
{
"host": "ec2-xx-xxx-xxx-xxx.compute-1.amazonaws.com", 
"port": 10001, 
"schema": "my_schema",
"type":"spark",
"method":"thrift"
}
and key is like 
airflow/connections/my_spark_connection

I pass the profile mapping value of 
profile_mapping=SparkThriftProfileMapping(
                conn_id = 'my_spark_connection',
                profile_args = { } 
)

I expect dbt to then use the my_spark_connection from secrets manager. However DBT complains that 
`Credentials in profile "default", target "dev" invalid: 'schema' is a required property`

Is it possible that the value from secrets manager is not being picked up for SparkThrift profile  ?

**Comment by shishircc** [comment]
Strangely, it seems it worked once I changed 
profile_mapping=SparkThriftProfileMapping(
conn_id = 'my_spark_connection',
profile_args = { 'schema':'myschema' }
)

It seems it picked up the host and port from secrets manager key/value, but picked up schema from profile_args. 

I am trying to confirm this behaviour.

**Comment by etheleon** [comment]
Also have the same error message but this time it's complaining 

```
Credentials in profile "default", target "dev" invalid: \'database\' is a required property'
```

**Comment by etheleon** [comment]
After adding 'database' in my profile args I get another error 

```
 'Runtime Error', "  at path []: 'database' is a required property")
```
