### ISSUE TITLE
Virtualenv execution mode does not cleanup venv after exception

### ISSUE THREAD

**Issue by sphenlee** [astronomer/astronomer-cosmos#483]
If an exception is thrown while executing dbt in virtualenv mode, the venv directory isn't cleaned up.

Eventually the worker node fills the disk and fails.

See https://github.com/astronomer/astronomer-cosmos/blob/6ac1763057c44be5b76b9490224308bda09af1e8/cosmos/operators/virtualenv.py#L95-L98

There should be a finally block here.

**Comment by sphenlee** [comment]
Actually, I see the TemporaryDirectory automatically cleans up on garbage collection, so this is not an issue.

Closing.

**Comment by michalsosn** [comment]
Wouldn't it still be an improvement to place it in a try except block instead of waiting for GC? 
I don't really see a downside I sometimes manage to kill a worker by exhausting its storage space
