### ISSUE TITLE
Unable to select specific models to run in a dag 

### ISSUE THREAD

**Issue by aditipimpale** [astronomer/astronomer-cosmos#486]
Selecting specific models to run is possible via tags/config option. But is difficult to achieve so if I need to run all the upstream or downstream models related to a specific model.

Example:
Need to achieve something like : 
dbt run --select @some_test 

It can be achieved by leveraging tags, but adds up to the extra overhead of adding tags for each of the models(especially when a dbt project has 100s of defined models) which can otherwise be easily possible using graph operators.

**Comment by brunoh1990** [comment]
Hi @aditipimpale are you doing this using DbtTaskGroup and using the argument render_config? For me it is not working even on that end. I pass the tag but airflow is not rendering the models that it should.
dbt_test = DbtTaskGroup(
        group_id="run_dbt",
        project_config=ProjectConfig(
            dbt_project_path=DBT_PROJECT_PATH,
            models_relative_path="models",
            manifest_path="/target/manifest.json"
        ),
        profile_config=profile_config,
        execution_config=execution_config,
        render_config=RenderConfig(
            select=["tag:my_test"],
        )
    )

Using the code above but at least the select is not working. If I remover render_config it renders everything else just fine. 
It would be nice to have a select option that could be by model where we could add upstream and downstream options, tests and also state, to apply to only modified models for CI/CD integration. Don't know, do you know any of these are planned to be added?
New to Cosmos and saw your post that most fits the issue that I currently am facing just with the select tag option, if you can help there I would appreciate a lot!
Cheers!

**Comment by aditipimpale** [comment]
It would be more useful if you could mention the cosmos version that you are using.
I am working on `astronomer-cosmos==0.7.3`
and how we use it is:

DbtTaskGroup(
        dbt_project_name="my_project",
        group_id="some_group_id",
        conn_id="connection_id",
        select={"configs": ["tags:my_tag"]}
        dbt_root_path="/path/to/directory"
    )

**Comment by brunoh1990** [comment]
Hey @aditipimpale, thanks for the fast reply! :)
Good point forgot to mention it. I'm working with the latest version 1.0.5
Already able to work with the profile config and project config arguments which are very useful to have a Task Group less verbose.
Did use those versions of cosmos before in my tests, but wanted to use the stable version from 1.0.5 onwards. 
Being this so you probably can't help me. But we can keep a healthy discussion on the topic here if you want :)
Cheers!

**Comment by Akshay-Kokate** [comment]
@aditipimpale You can achieve this using RenderConfig.
Can you try the below 
```
RenderConfig(
select=["tag:my_test"],
load_method=LoadMode.DBT_LS
)
```

Let me know if this works.

**Comment by brunoh1990** [comment]
Hi,
It eventually worked with me in this manner:

profile_config = ProfileConfig(
    profile_name=PROFILE_NAME,
    target_name=dbt_exec.get("env_to_run"),
    profiles_yml_filepath=DBT_PROFILE_PATH,
)

project_config = ProjectConfig(
            dbt_project_path=DBT_PROJECT_PATH,
            models_relative_path="models",
            manifest_path="/target/manifest.json",
        )

# Path where dbt bin executable is stored (Needs to be used if execution mode is local)
execution_config = ExecutionConfig(
    execution_mode=ExecutionMode.LOCAL,
    dbt_executable_path=DBT_EXECUTABLE_PATH,
)

render_config = RenderConfig(
    test_behavior=TestBehavior.NONE,
    load_method=LoadMode.AUTOMATIC,
    select=[f"{model_to_run} --vars {load_mode}"],
    #select=[f"path:{path_to_run}"],
    #select=[f"tag:{tag_to_run}"],
)

# Dag default arguments
default_args = {
    "owner": 'airflow',
    "retries": 0
}

with DAG(
        dag_id="cosmos_dag",
        start_date=datetime(2024, 1, 1),
        default_args=default_args,
        schedule=None,
        catchup=False,
        concurrency=32,
):

    dbt_test = DbtTaskGroup(
        group_id="my_project",
        project_config=project_config,
        profile_config=profile_config,
        execution_config=execution_config,
        render_config=render_config,
        operator_args={
            "install_deps": False,  # install any necessary dependencies before running any dbt command
            "full_refresh": False,  # used only in dbt commands that support this flag
        },
    )


With this I was able to run exactly the model I wanted to run and pass an environment variable of my choice. It can be edited and I hope this may help anyone else. This ticket can be closed.
