### ISSUE TITLE
Unable to use DbtTaskGroup with Kubernetes 

### ISSUE THREAD

**Issue by adityasharma1685** [astronomer/astronomer-cosmos#491]
As per [this](https://astronomer.github.io/astronomer-cosmos/getting_started/kubernetes.html) documentation, we should be able to use DbtTaskGroup with Kubernetes, but there are two mandatory parameters, `project_config` and `profile_config` this task group expects. Now, according to the documentation I mentioned earlier, my DBT package and installation is within the image that I want to run, i.e., my Airflow Dag code and DBT code are in separate places. However, when I am deploying my code, the Dag is unable to load because it is not able to find dbt_project.yml in the path I have defined. The example shown in the documentation does not very well explain how to use this task group with Kubernetes. Also, in the example, it mentioned "DbtKubernetesOperator," which I am not able to find in the latest version of the package, `1.0.5`. Below is my code, please let me know if I am missing something. I really want to use this task group instead of running my Dbt job by using standard KubernetesPodOperator.

```
dbt_task = DbtTaskGroup(
        group_id="run_edge_customer",
        project_config=ProjectConfig(dbt_project_path="./"),
        profile_config=ProfileConfig(
            profile_name="profile_name",
            target_name="trino_task",
        ),
        operator_args={
            "queue": "kubernetes",
            "image": "my_image",
            "image_pull_policy": "Always",
            "get_logs": True,
            "is_delete_operator_pod": True,
            "namespace": "airflow",
            "env_vars": {
                "TRINO_CATALOG": "delta",
                "TRINO_SCHEMA": "default",
                "TRINO_HTTP_SCHEME": "https",
                "LIMIT_STATEMENT": " LIMIT 100000 ",
            },
            "retry_delay": timedelta(seconds=30),
            "node_selector": {"label": "nodepool1"},
        },
        execution_config=ExecutionConfig(execution_mode=ExecutionMode.KUBERNETES),
    )
```
I am not running this code locally, this is on the server.
`Apache-Airflow: 2.5.3`

**Comment by jlaneve** [comment]
Hi @adityasharma1685, thanks for filing this issue! When 1.1 is released with [this PR](https://github.com/astronomer/astronomer-cosmos/pull/505), the profile config issue should be fixed. Airflow still needs some visibility into your dbt project to understand how to construct the graph, and you can do that in 1 of 2 ways:
1. Copy your entire dbt project into your Airflow project at the path supplied in `ProjectConfig(dbt_project_path=...)`
2. Generate a manifest.json and put that in your Airflow project. Check out the [docs on loading your project from the manifest file here](https://astronomer.github.io/astronomer-cosmos/configuration/parsing-methods.html#dbt-manifest)

**Comment by adityasharma1685** [comment]
Thanks @jlaneve

**Comment by rtooker** [comment]
@jlaneve  - I noticed that dbt_project_path is mandatory https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/config.py#L57 and there's quite a bit of logic there that expects it (validation, post init).

I can't see how your option 2 will work with the current config structure? Is it expected that the entire project is present even if providing a manifest?

**Comment by qimumu9406** [comment]
> @jlaneve - I noticed that dbt_project_path is mandatory https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/config.py#L57 and there's quite a bit of logic there that expects it (validation, post init).
> 
> I can't see how your option 2 will work with the current config structure? Is it expected that the entire project is present even if providing a manifest?

I also encountered the same problem
