### ISSUE TITLE
Analyse Cosmos performance and possible bottlenecks

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#519]
Some questions we may want to answer:
1. How much time does it spend during DAG parsing for jaffle shop and a dbt project with 600 models? How different is the performance of different parsing methods?
2. How much time does it spend running a task compared to using the Bash Operator?

**Comment by DanMawdsleyBA** [comment]
On this I think one thing to consider is not rendering test tasks for every model if there is no tests (Or at least a setting to remove them) If we do want them then maybe use the airflow empty operator to speed up runtimes
