### ISSUE TITLE
Do not use task group and create a test task for a model that does not have tests

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#531]
As of Cosmos 1.1, if `test_behavior=TestBehavior.AFTER_EACH` (default), we always convert models into a task group containing a model run task and a test task, regardless of actual tests for that model.

@DanMawdsleyBA mentioned this issue in https://github.com/astronomer/astronomer-cosmos/issues/519#issuecomment-1714399354  and also in slack:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1694606935594769?thread_ts=1694551447.136999&cid=C059CC42E9W

The goal of this ticket is to change the Airflow DAG generation, so we only create a task group and the test task if there are test nodes associated with the model of interest.

**Comment by raffifu** [comment]
Hii, i'm interesting working on this issue. I think it can be configured on this [file](https://github.com/astronomer/astronomer-cosmos/blob/665a9b87a953e2659e5d2aecaefcf770374b08ae/cosmos/airflow/graph.py#L176). But i can't figure it out the solution now (need some time to try the project)

**Comment by tatiana** [comment]
This was released as part of 1.1.3:
https://pypi.org/project/astronomer-cosmos/1.1.3/
https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.1.3
