### ISSUE TITLE
Vertica adapter support

### ISSUE THREAD

**Issue by perttus** [astronomer/astronomer-cosmos#538]
Is it possible to add support for Vertica? There is already [dbt-vertica](https://github.com/vertica/dbt-vertica) adapter for it.

**Comment by jlaneve** [comment]
Hey @perttus, yes it's definitely possible! Would you be open to contributing a profile mapping? They're meant to be fairly straightforward to contribute, here's an example 🙂 

https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/profiles/postgres/user_pass.py

**Comment by perttus** [comment]
I just made the PR for Vertica
