### ISSUE TITLE
Create DbtDocsGCSOperator 

### ISSUE THREAD

**Issue by 1cadumagalhaes** [astronomer/astronomer-cosmos#541]
We have operators to upload docs to Amazon S3 and to Azure Storage. I would like to develop a new one, to use Google Cloud Storage.
https://astronomer.github.io/astronomer-cosmos/configuration/generating-docs.html

This is pretty straightforward and it might be a good first issue to contribute here, so I'll give it a try

**Comment by tatiana** [comment]
HI @1cadumagalhaes sounds great, please, do let us know if you need any support!

**Comment by podviaznikov** [comment]
need this one too!
