### ISSUE TITLE
Resource Type `operation` missing from the `DbtResourceType` Class

### ISSUE THREAD

**Issue by cashel** [astronomer/astronomer-cosmos#559]
[Hooks](https://docs.getdbt.com/docs/build/hooks-operations) are designated as [`operation` resource types](https://schemas.getdbt.com/dbt/manifest/v10/index.html#nodes_additionalProperties_oneOf_i2_resource_type) and this resource type is missing from the [`DbtResourceType` class](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/constants.py#L53C1-L62C22). 

I have a dbt project that utilizes `on-run-start` and `on-run-end` hooks, and I get the following error when trying to utilize [`dbt_manifest` parsing](https://astronomer.github.io/astronomer-cosmos/configuration/parsing-methods.html#dbt-manifest):

`ValueError: 'operation' is not a valid DbtResourceType`

I believe it's this lack of this `operation` resource type that is causing the failure.

**Comment by tatiana** [comment]
Thanks for reporting this, @cashel !
Would you have the capacity to help us implement this? If not, could you give a simple end-to-end example for us to reproduce this?

**Comment by edgga** [comment]
I believe it's a duplicate of https://github.com/astronomer/astronomer-cosmos/issues/477

**Comment by cashel** [comment]
@tatiana, happy to contribute to this project when and where I can, though it looks like #477 that @edgga mentioned already has a good fix that covers all edge cases 👍

**Comment by tatiana** [comment]
@edgga @cashel Following up on this ticket, since #503 closed #477 (released on Cosmos 1.2.0), I'm assuming this ticket also is closed. Please reopen with more details if necessary!
