### ISSUE TITLE
Make the arg `dbt_project_path` set in the `ProjectConfig` init optional 

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#569]
**Context**

Currently, users must declare the `dbt_project_path` argument when instantiating `ProjectConfig` (https://github.com/astronomer/astronomer-cosmos/blob/0123c3e19422bf665eca6a489a1248cc7ad17de9/cosmos/config.py#L57).

However, this variable should not be needed when rendering DAGs using a dbt manifest (`LoadMode.DBT_MANIFEST`). This is particularly relevant if users do not want to have their dbt pipelines together with the Airflow DAGs code, which should already be possible if they are using `ExecutionMode.KUBERNETES`.

**Proposal**

Make the `dbt_project_path` argument optional when instantiating `ProjectConfig`.

This ticket relates to #568 and it is also a follow-up to a conversation with @pgoslatara

**Comment by tatiana** [comment]
Discussed in the #airflow-dbt channel:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1696308262251219

**Comment by MrBones757** [comment]
I was discussing this in the slack thread linked above, and will attempt to work on the implementation of this.

**Comment by erdos2n** [comment]
@tatiana  can I take this issue?

**Comment by tatiana** [comment]
Hi @erdos2n , thanks for offering to help! I think @MrBones757  is working on this: #581

**Comment by tatiana** [comment]
This was released as part of 1.2:
* https://pypi.org/project/astronomer-cosmos/1.2.0/
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.2.0
