### ISSUE TITLE
Add support for dbt-spark adapter

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#58]
We should add all of the dbt supported platforms (and then move to the community ones). This will require two things:

- [ ]  default profile that maps to an Airflow connection
- [ ]  new extra in setup.cfg

- See Apache Spark setup in [dbt docs](https://docs.getdbt.com/reference/warehouse-setups/spark-setup). 
- See OSS Airflow Docs for [Apache Spark Connection](https://airflow.apache.org/docs/apache-airflow-providers-apache-spark/stable/connections/spark.html)

**Comment by tatiana** [comment]
@chrishronek I think #254 added support to this:
https://github.com/astronomer/astronomer-cosmos/tree/main/cosmos/profiles/spark

Please, reopen if there is something missing :)
