### ISSUE TITLE
docs: Improvement on Contributing Guide

### ISSUE THREAD

**Issue by raffifu** [astronomer/astronomer-cosmos#588]
## Problem
1. Currently there are duplicates steps on the contributing guide file which can confused for some people:
![image](https://github.com/astronomer/astronomer-cosmos/assets/22138274/7c9b33e0-617a-4b86-a10c-fcbf50f05b67)

2. I also encountered an error when trying to run `docker compose -f dev/docker-compose.yaml up -d --build` because of permission error on linux. The created folder for volume on linux is owned by root and need manual action to change permission of created folder
![image](https://github.com/astronomer/astronomer-cosmos/assets/22138274/fdf3539d-e7ca-4949-8a10-07686175511b)

## Proposal
I want to delete the duplicate steps and add more steps for change permission of folder, so user will not encountered permission error because of lack of permission

**Comment by tatiana** [comment]
Sounds excellent, @raffifu , thank you very much for taking the time to propose the improvements! Can't wait to see them
