### ISSUE TITLE
Add support for dbt-trino adapter

### ISSUE THREAD

**Issue by pohek321** [astronomer/astronomer-cosmos#59]
We should add all of the dbt supported platforms (and then move to the community ones). This will require two things:

- [ ]  default profile that maps to an Airflow connection
- [ ]  new extra in setup.cfg

- See Trino setup in [dbt docs](https://docs.getdbt.com/reference/warehouse-setups/trino-setup). 
- See OSS Airflow Docs for [Apache Trino Connection](https://airflow.apache.org/docs/apache-airflow-providers-trino/stable/connections.html)

**Comment by MikeWallis42** [comment]
@pohek321 I'd like to take a stab at this one please.
I use Trino in my day to day but through LDAP. I see there are a few different authentication methods with dbt so if I do this one and perhaps the others can be added as issues afterwards when users request them?

**Comment by pohek321** [comment]
@MikeWallis42 please do! It would be great to see _any_ type of auth as a starting point
