### ISSUE TITLE
Dissolve `ProjectConfig` into `RenderConfig` and `ExecutionConfig` supporting different dbt project paths for rendering and execution

### ISSUE THREAD

**Issue by david-mag** [astronomer/astronomer-cosmos#597]
Solution/proposal related to issue #568 that has possible backwards compatibility issues.

**Context**

As of Cosmos 1.1.x, the argument project_dir (passed in the `ProjectConfig` constructor) is used for two purposes:

1. To interpret the dbt project & build Airflow DAG
2. To execute the dbt project nodes

Although this makes sense for the `ExecutionMode.LOCAL`, it would make more sense to declare different paths when using `ExecutionMode.DOCKER` and `ExecutionMode.KUBERNETES`.

**Proposal**

With the `ProjectConfig` serving information for two purposes (rendering and execution), and purpose specific configs already existing (`ExecutionConfig` and `RenderConfig`). One approach could be to dissolve `ProjectConfig` into `ExecutionConfig` and `RenderConfig`. 

Currently the `ExecutionConfig` serves no other purpose than to specify which execution mode to run. Arguments that are execution specific that are currently stored in the `ProjectConfig` such as `models_relative_path`, `seeds_relative_path`, and `snapshots_relative_path` could be moved there, as well as an execution specific `project_dir` (currently `dbt_project_path`). *[All these arguments could/should be optional btw.]* 

The `RenderConfig` which already concerns how the dbt DAG is presented in airflow could do just that and include a `dbt_project_path` argument as well as a `manifest_path` [*I guess one of them needs to be required*], which are currently part of the `ProjectConfig`.

That way we could get rid of a dual purpose configuration and have the remaining configs be clearer in their scope.

**Comment by tatiana** [comment]
This was the way to go, but we may need to review this approach.

I have the impression that it does make sense to have a shared configuration between Execution and Render config - for local users' sake. It may or may not be `ProjectConfig`.

Whereas we should allow users who want to give different configurations to `RenderConfig` and `ExecutionConfig` to do so, we should also not burden the users who want the same configuration to be applied in both places to have to define them twice.

This is an example of an issue we came across while splitting the project dir and the dbt bin path in #568 : #666

**Comment by MrBones757** [comment]
I agree with the statement/s above.
With the work undertaken to add dbt_project_path to RenderConfig and ExecutionConfig (and thus supporting None in projectconfig), as well as other similar changes such as allowing the dbt executable to be different between RenderConfig and Execution, i'd say we're already most of the way there.

I can see allowing the manifest file to be defined in render config is a task that should be completed to better align those classes' use, and a review on the other fields remaining in ProjectConfig should also be done to see if we can create duplicates in other locations to prepare for a further ProjectConfig deprecation.

Doing it in a phased approach like this will also make it less painful if/when we deprecate ProjectConfig for most users.
