### ISSUE TITLE
Fix converting dbt projects that have ProjectConfig.dbt_project_path set as strings

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#601]
Our documentation has examples of configuring a project using a project path that is a string:
```
from cosmos.config import ProjectConfig

config = ProjectConfig(
    dbt_project_path="/path/to/dbt/project",
    models_relative_path="models",
    seeds_relative_path="data",
    snapshots_relative_path="snapshots",
    manifest_path="/path/to/manifests",
)
```
https://astronomer.github.io/astronomer-cosmos/configuration/project-config.html

However, if users attempt to use this, they will face an error:
```
Broken DAG: [/home/airflow/Sites/data-airflow/dags/high_freq_core_dbt.py] Traceback (most recent call last):
  File "/home/airflow/python-venvs/data-pipelines/lib/python3.10/site-packages/cosmos/airflow/task_group.py", line 26, in __init__
    DbtToAirflowConverter.__init__(self, *args, **specific_kwargs(**kwargs))
  File "/home/airflow/python-venvs/data-pipelines/lib/python3.10/site-packages/cosmos/converter.py", line 109, in __init__
    dbt_root_path = project_config.dbt_project_path.parent
AttributeError: 'str' object has no attribute 'parent'
```

Because of:
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/converter.py#L109-L110

This issue was originally reported in the #airflow-dbt slack channel by Sai:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1697234106298499?thread_ts=1697209691.193499&cid=C059CC42E9W

**Acceptance criteria**
As part of the fix, we should improve the converter tests by adding unit tests similar to:
https://github.com/astronomer/astronomer-cosmos/blob/main/tests/test_converter.py#L49-L69

We should validate at least the two following use-cases:
1. `ProjectConfig.dbt_project_path` as string
2. No `ProjectConfig.dbt_project_path`, to have a broader test of the improvement #581

**Comment by MrBones757** [comment]
I should have some time to take a look at this tomorrow!

**Comment by tatiana** [comment]
Thanks a lot, @MrBones757 ! I assigned it to you for now - please, let us know if the circumstances change
