### ISSUE TITLE
LoadMode.DBT_LS unnecessarily requires render_config.dbt_deps=True

### ISSUE THREAD

**Issue by nicohein** [astronomer/astronomer-cosmos#602]
With the version 1.2.0 I got the below error with the `LoadMode.DBT_LS`.

```
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/dbt/graph.py", line 134, in load
    load_method[method]()
  File "/opt/python3.8/lib/python3.8/site-packages/cosmos/dbt/graph.py", line 243, in load_via_dbt_ls
    raise CosmosLoadDbtException(
cosmos.dbt.graph.CosmosLoadDbtException: Unable to run dbt ls command due to missing dbt_packages. Set render_config.dbt_deps=True.
```

The below config was working with version 1.1.2.

```
RenderConfig(
    test_behavior=TestBehavior.AFTER_EACH,
    load_method=LoadMode.DBT_LS,
    dbt_deps=False,
)
```

There are no dependencies required for dbt_ls in my setup. I fully understand that there are cases but it's not universally true.
This enforced setting leads to a dag load times of between 45 and 70s (up from 25s) which I find very long with all our (more than 200) other DAGs loading below a single second.

My suggestion would be to throw a warning instead of an error: https://github.com/astronomer/astronomer-cosmos/blame/main/cosmos/dbt/graph.py#L244 
I would understand the behavior if the dbt ls command was throwing an error but this is generated from stdout, hence the request.

**Comment by tatiana** [comment]
Hi @nicohein , thank you very much for the feedback!

I just reviewed the code that should be generating this exception:
https://github.com/astronomer/astronomer-cosmos/blob/d61f120db9b37c2cb81d4e5744da28500bf7062e/cosmos/dbt/graph.py#L242-L245

And, ATM, this exception should only be raised if dbt itself outputs 'Run "dbt deps" to install package dependencies' ". Could you please confirm if this is the case in your project?

**Comment by nicohein** [comment]
Hi @tatiana,
I have not invested more tim ein this and have solved the issues with a different setup altogether. As I will unfortunately not have much more time to contribute here, it is fine with me to close this.
Best
Nico
