### ISSUE TITLE
Proposed additional LoadMode for Faster DAG Load Times

### ISSUE THREAD

**Issue by nicohein** [astronomer/astronomer-cosmos#603]
DAG load times are observed to be long for cosmos DAGs. The load times for vary greatly between different LoadModes and are currently also dependent on the size of the dbt project. This is mostly caused by top level code that has non constant execution times.

In this context, and the Airflow best practice to reduce top level code (https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code) I would like to propose a new LoadMode for astronomer-cosmos that moves the more complex parts of the Dag render process into a build pipeline or runs it only when required.

It appears that the hardest problem to solve during the DAG load is the `dbt ls --select <selection>` process and it's variants.
This process does not need to be repeated with each DAG load and hence there are a few options to be considered. I would like to discuss two in this issue:

1. Run the `dbt ls --select <selection>` only when the dbt code changed 
2. Run the `dbt ls --select <selection>` in a build pipeline and ony read a yaml during the load of the DAG 

## Render only when dbt Code Changed

1. For example use the creation time of the `manifest.json` as the proxy for dbt code changes. The file creation time is monitored and lets say stored in an Airflow variable specific to each DAG. Let's call it `cosmos_dag_maifest_change_time` for now.
2. When the value of the `cosmos_dag_maifest_change_time` variable is different from the actual file creation time (`os.path.getmtime("/home/airflow/data/dbt/target/manifest.json")`) then the full init function of the `DbtToAirflowConverter` must be executed, including `dbt_graph.load(method=load_mode, execution_mode=execution_mode)` and the cosmos_dag_maifest_change_time will be updated.
3. If the `manifest.json` was unchanged, then the `DbtGraph` is loaded from a pickle file instead.

This could probably be achieved by using pickle files in the `/data` or `/dags` folder wherever more appropriate. 

It would require at least parts of the `DbtGraph` to be pickled https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/converter.py#L140C21-L140C29. Each graph would require an id to identify the right pickle file. I could imagine that the `RenderConfig.select` parameter could be a good enough id. (Base64 encoding would solve any problems with special characters.)

This option has the advantage that no preprocessing is required. It has the disadvantage that the the Airflow scheduler might be overwhelmed every time the dbt project changes, because then all cosmos dags would run a full re-load.

## Render as part of a Build Pipeline

This flow would allow to achieve consistent load times and entirely remove the requirement to execute `dbt ls --select <selection>`  in any form on the Airflow scheduler. The flow could look as follows:

1. During build run `dbt ls --select <selection> --output json` for each required selection as available in the RenderConfig objects and store the output in a file with something like the base64 encoding of the selection as the name. (E.g. `base64.b64encode(b"tag:test")` would result in `dGFnOnRlc3Q.json`.) Alternatively the output could be stored in an Airflow Variable.
2. The new LoadMode would allow to create the Airflow DAG nodes from this json in time linear to the DAG size.

The biggest challenge with this approach is to know all the relevant selections in advance during the build. All options I could so far think about either require an airflow environment in the build context or require to maintain a list of selections in a file that can be rendered without airflow.

I am looking forward to the conversation around this topic.

**Comment by jlaneve** [comment]
This is a great idea! Have you seen https://github.com/astronomer/astronomer-cosmos/issues/520#issuecomment-1756310501? I've outlined some of my thoughts there - your first approach and my caching approach sound very similar

**Comment by nicohein** [comment]
Sorry I have missed this issue! These two approaches indeed sound very similar. The second approach adds a new perspective that is not yet discussed. Let's continue the conversation on #520. I will add a comment there soon.
