### ISSUE TITLE
Snowflake auth encrypted key path not supported

### ISSUE THREAD

**Issue by ivanstillfront** [astronomer/astronomer-cosmos#607]
`astronomer-cosmos` is unable to map a snowflake connection with an encrypted private key **path**

To reproduce, use an Airflow connection to Snowflake with `extra.private_key_file` and `password` settings, for example:
```
AIRFLOW_CONN_SNOWFLAKE_TEST='{
  "conn_type": "snowflake",
  "login": "username",
  "password": "secret",
  "host": "https://ACCOUNT.snowflakecomputing.com",
  "schema": "public",
  "extra": {
    "region": "eu-central-1",
    "account": "ACCOUNT",
    "private_key_file": "/path/to/rsa_key.p8",
    "database": "test",
    "role": "system",
    "warehouse": "default"
  }
}'
```

**Comment by DanMawdsleyBA** [comment]
Great work! Any idea on when this would get released? I'm currently looking to switch to the profile mapping using this
