### ISSUE TITLE
Refactor LoadMethod.LOCAL to use symlinks as opposed to copying the dbt source dir

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#614]
As of Cosmos 1.0-1.2, it copies the entire dbt project for every operator that runs dbt:
https://github.com/astronomer/astronomer-cosmos/blob/c82e6bc66dd31d6e1404fc24548d978489f4f0ab/cosmos/operators/local.py#L198

As reported in the #airflow-dbt slack, this can lead to performance issues:
https://apache-airflow.slack.com/archives/C059CC42E9W/p1697718075031609?thread_ts=1697708239.918849&cid=C059CC42E9W

We successfully adopted a strategy of using symbolic links from a temporary folder to run `dbt ls`:
https://github.com/astronomer/astronomer-cosmos/blob/c82e6bc66dd31d6e1404fc24548d978489f4f0ab/cosmos/dbt/graph.py#L167-L171

The goal with this ticket is to adopt this same strategy when running tasks using `LoadMethod.LOCAL`.

**Comment by jbandoro** [comment]
I can work on this one, in #629 to reduce complexity I created the function: https://github.com/astronomer/astronomer-cosmos/blob/9cd46d2353dff874cc94c66baa0b146255ec42f5/cosmos/dbt/graph.py#L56-L61

which could be `DbtLocalBaseOperator.run_command`.
