### ISSUE TITLE
Profile Mapping for MWAA secrets backend

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#617]
Would it be possible set up another profile mapping specific to MWAA where it could take the AWS secret connection to load up the details of a database connection and then map it to a profile . Similar to how Airflow connections are mapped currently to profile

**Comment by benjamin-awd** [comment]
If you have your secrets backend set up correctly, Airflow should be able to access the secrets as connections

Assuming that you have a secret:
```terraform
resource "aws_secretsmanager_secret" "this" {
  name = "${module.data.mwaa_connection_secrets_prefix}/aws_athena"
}

resource "aws_secretsmanager_secret_version" "this" {
  secret_id     = aws_secretsmanager_secret.athena.id
  secret_string = "aws://${local.aws_access_key_id}:${local.aws_secret_access_key}@/?s3_staging_dir=${local.s3_staging_dir}&s3_data_dir=${local.s3_data_dir}&region_name=${var.region}&database=${local.database}&schema=${var.schema}&work_group=${local.workgroup_name}"
}
```

it should be automatically populated in MWAA, meaning that you can then pass the connection to your profile:
```python
profile_config = ProfileConfig(
    profile_name="athena",
    target_name=ENV_NAME,
    profile_mapping=AthenaAccessKeyProfileMapping(
        conn_id="aws_athena",
    ),
)
```

But you'd probably need to define a mapping for whatever dbt adapter you want to use (assuming that it's not dbt-athena)
