### ISSUE TITLE
After all test behaviour with select and exclude

### ISSUE THREAD

**Issue by ndrluis** [astronomer/astronomer-cosmos#643]
Hello, the AFTER_ALL tests behavior is not considering the select and exclude settings defined in the rendering configuration.

Test Behavior: After All
Load Method: DBT ls
Execuction mode: Kubernetes
Test indirect selection: Buildable

<img width="1267" alt="image" src="https://github.com/astronomer/astronomer-cosmos/assets/1859449/4b22cef8-81e3-4430-a272-ae96785ad0c0">

**Comment by tatiana** [comment]
Thanks for reporting this issue, @ndrluis! Would you like to help us fix this?

**Comment by ndrluis** [comment]
Hello @tatiana, I am interested, but I need help understanding where I should make this correction.

I am studying the code, and I'm not sure if I got it right. But I believe I would need to pass the select and exclude values to the `build_airflow_graph` function and then to `create_test_task_metadata` when `TestBehavior.AFTER_ALL` is used. 

Within `create_test_task_metadata`, I would check if the load mode is `DBT_LS` and pass the values to the select and exclude arguments.

Is it something along these lines?

**Comment by tatiana** [comment]
> Hello @tatiana, I am interested, but I need help understanding where I should make this correction.
> 
> I am studying the code, and I'm not sure if I got it right. But I believe I would need to pass the select and exclude values to the `build_airflow_graph` function and then to `create_test_task_metadata` when `TestBehavior.AFTER_ALL` is used.

Yes, I believe we could pass `render_config` as an argument of `build_airflow_graph` and expose select/exclude in `create_test_task_metadata`, as you suggested.

> Within `create_test_task_metadata`, I would check if the load mode is `DBT_LS` and pass the values to the select and exclude arguments.

I don't think we'd need to check if it is `DBT_LS`. Why do you think this would be necessary? This issue happens for other `LoadMode`s as well, and it makes sense for the test task craeted to only run tests for the subset of tasks filtered using `RenderConfig`.

**Comment by binhnq94** [comment]
I have the same issue.
