### ISSUE TITLE
Create an Airflow DAG/Task Group from a dbt selector argument

### ISSUE THREAD

**Issue by pohek321** [astronomer/astronomer-cosmos#67]
If this were completed, the DbtTaskGroup and DbtDag parsers would be able to parse given a selector argument like so:

```python
DbtTaskGroup(project="...", selector="tag:foo+", ...)
```

**Comment by pohek321** [comment]
dbt's official docs on tags [here](https://docs.getdbt.com/reference/resource-configs/tags)

**Comment by dweaver33** [comment]
We will need this as well.

**Comment by jlaneve** [comment]
@pohek321 want to split these into different issues for each of the selector types?

**Comment by pohek321** [comment]
- Created issue [89](https://github.com/astronomer/astronomer-cosmos/issues/89) for path selector method
- Created issue [90](https://github.com/astronomer/astronomer-cosmos/issues/90) for config selector method
- Created issue [91](https://github.com/astronomer/astronomer-cosmos/issues/91) for `test_type` selector method
- Created issue [92](https://github.com/astronomer/astronomer-cosmos/issues/92) for `test_name` selector method

**Comment by pohek321** [comment]
Closing issue since we split it out into smaller issues.
