### ISSUE TITLE
Raise exception when attempting to run a model that dbt can't find

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#682]
**Context**

Cosmos 1.2 considers a model run task successful even if dbt finds no models for that execution, as illustrated in:
https://github.com/astronomer/astronomer-cosmos/pull/662#issuecomment-1814372773

The Airflow task succeeds, but the logs say:
```
[2023-11-16T12:32:37.420+0000] {subprocess.py:94} INFO - (astronomer-cosmos) - 12:32:37  The selection criterion 'customers_USA_v1' does not match any nodes
```

I'd expect us to be able to reproduce this by instantiating a `DbtRunLocalOperator` https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/operators/local.py#L433C7-L433C26 with a select statement that doesn't match any dbt models.

**Proposal**

(I would love thoughts from the community!)

We should raise an exception if dbt's output contains "select statement that doesn't match any dbt models".
We could allow users to opt out of this behaviour via some configuration.

**Comment by MrBones757** [comment]
What does DBT do in the case it doesn't match? 

If DBT fails in this situation i would say we should fail as a default and allow the user to turn it off. Likewise if DBT doesn't fail we should follow suit and add a toggle to enable failing.

**Comment by tatiana** [comment]
@MrBones757 I really like your approach to this - but I feel in this particular case, things are not as clear.

`dbt ls`, for instance, doesn't return an error (return code) even when there are errors (such as missing dependencies!) - it merely outputs the error on the standard output.

Since dbt Core users use the command line, they always see the output - regardless of the OS return code /stderr, so the error is visible. I don't have access to dbtCloud, but I'd expect them to be exposed in the UI if a model expected to run did not run.

In the case of Cosmos/Airflow, we need to make a call of which scenarios represent a task failure - since we cannot rely on dbt Core return codes or the stderr.
