### ISSUE TITLE
Add back newlines into log format

### ISSUE THREAD

**Issue by joppevos** [astronomer/astronomer-cosmos#687]
The stderror from dbt is displayed on a single line in Airflow logs. This makes it difficult to read what is going on. 
We get back the new lines to display it just as DBT does on CLI.

This is part of the log that is outputted on the single line:
```airflow.exceptions.AirflowException: ('dbt command failed. The command returned a non-zero exit code 1. Details: ', '\x1b[0m07:55:11  Running with dbt=1.5.0', '\x1b[0m07:55:14  Unable to do partial parsing because saved manifest not found. Starting full parse.', '\x1b[0m07:55:18  Found 3 models, 25 tests, 0 snapshots, 0 analyses, 596 macros, 0 operations, 0 seed files, 2 sources, 0 exposures, 0 metrics, 0 groups', '\x1b[0m07:55:18', "\x1b[0m07:55:18  Concurrency: 3 threads (target='prod')", '\x1b[0m07:55:18', ```

It looks like we can use `\x1b` or the comma's to get back the new line structure.

Screenshot of Airflow
<img width="1096" alt="image" src="https://github.com/astronomer/astronomer-cosmos/assets/44348300/fc2776d2-6771-43a9-925e-3b2e7b7d1879">

I am happy to give it a shot

**Comment by tatiana** [comment]
Hi @joppevos , thanks for raising this. We'd appreciate your contribution!
