### ISSUE TITLE
LoadMode.CUSTOM cannot select tags

### ISSUE THREAD

**Issue by adammarples** [astronomer/astronomer-cosmos#693]
https://github.com/astronomer/astronomer-cosmos/blob/d28d3df7eacac74d0fbb016be70434bcc30c51be/cosmos/dbt/graph.py#L314C17-L314C25

`load_via_custom_parser` hard codes DbtNode.tags attribute to be an empty list
 
 ```python
         for model_name, model in models:
            config = {item.split(":")[0]: item.split(":")[-1] for item in model.config.config_selectors}
            node = DbtNode(
                unique_id=f"{model.type.value}.{self.project.project_name}.{model_name}",
                resource_type=DbtResourceType(model.type.value),
                depends_on=list(model.config.upstream_models),
                file_path=Path(
                    model.path.as_posix().replace(
                        self.render_config.project_path.as_posix(), self.execution_config.project_path.as_posix()
                    )
                ),
                tags=[],
                config=config,
            )
  ```
  
  This causes `_is_tags_subset` to return False every time
  
  ```python
      def _is_tags_subset(self, node: DbtNode) -> bool:
        """Checks if the node's tags are a subset of the config's tags."""
        if not (set(self.config.tags) <= set(node.tags)):
            return False
        return True
 ```
 
 because set(node.tags) is always empty.

**Comment by tatiana** [comment]
@adammarples I just checked on the main branch, and the latest versions of Cosmos, both 1.2.5 and 1.3.0a2 should have this fixed:
https://github.com/astronomer/astronomer-cosmos/blob/173436552c8362e229258386e63ceb395fa33a44/cosmos/dbt/graph.py#L112

Could you upgrade and confirm if it works as expected, please?

**Comment by adammarples** [comment]
Hi @tatiana this is not a problem with DBT_LS but with load via custom parser https://github.com/astronomer/astronomer-cosmos/blob/2878d6accc2a725502158247dbd1af7ac37b4449/cosmos/dbt/graph.py#L314 which is still there in 1.2.5 etc

**Comment by tatiana** [comment]
HI @adammarples , please, could you confirm if this is still an issue in Cosmos 1.4?
Would you like to contribute to the fix?

**Comment by nathan-nguyen-webjet** [comment]
Can confirm dbt_ls fixed the bug for me, custom mode fail to create the graph
