### ISSUE TITLE
Add dbtRunOperation Operator

### ISSUE THREAD

**Issue by dweaver33** [astronomer/astronomer-cosmos#70]
Sometimes we need to run some macros via the [dbt run-operation](https://docs.getdbt.com/reference/commands/run-operation). Examples would include:
* Staging external tables
* Setting up permissions

**Comment by pohek321** [comment]
@ dweaver33 This already exists [here](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/providers/dbt/core/operators.py#L338-L369). Unless I'm misunderstanding and it isn't doing what you are referring to?

**Comment by dweaver33** [comment]
@pohek321, my apologies! Might be a good idea to document the available operators in the README.md file.
