### ISSUE TITLE
Expose environment variables and dbt vars configuration via `ProjectConfig`

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#712]
**Context**

As of Cosmos 1.2.4, users cannot define dbt `--vars` when running `LoadMode.DBT_LS` during project parsing / DAG rendering. They are able to define environment variables, thanks to #690 .

At the moment, users have to also define the environment variables and dbt vars for the task execution, using:
`operator_args={"env": ..., "var": ...}`
as described in https://astronomer.github.io/astronomer-cosmos/configuration/operator-args.html

This discussion started as part of this review:
https://github.com/astronomer/astronomer-cosmos/pull/690#pullrequestreview-1744068052

**Acceptance criteria**

* Deprecate operator args env & var, raising warnings, and fully deprecate them as of Cosmos 2.x
* Deprecate RenderConfig.env_vars, raising warnings, and fully deprecate them as of Cosmos 2.x
* Expose both dbt_vars and env_vars within the `ProjectConfig`
* Update the documentation and example DAGs to use the new `ProjectConfig` arguments

**Comment by jbandoro** [comment]
Thanks @tatiana for the detailed AC, I can work on contributing this 👍

**Comment by jbandoro** [comment]
@tatiana do you by chance have a dbt example where dbt variables passed to `dbt ls` will change the models listed. I'd like to have tests for this when use load method of dbt ls with `--vars` but haven't found any examples of where variables could be used in order to change the dbt graph cosmos would render.
