### ISSUE TITLE
Avoid installing deps in Local mode - behaviour change in 1.2.4

### ISSUE THREAD

**Issue by sphenlee** [astronomer/astronomer-cosmos#715]
We're using Cosmos in a regulated environment (FedRAMP) so we aren't allowed to let `dbt` install dependencies at runtime. Instead we package up the project with all the dependencies in our build pipeline and then unpack the whole thing into Airflow. We run Cosmos with the Local executor mode.

The recent release 1.2.4 has broken our workflow since the dependencies are no longer being copied, and the suggested fix (to use `install_deps` - see https://github.com/astronomer/astronomer-cosmos/issues/713 ) isn't allowed due to regulations.

https://github.com/astronomer/astronomer-cosmos/commit/2b91285d352d29aae3e09463465978f978b715df#diff-cdc7f3cedeca298d5c3bdd8d9be8fa15791b915fbe1b2810e9c86c271eb86446L200

This diff :arrow_up: changed `copytree` into `create_symlinks` which skips over the `dbt_packages` directory.

(I'm happy to contribute a fix to make this behavior configurable but would appreciate any guidance about how to best achieve this!)

**Comment by jbandoro** [comment]
@sphenlee this issue was fixed in #730, and there will be a new alpha release for v1.3 that will have the fix.
