### ISSUE TITLE
Tasks are running full parse each time 

### ISSUE THREAD

**Issue by DanMawdsleyBA** [astronomer/astronomer-cosmos#722]
I've noticed that within each job it is running a full parse each time. I upload the manifest as part of the cicd so not sure why it isn't recognizing the existing manifest file. This could significantly improve the job performance currently full parse step takes 7 seconds per task. 
![image](https://github.com/astronomer/astronomer-cosmos/assets/134394384/38fe30e0-4ac8-4577-90cd-c8274b23c67c)

**Comment by DanMawdsleyBA** [comment]
I think this is due to the syslink again as it does not copy across the target path by default. We could add a step to check if the manifest file is present then syslink just the manifest file. This should mean each task does not need to be reparsed fully each time

**Comment by lrcuwicRSG1** [comment]
Hi @all, I am new to astronomer cosmos and I have the same performance issues as @DanMawdsleyBA noticed. When will it be fixed? @tatiana  Milestone 1.4.0 was updated for the release date

In the meanwhile I want to fix it temporary with the codesnippet from dosubot. What is the easiest way to modiy the graph.py file and take it over to my local docker-installation based on astronomer-runtime and astro-cli? I am looking forward to your suggestions. Thanks Chris

**Comment by tatiana** [comment]
@DanMawdsleyBA @lrcuwicRSG1 Around two weeks ago, we managed to have an alpha release with #800 by @dwreeves, which seems to solve the problem. Could you try it out using [1.4.0a1](https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.4.0a1)? We're planning to release the stable 1.4 with this feature next week, and it would be great to confirm if/how much it helped you

**Comment by lrcuwicRSG1** [comment]
@tatiana Thanks for your reply. The issue #800 was on my watchlist ;) I will try it soon. Cheers Chris

**Comment by DanMawdsleyBA** [comment]
I am using 1.4.0a1 and wasn't able to get it to work because DBT was saying the profile and env vars have changed. 

[2024-03-14, 17:04:56 GMT] {{subprocess.py:94}} INFO - [0m17:04:56  Running with dbt=1.7.9
[2024-03-14, 17:04:57 GMT] {{subprocess.py:94}} INFO - [0m17:04:57  Registered adapter: snowflake=1.7.2
[2024-03-14, 17:04:57 GMT] {{subprocess.py:94}} INFO - [0m17:04:57  Unable to do partial parsing because config vars, config profile, or config target have changed
[2024-03-14, 17:04:57 GMT] {{subprocess.py:94}} INFO - [0m17:04:57  Unable to do partial parsing because profile has changed
[2024-03-14, 17:04:57 GMT] {{subprocess.py:94}} INFO - [0m17:04:57  Unable to do partial parsing because env vars used in profiles.yml have changed
[2024-03-14, 17:05:00 GMT] {{subprocess.py:94}} INFO - [0m17:05:00  Found 47 models, 12 snapshots, 0 sources, 0 exposures, 0 metrics, 554 macros, 0 groups, 0 semantic models

In my cicd pipeline I use a dummy target to generate the manifest. As cosmos uses a different target and generates it own in env vars I'm not sure if it will work? (I could be wrong I also use env vars for other things as well)

**Comment by dwreeves** [comment]
I was able to get it to work but it's a lot of effort. Later today I'll post the full guide. I think I actually posted it elsewhere in a comment in this repo.

**Comment by dwreeves** [comment]
I do agree that specifying a `profiles_yml_filepath` is the best way to go for most users. It should be what the docs suggest.

It's also possible to do something like this:

> 1. Go to one of your DbtOperator task logs in Airflow, and copy the `profile` YAML you see in the logs.
>    It will look something like this (example of a Snowflake profile):
> 
>    ```yaml
>    my_profile_name:
>        outputs:
>            airflow_target:
>                account: myaccount
>                database: mydatabase
>                password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
>                # ... etc. ...
>        target: my_target_name
>    ```
> 
> 2. Add this file to your Airflow project somewhere, e.g. `dags/dbt/profile/profiles.yml`.
> 
> 3. In your CICD, set the `DBT_PROFILES_DIR` env var to the folder you placed that file, e.g. `dags/dbt/profile`.
> 
> 4. Add `--profile [my_profile_name] --target [my_target_name]` to the `dbt parse` command you run in your CICD (replace `[my_profile_name]` and `[my_target_name]` with the appropriate names). **You must add these flags and you cannot just rely on defaults.** This is because dbt partial parsing does a checksum on a subset of the flags used in the CLI, and both `--profile` and `--target` are included in the checksum. Failing to add these flags means it won't work.
> 
>    ```shell
>    dbt deps
>    dbt parse --profile [my_profile_name] --target [my_target_name]
>    ```
> 
> 5. You must set up your CICD to run **the exact same connection you use in Cosmos**, meaning that you need to set `COSMOS_CONN_SNOWFLAKE_PASSWORD` to be the password you use in production. _Again_, similar deal as above: dbt does checksums when parsing, and every call to the `env_var()` macro creates a side-effect where the key-value pair of the env var is eventually put into the hash.
> 
> 6. Any `--vars` and env vars you use must also be included the exact same way you use them in Airflow. **You cannot rely on DagRun-specific or DAG-specific parameterized vars / env vars, otherwise partial parsing won't work.** (The 1.5.0 or later updates to partial parsing support should address this limitation, though.)
