### ISSUE TITLE
Can't use model name in selector

### ISSUE THREAD

**Issue by ykuc** [astronomer/astronomer-cosmos#723]
We can't use model name in selector, use path but it isn't comfortable. Model name is unique in dbt. 
https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/dbt/selector.py#L15

Example dbt run --select "my_dbt_model"
https://docs.getdbt.com/reference/node-selection/syntax

**Comment by jbandoro** [comment]
@ykuc sorry to hear you're having issues. Can you confirm what Cosmos version you're using and which [load method](https://astronomer.github.io/astronomer-cosmos/configuration/parsing-methods.html) you're working with?

Currently selecting my model name is only supported using `dbt_ls`. There is good news is that there is an open PR https://github.com/astronomer/astronomer-cosmos/pull/728 will allow this for the `custom` and `dbt_manifest` load methods if you're using either of those.

**Comment by ykuc** [comment]
Hi, @jbandoro 
v1.2.5 and standard method (don't change it). Now dbt install on the same vm as airflow

> Currently selecting my model name is only supported using dbt_ls
sorr i had a problem with previous version...

**Comment by jbandoro** [comment]
> Hi, @jbandoro
> v1.2.5 and standard method (don't change it). Now dbt install on the same vm as airflow

Thanks, so you would be using the [automatic](https://astronomer.github.io/astronomer-cosmos/configuration/parsing-methods.html#automatic) load method that tries to use manifest load, dbt ls, then falls back to the custom load method. In your dbt DAG can try using `LoadMode.DBT_LS` like below:

```python
from cosmos import LoadMode
...
DbtDag(
    render_config=RenderConfig(
        load_method=LoadMode.DBT_LS,
    ...
    )
)
```
If the dbt ls load mode DAG falls to render then that means it's falling back to the `custom` load method where selecting by model name is not yet supported.

If you're seeing errors it would be helpful if you could share your example DAG that's not working and any stack logs.
