### ISSUE TITLE
BUG: Version 1.2.5 does not contain env_vars in RenderConfig

### ISSUE THREAD

**Issue by SEBASTISCHMITT** [astronomer/astronomer-cosmos#726]
in the release overview and also in the documentation the Class RenderConfig() has the parameter 'env_vars' but in the code the parameter is missing https://github.com/astronomer/astronomer-cosmos/blob/2878d6accc2a725502158247dbd1af7ac37b4449/cosmos/config.py#L32

a new Release with this feature (like in main) would be nice

**Comment by tatiana** [comment]
@SEBASTISCHMITT  This feature is part of the 1.3 release. You can find it at https://pypi.org/project/astronomer-cosmos/1.3.0a3/

We need to improve our documentation process, so it is versioned #750. In the meantime, we'll try to be more explicit in the docs about from which version that feature is available.
