### ISSUE TITLE
path downstream

### ISSUE THREAD

**Issue by Lee2532** [astronomer/astronomer-cosmos#739]
I tried to configure downstream by configuring a path such as model or other snapshots as dir, but it didn't work properly.

For example, I would like to configure and apply downstream for each dir in the model such as staging and marts
my code
`
models_relative_path = Path("models", "marts")

project_config=ProjectConfig(DBT_PROJECT_PATH
                        , models_relative_path=models_relative_path
                                     )
`

debugging then path is WindowsPath('dags/dbt/sakila/models')

but is not work.

**Comment by tatiana** [comment]
@Lee2532 did you consider using path selectors, as described in https://astronomer.github.io/astronomer-cosmos/configuration/selecting-excluding.html?

**Comment by Lee2532** [comment]
it works Thanks
