### ISSUE TITLE
Extend DbtDocsLocalOperator with --static flag

### ISSUE THREAD

**Issue by joppevos** [astronomer/astronomer-cosmos#746]
dbt docs can be hosted in cloud storage as a static page application. The contents of `catalog.json` and `manifest.json` are then directly inserted into the `index.html`. 

A static page app has advantages. For example: 
- Upload and host directly from cloud storage, instead of a server. Making it cheap and easy
- Single page, making it easy to share around. email, slack etc
- Use Cloud Storage provider permissions on the file

Since a few months, DBT provides a flag to do this
`dbt docs generate --static`

I propose to extend this flag to the DbtDocsLocalOperator
Read more about this feature in the dbt discussion [here](https://github.com/dbt-labs/dbt-docs/issues/53)

I'm happy to work on this :)

**Comment by tatiana** [comment]
That's a great idea and initiative, @joppevos - the ticket is assigned to you! 🚀
