### ISSUE TITLE
DBT_MANIFEST mode does not use manifest for task execution

### ISSUE THREAD

**Issue by flinz** [astronomer/astronomer-cosmos#791]
I am using DBT_MANIFEST parsing mode, and seeing quite a bit of time being spent in each **task** on parsing the whole project, spending around 1/3 of the task total time on a full parse:

```
[2024-01-09, 16:51:27 CET] {subprocess.py:94} INFO - [0m15:51:27  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2024-01-09, 16:51:30 CET] {subprocess.py:94} INFO - [0m15:51:30  Found 38 models, 6 tests, 20 sources, 0 exposures, 0 metrics, 532 macros, 0 groups, 0 semantic models
```

I see the command being executed for each task is along the lines of 
```
[2024-01-09, 16:51:23 CET] {subprocess.py:73} INFO - Running command: ['/opt/***/dbt_venv/bin/dbt', 'run', '--models', 'mart_facts_samples', '--profiles-dir', '/tmp/tmpnhr57up0', '--profile', 'default', '--target', 'prod']
```

I believe that providing the `target-dir` with the `manifest.json` in the command execution would probably allow skipping the re-parsing of the project for each **task**.

Related to this:
- https://github.com/astronomer/astronomer-cosmos/issues/520: this is at DAG parsing time, but not at task execution time
- https://github.com/astronomer/astronomer-cosmos/issues/785: is probably a more generic API for this -- i think for DBT_MANIFEST mode, this could be solved in an easier way by just using the existing manifest?

I am fairly new to cosmos, so I would be grateful for some pointers in the right direction.

**Comment by dwreeves** [comment]
I think this is essentially the same as #785; I think the runtime only uses the manifest if it detects no code changes, which it can only do with the `msgpack`.

Let me know if you'd like to coordinate adding this change as I was going to get to it this weekend, but we could work together on it. The solution is if an existing target dir is found that the whole target dir should be moved into the tmpdir for the runtime.

**Comment by flinz** [comment]
Hi @dwreeves ,

Next to the job I don't have much time to work on this, but i am happy to help if i manage.

I would probably start by adding support for supplying the msgpack in `dbt-manifest` mode, with a more generic API change in mind after. But we would need agree on the final design of how msgpack/manifest is copied to the tmp directories.

Do you have a branch already? I will close this issue in favor of #785  and we continue discussing there then.
