### ISSUE TITLE
LoadMode.DBT_LS_FILE does not render test nodes

### ISSUE THREAD

**Issue by cashel** [astronomer/astronomer-cosmos#798]
Test nodes listed within a `dbt ls` output file utilized by `LoadMode.DBT_LS_FILE` do not render as Airflow tasks. 

Digging into the DAG’s log on the scheduler, I can see Cosmos is parsing both model and test nodes from the file, but only the model nodes are showing successful conversions whereas the test nodes show only that they started conversion and nothing else.

[Looking at the code](https://github.com/astronomer/astronomer-cosmos/blob/1b7f4a06e06cb5af75bf411a28dca932ef37ab5d/cosmos/dbt/graph.py#L305-L306), I see all load mode functions, except `DBT_LS_FILE`, have the following bit of code at the end to update test dependencies (and log node counts):

```python
self.update_node_dependency()


logger.info("Total nodes: %i", len(self.nodes))
logger.info("Total filtered nodes: %i", len(self.nodes))
```

I’m assuming it’s this lack of `update_node_dependency` call that is resulting in task nodes from successfully completing conversion into Airflow tasks?

**Comment by jbandoro** [comment]
Thanks @cashel for reporting this! 

I added a PR that will resolve this and be fixed soon in the next patch release v1.3.2
