### ISSUE TITLE
Model selection "

### ISSUE THREAD

**Issue by enkeboll** [astronomer/astronomer-cosmos#822]
Migrating an issue raised in the [`#airflow-dbt` slack org](https://apache-airflow.slack.com/archives/C059CC42E9W/p1706214231926849):
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/060d5f80-a4aa-44cb-ae65-d89d143aeece)
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/a584dce3-da43-4e9e-b4e7-625fa766af8f)

Basically, the "plus" operator isn't properly parsed when used with tags. So `tag:every-hour` works but `+tag:every-hour` or `tag:every-hour+` result in empty graphs.  We use this syntax in our DBT Cloud scheduled jobs, even though it isn't explicitly called out in the [DBT docs](https://docs.getdbt.com/reference/node-selection/graph-operators):
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/b8a47728-13f4-4d00-bfb8-4f10fb51b4b2)

I'm happy to try to take a stab at adding this functionality to [selector.py](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/dbt/selector.py), unless there's a reason to hold off.

**Comment by jbandoro** [comment]
hey @enkeboll I'm closing this since it's the same as #823

**Comment by enkeboll** [comment]
Thanks - GH gave me a weird error and then I couldn't find the issue, so I made another.
