### ISSUE TITLE
Model selection "plus" operator not properly parsed when selecting tags

### ISSUE THREAD

**Issue by enkeboll** [astronomer/astronomer-cosmos#823]
Migrating an issue raised in the [`#airflow-dbt` slack org](https://apache-airflow.slack.com/archives/C059CC42E9W/p1706214231926849):
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/060d5f80-a4aa-44cb-ae65-d89d143aeece)
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/a584dce3-da43-4e9e-b4e7-625fa766af8f)

Basically, the "plus" operator isn't properly parsed when used with tags. So `tag:every-hour` works but `+tag:every-hour` or `tag:every-hour+` result in empty graphs.  We use this syntax in our DBT Cloud scheduled jobs, even though it isn't explicitly called out in the [DBT docs](https://docs.getdbt.com/reference/node-selection/graph-operators):
![image](https://github.com/astronomer/astronomer-cosmos/assets/4869523/b8a47728-13f4-4d00-bfb8-4f10fb51b4b2)

I'm happy to try to take a stab at adding this functionality to [selector.py](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/dbt/selector.py), unless there's a reason to hold off.

**Comment by jbandoro** [comment]
Thanks @enkeboll for opening this issue!

> I'm happy to try to take a stab at adding this functionality to [selector.py](https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/dbt/selector.py), unless there's a reason to hold off.

That would be great, thanks!

**Comment by danielvdende** [comment]
Any update on this? We just hit the same issue 🥲

**Comment by enkeboll** [comment]
I personally haven't started work on this yet, though it's still in my backlog.

**Comment by tatiana** [comment]
@enkeboll @danielvdende, would you have bandwidth to work on this?

**Comment by gbatiz** [comment]
Would it be possible to for the development team to pick this up?

We are making use of custom node renderers for sources (sensor to wait on loading task) and exposures (operator triggering refresh in BI-tool), but schedule-related tags only make sense in case models.

We would like to run models tagged daily in a daily Airflow DAG, models tagged weekly in a weekly DAG, etc.
However, without properly functioning graph selectors, we cannot include sources and exposures for these models.

We were using

**Comment by tatiana** [comment]
It seems @mvictoria is solving the issue in #1150 🎉
