### ISSUE TITLE
Make GoogleCloudServiceAccountDictProfileMapping dataset profile argument optional

### ISSUE THREAD

**Issue by oliverrmaa** [astronomer/astronomer-cosmos#837]
**Context**

Given the issue [here](https://github.com/astronomer/astronomer-cosmos/issues/675) and the discussion around it [in slack](https://apache-airflow.slack.com/archives/C059CC42E9W/p1700049843620749), it follows that it would not be too far off for other profile mapping classes (like GCP) to have their schema (dataset in GCP terms) arguments made optional. 

The configurations in dbt (profiles.yml, dbt_project.yml, model level configs etc.) are meant to provide the dataset. As such, me and my team's initial thoughts were to not provide any arguments here since usually we would rely on this being handled inside of dbt instead of it being hard coded at the DAG (orchestration) level.

**Solution**

I believe its possible modifying this line [here ](https://github.com/astronomer/astronomer-cosmos/blob/72690d31ba6822ae6df56f4d56f26196234c80b5/cosmos/profiles/bigquery/service_account_keyfile_dict.py#L25) and the associated code similarly to this issue [here](https://github.com/astronomer/astronomer-cosmos/issues/675) would be the right path.

Me and/or my colleague are happy to to attempt this modification if there are no objections to this proposed change. Please let us know, thanks

**Comment by oliverrmaa** [comment]
@dosu-bot I have opened a PR #839 to address this issue and it has passed all tests and is ready for review, how do I request a review?

**Comment by tatiana** [comment]
It seems the `schema` property is mandatory in `profiles.yml` when using BQ:

Having a dbt project with `profiles.yml`:
```
airflow_db:
  target: dev
  outputs:
    bq:
      type: bigquery
      method: service-account
      project: <project>
      #schema: <dataset>
      threads: 2
      keyfile:  /usr/local/airflow/dbt/jaffle_shop/key.json
```

And the following 
```
models:
  jaffle_shop:
      +schema: dataset
```

Fails in both dbt 1.5 and 1.8:

Running `dbt-core==1.5.0`:
```
dbt ls --target bq --profile airflow_db
10:13:24  Running with dbt=1.5.0
10:13:32  Encountered an error:
Runtime Error
  Credentials in profile "airflow_db", target "bq" invalid: 'schema' is a required property
```

Running `dbt-core==1.8.2`:
```
dbt ls --target bq --profile airflow_db     
10:15:31  Running with dbt=1.8.2
10:15:40  Encountered an error:
Runtime Error
  Credentials in profile "airflow_db", target "bq" invalid: Runtime Error
    Must specify schema
```

I also attempted to do this while
