### ISSUE TITLE
[Bug] [1.4.0a] Seeds aren't working when partial parsing

### ISSUE THREAD

**Issue by dwreeves** [astronomer/astronomer-cosmos#880]
Not sure what's going on but after switching to 1.4.0a, my seeds stopped working.

```
[2024-03-05, 00:47:29 UTC] {log.py:232} WARNING - [[34m2024-03-05T00:47:29.333+0000[0m] {[34msubprocess.py:[0m94} INFO[0m - [35m(astronomer-cosmos)[0m - [Errno 2] No such file or directory: 'dags/dbt/seeds/us_states_seed.csv'[0m
```

Really weird.

There is a hint of what is going on. My dbt directory is `dags/dbt`, and relative to that it should be looking for `seeds/us_states_seed.csv`. However, it seems to literally be looking for `dags/dbt/seeds/us_states_seed.csv` inside the `dags/dbt` folder, meaning it's looking for `dags/dbt/dags/dbt/seeds/us_states_seed.csv`.

I don't have time to look into this for the next few days, I'll see this weekend what's going on.

dbt-core version: `dbt-core==1.6.4`
Astronomer Cosmos version: `astronomer-cosmos==1.4.0a1`
Python: `Python 3.11.6`

**Comment by tatiana** [comment]
@dwreeves, thanks for pointing this out. Could you confirm which configurations you're using to run this? I'll reproduce and try to get it fixed it until tomorrow

**Comment by dwreeves** [comment]
@tatiana Oh my god I figured it out and it's kind of funny and unfortunate.

Basically, the partial parse saves the location of the seed file. So if you use the partial parse file, but run in a different directory (aka tmp/something), it checks for the seed file at the location it saw it at when the partial parsing occurred.

There are a few potential avenues to solve the issue.

- I think changing the "cwd=" of the subprocess to be the Airflow home directory might work, and if so it should give you the best of both worlds-- you get to partial parse when running seeds and also the seeds are found just fine. **This would be my recommended solution along with passing --project-dir explicitly.** I don't know if this would have any potential downsides, though. For typical users it shouldn't. But who knows what people are doing. For safety I'd suggest adding an operator kwarg that is like, `set_cwd_to_tmp_dir: bool`, so users who experience issues can override to the previous behavior.
- If that doesn't work, another option is turning off partial parsing for seed and build.

**Comment by dwreeves** [comment]
Actually let me think for a second about what the solution should be for the API. Setting the cwd as the AIRFLOW_HOME would be bad for users who run "cd dags/dbt && dbt compile", and I imagine some users would. A more generic "dbt_working_dir" kwarg could make more sense.

**Comment by dwreeves** [comment]
In more positive news... this does confirm that I am successfully using the `partial_parse.msgpack` in Cosmos 1.4.0a 😉 Although it's a distressing way to figure out that it worked.

**Comment by dwreeves** [comment]
I'm falling behind on my mountain of real work and have to get back to that, but before I disappear for a couple days, I do have one more thought: **I would argue this is a bug in dbt-core.**

Basically: dbt-core should be resolving the path of the seed file _relative to the dbt project dir_ but it's actually saving the path _relative to the pwd of the executing command_. The latter behavior is a "bug," I think, and the former behavior is the more technically correct and robust behavior.

I'm actually a little surprised this seemingly hasn't caused any issues and bug reports for all dbt-core users, as it's not unreasonable to see how that could cause problems in other contexts.

**Comment by tatiana** [comment]
@dwreeves would it make more sense for us to solve the problem when we generate the `partial_parse.msgpack`?
How did you generate it?

**Comment by dwreeves** [comment]
> @dwreeves would it make more sense for us to solve the problem when we generate the partial_parse.msgpack?
How did you generate it?

Sigh, it's harder than I was hoping it would be.

Here are the instructions I have on how to get partial parsing working in 1.4.0 (it's a draft snippet from a blog I'm writing on this and a few other Cosmos topics):

> **For now, you must follow these directions _exactly_ or else it will not work!** Sorry.
> 
> 1. Go to one of your DbtOperator task logs in Airflow, and copy the `profile` YAML you see in the logs.
>    It will look something like this (example of a Snowflake profile):
> 
>    ```yaml
>    my_profile_name:
>        outputs:
>            airflow_target:
>                account: myaccount
>                database: mydatabase
>                password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
>                # ... etc. ...
>        target: my_target_name
>    ```
> 
> 2. Add this file to your Airflow project somewhere, e.g. `dags/dbt/profile/profiles.yml`.
> 
> 3. In your CICD, set the `DBT_PROFILES_DIR` env var to the folder you placed that file, e.g. `dags/dbt/profile`.
> 
> 4. Add `--profile [my_profile_name] --target [my_target_name]` to the `dbt parse` command you run in your CICD (replace `[my_profile_name]` and `[my_target_name]` with the appropriate names). **You must add these flags and you cannot just rely on defaults.** This is because dbt partial parsing does a checksum on a subset of the flags used in the CLI, and both `--profile` and `--target` are included in the checksum. Failing to add these flags means it won't work.
> 
>    ```shell
>    dbt deps
>    dbt parse --profile [my_profile_name] --target [my_target_name]
>    ```
> 
> 5. You must set up your CICD to run **the exact same connection you use in Cosmos**, meaning that you need to set `COSMOS_CONN_SNOWFLAKE_PASSWORD` to be the password you use in production. _Again_, similar deal as above: dbt does checksums when parsing, and every call to the `env_var()` macro creates a side-effect where the key-value pair of the env var is eventually put into the hash.
> 
> 6. Any `--vars` and env vars you use must also be included the exact same way you use them in Airflow. **You cannot rely on DagRun-specific or DAG-specific parameterized vars / env vars, otherwise partial parsing won't work.** (The 1.5.0 or later updates to partial parsing support should address this limitation, though.)
> 
> If you do **not** follow these steps exactly, you will see something like this in your logs:
> 
> ```shell
> Unable to do partial parsing because config vars, config profile, or config target have changed
> Unable to do partial parsing because profile has changed
> Unable to do partial parsing because env vars used in profiles.yml have changed
> ```
> 
> Or if something went really wrong, you'll see this:
> 
> ```python
> Unable to do partial parsing because saved manifest not found. Starting full parse.
> ```
> 
> If you do not see any of these messages in your logs, congrats, you have successfully made partial parsing work! 😊😊😊
>

**Comment by dwreeves** [comment]
One more note-- it's possible that merging the `--project-dir [tmpdir]` may make this bug go away. Unfortunately, subclassing the DbtOperators is extraordinarily difficult (I have actually discussed this with Julian and making stuff like that easier is something I think we can achieve in the near future), so it'd be better to just release `1.4.0a2` and cross our fingers that this solved the problem.

**Comment by dwreeves** [comment]
Can we release 1.4.0a2? I want to see if `--project-dir [tmpdir]` works to solve this issue. (Aka what I pushed in #873). I have a feeling it might. 

I would use the `node_converters` feature to test this change early, but I find that feature terribly cumbersome and hard to use and I'm struggling to get it to work, I'm sorry to say. It would be a lot easier to just do a second alpha release.

**Comment by tatiana** [comment]
@dwreeves When you have a chance, please, could you confirm if this issue was solved in 1.4.0?

**Comment by tatiana** [comment]
Hi @dwreeves did you have a chance of checking if this still happens in 1.4.1?

**Comment by dwreeves** [comment]
Not yet. I believe that adding `--project-dir [tmpdir]` should have fixed it though, but haven't fully confirmed.

**Comment by dwreeves** [comment]
Yep, it's good, the fix worked. Closing as completed.
