### ISSUE TITLE
[Feature request] Build operator as a test behavior: `TestBehavior.BUILD`

### ISSUE THREAD

**Issue by dwreeves** [astronomer/astronomer-cosmos#892]
In Cosmos 1.4, the "build" operator was added.

This is not currently being used in the DbtTaskGroup / DbtDag API. But there is one use case that can be supported: tests! You can run tests and a model in a single dbt invocation using `dbt build`.

Why would someone want this? A big reason is to reduce the time of DAG runs. Splitting out tests into two Airflow tasks-- one for the node and one for the test-- can slow things down for users who are facing huge bottlenecks in spinning up nodes, e.g. they are not using partial parsing.

This is probably not a simple change because it most likely requires changing some internal assumptions regarding how Cosmos parses DAGs.

I'm very open to someone else taking on this issue, too.

**Comment by tatiana** [comment]
Hi @dwreeves , I like your proposal.
What do you think we introduced this as `TestBehaviour.BUILD`? I believe this is a relatively small change.
