### ISSUE TITLE
Permission Denied for DBT Directory

### ISSUE THREAD

**Issue by mkeightleyentrata** [astronomer/astronomer-cosmos#897]
I had trouble getting cosmos dags to run on version 1.3.2. I would always end up with `PermissionError: [Errno 13] Permission denied: /path/to/dbt_project`. 

I tried `chmod -R 777 /path/to/dbt_project` in my Dockerfile with no luck.

The one solve I found was this version `astronomer-cosmos==1.4.0a1`. I added `invocation_mode=InvocationMode.DBT_RUNNER` to my ExecutionConfig and things started running as expected. Per the Invocation Modes section of [these docs ](https://astronomer.github.io/astronomer-cosmos/getting_started/execution-modes.html#execution-modes) there is the DBT_RUNNER invocation mode and the SUBPROCESS mode. While things run in the DBT_RUNNER mode, the SUBPROCESS mode still gives me the permission error. 

I am wondering what the difference between the DBT_RUNNER and SUBPROCESS modes where the SUBPROCESS mode throws the permission error but the DBT_RUNNER mode does not. And if there's a way to avoid the permission error in the latest official release since Invocation Modes can't be used until 1.4 is released

**Comment by tatiana** [comment]
Hi @mkeightleyentrata, thanks for reporting the issue!

Is this error happening when you try to execute tasks? Please share the steps/code so we can reproduce the problem you're facing. It would also be helpful if you could share more lines of the log stack trace. This usually helps us reproduce and fix the issue.

By default, Cosmos attempts to run dbt commands using a Python subprocess when using `ExecutionMode.LOCAL`.  The commands are executed within the same environment and with the same user privileges as the Python interpreter executing Airflow tasks. The main difference from a permission perspective that I can see when using `invocation_mode=InvocationMode.DBT_RUNNER` is that, by default, the system environment variables are used to run the command.

Could you try making the system environment variables available to the the process running the dbt command by setting operator args?
```
DbtDag(
    # ...
    operator_args={"append_env": True}
```

**Comment by mkeightleyentrata** [comment]
Hi @tatiana , thanks for your help. I get the following error on the run step of a model 
```
ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/base.py", line 246, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 370, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 237, in run_command
    result = self.run_subprocess(
  File "/usr/local/lib/python3.10/site-packages/cosmos/operators/local.py", line 189, in run_subprocess
    subprocess_result: FullOutputSubprocessResult = self.subprocess_hook.run_command(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cosmos/hooks/subprocess.py", line 75, in run_command
    self.sub_process = Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/dags/dbt'
```

Here is the dag that I'm attempting to run. I decided to take out the invocation_mode argument so that I can run on what I understand to be the latest official release of 1.3.2. I am able to run this successfully with or without `operator_args={"append_env": True}` on version 1.4.0a1. As soon as I switch to 1.3.2, it resorts back to the error above with or without append_env: True argument.
```
from datetime import datetime
from cosmos import ExecutionConfig, ProfileConfig, ProjectConfig, DbtDag, RenderConfig, LoadMode
from cosmos.profiles import RedshiftUserPasswordProfileMapping

DBT_ROOT_PATH = '/usr/local/airflow/dags/dbt'

profile_config = ProfileConfig(
    profile_name="my_profile",
    target_name="my_target",
    profile_mapping=RedshiftUserPasswordProfileMapping(
        conn_id="my_conn",
        profile_args={"schema": "my_schema"},
    )
)

execution_config = ExecutionConfig(dbt_executable_path=DBT_ROOT_PATH)
project_config = ProjectConfig(manifest_path=f"{DBT_ROOT_PATH}/target/manifest.json", project_name="my_project", dbt_project_path=DBT_ROOT_PATH)

cosmos_manifest_example = DbtDag(
    # dbt/cosmos-specific parameters
    project_config=project_config,
    profile_config=profile_config,
    render_config=RenderConfig(load_method=LoadMode.DBT_MANIFEST, select=[f"tag:cosmos-test"]),
    execution_config=execution_config,
    # normal dag parameters
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    dag_id="cosmos-manifest-example",
    operator_args={"append_env": True}
)
```

**Comment by tatiana** [comment]
Hi @mkeightleyentrata Cosmos 1.4 was officially released:
* https://github.com/astronomer/astronomer-cosmos/releases/tag/astronomer-cosmos-v1.4.0
* https://pypi.org/project/astronomer-cosmos/1.4.0/

Please, could you also share your `Dockerfile` so we can reproduce the issue you described with `SUBPROCESS`?

**Comment by pankajastro** [comment]
Hi @mkeightleyentrata, Are you still encountering this issue? If so, could you please provide the steps to reproduce it with the latest version?

**Comment by pankajastro** [comment]
Hey @mkeightleyentrata, Did you get a chance to look into my previous comments if possible can you please provider steps to reproduce it?

**Comment by pankajastro** [comment]
Please feel free to reopen it if you are still facing it issue
