### ISSUE TITLE
Testing behavior docs outdated regarding supported modes for on_warning_callback feature

### ISSUE THREAD

**Issue by mc51** [astronomer/astronomer-cosmos#909]
The testing behavior docs are outdated. [They say ](https://github.com/astronomer/astronomer-cosmos/blob/7c4d7d6e0c680a4847414ed4eb525b7baa27c8c1/docs/configuration/testing-behavior.rst?plain=1#L40 )that only the `local` executor mode is supporting the `on_warning_callback` feature: However, it also works with the `virtualenv` mode. The reason for this seems to bet that `virtualenv` mode didn't exist when the warning feature was implemented (here's the original feature [PR ](https://github.com/astronomer/astronomer-cosmos/pull/225)).

It would be helpful to fix this in the docs: We wanted to implement this functionality and gave up after checking the docs. But after looking at the source ourselves, we figured out that it actually also works with `virtualenv` execution mode. We then implemented and tested the functionality successfully.

**Comment by pankajastro** [comment]
Hey @mc51 would you like to submit a PR for this?

**Comment by pankajastro** [comment]
Looks like docs has been updated here https://astronomer.github.io/astronomer-cosmos/configuration/testing-behavior.html#warning-behavior
