### ISSUE TITLE
Add support for "test_type" select/exclude to DbtDag & DbtTaskGroup parsers

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#91]
See dbt docs on the `test_type` method [here](https://docs.getdbt.com/reference/node-selection/methods#the-test_type-method). 

```bash
$ dbt test --select test_type:generic        # run all generic tests
$ dbt test --select test_type:singular       # run all singular tests
```

Ultimately, in our parsers, we should be able to have a new parameter that looks something like this:

```python
# (Either the select or exclude parameter would be specified with the generic test_type - not both)
jaffle_shop = DbtTaskGroup(
    ...
    select={'test_types': ['generic']} # runs all generic tests in a dbt project
    exclude={'test_types': ['generic']} # runs all tests except for the generic ones in a dbt project
)
```

**Comment by pohek321** [comment]
@jlaneve wondering how applicable this is when running dbt core within Airflow. Particularly with the functionality you've provided to execute `dbt test` steps after each `dbt run` node or at the end of a dbt project. I could see where this could be applicable if our customers wanted to create entire DAGs and Task Groups for data quality checks -- but that almost feels like an anti-pattern. Do you have any thoughts?

**Comment by jlaneve** [comment]
hmm, I'm thinking with our run/test abstraction it could be worth creating a new arg called something like `test_args`:

```
jaffle_shop = DbtTaskGroup(
    ...
    test_args={
        'test_types': ['generic']
    }
)
```

Then, if a Test task runs we can pass it the args, and if there are no tests of that type it's just going to succeed without running anything.

Thoughts?

**Comment by tatiana** [comment]
Complementing, as of Cosmos 1.x, this functionality only works on `LoadMode.DBT_LS`. We should also support it when the DAG/TaskGroup uses `LoadMode.DBT_MANIFEST` and `LoadMode.CUSTOM`.
