### ISSUE TITLE
Add support for dbt-clickhouse adapter

### ISSUE THREAD

**Issue by chrishronek** [astronomer/astronomer-cosmos#95]
Requested via LinkedIn comment. 
- See dbt docs [here](https://docs.getdbt.com/reference/warehouse-setups/clickhouse-setup)
- See clickhouse home page [here](https://clickhouse.com/)

**Comment by infl18** [comment]
Hi, is anyone solving this problem?

**Comment by vargacypher** [comment]
Hi @pohek321 could u please help ? Wich parts of the project i need to look/change to solve this issue ?
I  know providers and profiles are the main ones to look at

**Comment by jlaneve** [comment]
> Hi @pohek321 could u help me ? Wich parts of the project i need to look/change to solve this issue ?
> 
> I  know providers and profiles are the main ones to look at
> 
> 
> 
> 
> 
>  I am willing to submit a PR!

Hey @vargacypher - I have a PR open that should simplify the process of adding new profiles quite a bit. I'd recommend waiting until it's merged to contribute a new profile! In the meantime, give the PR a look and let me know what you think of the profile/connection definitions. 

https://github.com/astronomer/astronomer-cosmos/pull/271

**Comment by roadan** [comment]
@jlaneve I actually have an initial working version of this using your refactored code which I'd love to PR, however, as far as I can see there is no clickhouse connection so my local version is using the generic connection which I think is not a great solution. Any thoughts on how it's best to progress with this?

**Comment by CorsettiS** [comment]
@roadan do you mind creating a PR so I may be able to check it out? This is also a PR that interests me quite a lot. And about the connection type, there is no clickhouse connection for airflow, therefore using a generic connection type is how clickhouse users have been doing so far, which makes your approach totally correct ✅

**Comment by roadan** [comment]
@CorsettiS will do, I just want to add some tests before I do that. The PR should be ready tomorrow.
My concern with the current PR is that the required fields are few so essentially my connector will be able to claim most generic connections. Maybe I can add an extra just for `can_claim_connection` to match on?
