### ISSUE TITLE
Sensitive information being logged by ProfileConfig 

### ISSUE THREAD

**Issue by jsborralho** [astronomer/astronomer-cosmos#970]
**Context** 
While using Airflow connections via Cosmos’ profile mappings we are seeing sensitive information being dumped into airflow logs. When run_command is executed, ensure_profile() of ProfileConfig is called and the content of the profile is logged. See code here https://github.com/astronomer/astronomer-cosmos/blob/main/cosmos/config.py#L295

Since we are using GoogleCloudServiceAccountDict mapping with a service account connection the content of the svc keyfile is logged into airflow.

**Goal**
We can always extend the behaviour of ProfileConfig ourselves and override that logging behaviour, however I would like to confirm if I am doing something that I shouldn't because this certainly is an odd practice.

Thanks in advance.

**Comment by tatiana** [comment]
@jsborralho thank you very much for reporting this issue!

Could you confirm which version of Cosmos you're using?

Cosmos has support to defining sensitive information, and in those cases it is not hard-coded in the profile nor printed, but added to an environment variable:
https://github.com/astronomer/astronomer-cosmos/blob/e2a454455983b5cfeffd69aa7980c66369edd0e9/cosmos/profiles/bigquery/service_account_keyfile_dict.py#L29

You can see this being successfully used in Postgres:
https://github.com/astronomer/astronomer-cosmos/blob/e2a454455983b5cfeffd69aa7980c66369edd0e9/cosmos/profiles/postgres/user_pass.py#L25-L26

Would you like to contribute to improving the behaviour in `GoogleCloudServiceAccountDictProfileMapping`?

**Comment by jsborralho** [comment]
Ola @tatiana, thanks for the quick support.

Will do.
I will give a deeper look to the secret_field logic since its quite unknown to me. 

Obrigado!

**Comment by tatiana** [comment]
Está ótimo, obrigada, @jsborralho :)
