### ISSUE TITLE
Hook to be called after cosmos task execution 

### ISSUE THREAD

**Issue by SiddiqueAhmad** [astronomer/astronomer-cosmos#976]
To pipe dbt test results.json, We need to register hook with results so users can use it for further integration. We need this for integration with openmetadata for data quality.

**Comment by tatiana** [comment]
Thanks a lot, @SiddiqueAhmad , for writing down this!

Giving further context, this came from a discussion in Slack #airflow-dbt: https://apache-airflow.slack.com/archives/C059CC42E9W/p1715857421750369

It is a valid use case, and we don't have an out-of-the-box solution at the moment.

Similar to how we're handling `on_warning_callback`:
https://github.com/astronomer/astronomer-cosmos/blob/af11d348cd87bdbd7cdef52535aaca74287b18e8/cosmos/operators/local.py#L592

We could have a mechanism for users to define a function that would be called after Cosmos tasks execution, that could receive the result/context.

Did you check with your team if someone would be available/interested in implementing this, @SiddiqueAhmad ?

**Comment by GabrielEisenbergOlympus** [comment]
Hi @tatiana, thanks for looking into this. I also need this functionality - unfortunately quite urgently to meet a requirement. 

Is there anything that can be done in the meantime to address this before it is cosmos native functionality? In particular I need to access the `run_results.json` and `manifest.json` after each run, however, my major challenge is retrieving the `/tmp` subfolder in which the task is run. With that I could make my own workaround until this functionality is available.

I attempted the `post_execute` behaviour that @ghjklw suggested, however, it points to a different subdirectory. 

Thanks so much!

**Comment by GabrielEisenbergOlympus** [comment]
Hi @pankajkoti, thanks so much for implementing this! I'm going to trial this with a custom callback. 

What I'm not clear on is how I would access the temporary directory, to get to the target directory from the dbt run. I have tried to retrieve the directory with `tempfile.gettempdir()` which returns `/tmp`, yet in this case the run happened in `/tmp/tmpq79u8zks/`. Please can you clarify this.

Thanks so much!

**Comment by pankajkoti** [comment]
hi @GabrielEisenbergOlympus 

If you’re planning to write a custom callback, you can refer to this callback function provided by Cosmos: [callback reference](https://github.com/astronomer/astronomer-cosmos/blob/184e45fc23044e52fa2033f4f546ebfd4ab2c249/cosmos/io.py#L14).

You can create a similar function, where the first argument represents the path to the temporary directory (e.g., project_dir in the example callback). Cosmos passes the path to the temporary directory as the first argument, allowing you to access the target directory from there.

**Comment by GabrielEisenbergOlympus** [comment]
Thanks for clarifying @pankajkoti! It wasn't clear to me from looking at the code and docs that the temporary directory was automatically passed in as an argument.

My mistake was missing where the callback was being applied. I assumed it could be applied like other Airflow callbacks at the DAG or `default_args` level. I'm still busy trialing this and am curious how this will interact with more complex DAGs that combine cosmos operators with say Python or bash operators.

**Comment by pankajkoti** [comment]
hi @GabrielEisenbergOlympus , you can very well pass this callback function to individual Cosmos operators in an Airflow DAG that contains other operators. You can check an example here https://github.com/astronomer/astronomer-cosmos/blob/184e45fc23044e52fa2033f4f546ebfd4ab2c249/dev/dags/example_operators.py#L46

Please let me know if you'd have further questions.

**Comment by GabrielEisenbergOlympus** [comment]
Thanks again @pankajkoti. In our case we mainly use `DbtDag` and `DbtTaskGroup` which I assume will accept the same argument. Hopefully the testing will progress smoothly and this can be integrated properly!

**Comment by pankajkoti** [comment]
Yes indeed @GabrielEisenbergOlympus . You would need the callback function in the `operator_args` param for `DbtDag` and `DbtTaskGroup`. Here is an example https://github.com/astronomer/astronomer-cosmos/blob/a56387037f731c298c4dd13268e158d600c2a364/dev/dags/cosmos_callback_dag.py#L27

Please also refer to the Cosmos documentation regarding this: https://astronomer.github.io/astronomer-cosmos/configuration/callbacks.html

Happy to answer if there are any follow-up questions
