### ISSUE TITLE
Support associating tests to multiple parents, if they have multiple parents

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#978]
Original discussion in: https://github.com/astronomer/astronomer-cosmos/pull/751#issuecomment-1878578854

Cosmos can improve its implementation towards tests with multiple parents - we should make it consistent with dbt.

**Comment by kzajaczkowski** [comment]
@tatiana, thank you, but unfortunately, I wouldn't be able to contribute at this time.
