### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by tatiana** [astronomer/astronomer-cosmos#980]
* #840 
* #932 
* #924
* #925 
* #647 
* #926

**Comment by dwreeves** [comment]
This is not directly a performance improvement, and this has been discussed before in terms of how to expand scope of Cosmos's docs, but I am in favor of resurfacing #832. Many (definitely not all! but many) user issues about performance relate to under-configuration of Cosmos itself (most notably use of `LoadMode.DBT_LS` which cripples the scheduler), and having a page in the docs with suggestions would make sense.
